### PR TITLE
fix(core): fix rare error on index drop that can suspend table

### LINKED ISSUE #6146: Exception in drop index, table suspended
### To reproduce

```
2025-09-15T17:59:39.315234Z C i.q.c.TableWriter exception on index drop [txn=98593050, table=tr, column=eid, error=
java.lang.StackOverflowError
	at io.questdb.std.IntGroupSort.partition(IntGroupSort.java:55)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:61)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
...
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.questdb.std.IntGroupSort.quickSortImpl(IntGroupSort.java:63)
	at io.q
2025-09-15T17:59:39.318803Z C i.q.g.e.o.AlterOperation could not alter table [table=tr~149, command=5, msg=cannot remove index for [txn=98593050, table=tr, column=eid]: , errno=0]
2025-09-15T17:59:39.318867Z E i.q.c.w.ApplyWal2TableJob error applying SQL to wal table [table=tr~149, sql=ALTER TABLE tr ALTER COLUMN eid DROP INDEX, msg=cannot remove index for [txn=98593050, table=tr, column=eid]: , errno=0]
2025-09-15T17:59:39.327685Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=tr~149, seqTxn=102965850, error=
io.questdb.cairo.CairoException: [0] cannot remove index for [txn=98593050, table=tr, column=eid]:
]
```

### QuestDB version:

9.0.3

### OS, in case of Docker specify Docker and the Host OS:

NA

### File System, in case of Docker specify Host File System:

NA

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ideoma**
fixes #6146

### CODE REVIEW

**Comment by ideoma** [comment]
@coderabbitai review

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/IntGroupSort.java|22|22|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/IntGroupSort.java|22|22|100.00%|

File: core/src/test/java/io/questdb/test/std/IntListTest.java [hunk 1]
```diff
@@ -282,6 +282,37 @@ public void testSortGroupsNotSupported() {
         }
     }
 
+    @Test
+    public void testSortGroupsStackOverflowScenario() {
+        // Create a scenario that would trigger deep recursion in quicksort
+        // by creating reverse sorted data which causes worst-case O(n) recursion depth
+        int groupSize = 3;
+        int numGroups = 50000; // Large size to ensure stack overflow with recursive implementation
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/test/std/IntListTest.java]: can we overflow stack with fewer groups?

Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/std/IntListTest.java]: 3s test on my desktop, probably 30s test on CI

Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/std/IntListTest.java]: 8s on CI

Comment (ideoma) [reply core/src/test/java/io/questdb/test/std/IntListTest.java]: CI is not bad with 50k, it's 1-4 secs

image

I reduced it to 30k; it's the minimum when the old bug can be reproduced.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/IntGroupSort.java|22|22|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by jerrinot** [comment]
I only reviewed and tested https://github.com/questdb/questdb/pull/6147/commits/4f38f32228ad970e07255a31e7abc19697e1b4cc and it look fine - the test failure is no longer reproducible.

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/IntGroupSort.java|22|22|100.00%|
