### PR TITLE
fix(sql): better overflow behaviour when converting timezones

### LINKED ISSUE #4752: friction when converting timestamps due to numeric overflow
### To reproduce

See https://community.questdb.io/t/sql-format-for-converting-to-microseconds/82

Values in expressions such as: `1720468802 * 1000000` are interpreted as ints, and compiled into `MulIntFunctionFactory`.
This factory does not handle numeric overflow. However, we this form of expression is common for increasing the precision of timestamps i.e from unix seconds to unix microseconds.

```sql
SELECT
  to_utc(1720468802000000, 'Europe/Berlin'),
  to_utc(1720468802 * 1000000, 'Europe/Berlin'),
  to_utc(1720468802, 'Europe/Berlin');
  to_utc(1720468802)
```

image

This can be worked round using `L` suffix i.e `1720468802 * 1000000L` .

Older articles do not use this suffix, so this may not have been a problem in the past: https://questdb.io/blog/2021/11/01/plotly-finnhub-realtime-dashboard/

Perhaps overflow can be handled better, or at least for this pattern with to_utc(), we can force it to use `MulLongFunctionFactory` instead.

### QuestDB version:

8.0.1

### OS, in case of Docker specify Docker and the Host OS:

N/A

### File System, in case of Docker specify Host File System:

N/A

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
fixes #4752

This query now returns the expected timestamps.
```sql
SELECT
  to_utc(1720468802000000, 'Europe/Berlin'),
  to_utc(1720468802 * 1000000, 'Europe/Berlin'),
from long_sequence(1);
```

### CODE REVIEW

**Comment by jerrinot** [comment]
the question remains whether it's a good idea to fix this for some functions, but not for others. 
also - I am not entirely sure whether this can make JIT-compiled filters behave differently than non-JITed filters. But I believe our JIT limitations (operands have to have the same size) then we should be fine. Let's see what tests think.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 6 (16.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 21 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/TimestampAwareIntConstant.java|7|10|70.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|

File: core/src/test/java/io/questdb/test/griffin/engine/functions/math/MulIntFunctionFactoryTest.java [hunk 1]
```diff
@@ -57,6 +57,16 @@ public void testSimple() throws SqlException {
         call(10, 81).andAssert(810);
     }
 
+    @Test
+    public void testTimestamp() throws SqlException {
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/test/griffin/engine/functions/math/MulIntFunctionFactoryTest.java:61]: i made "call" method deprecated, please replace new tests with "assertSql" or "assertQuery" calls

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java [hunk 2]
```diff
@@ -81,6 +81,17 @@ public Function getRight() {
             return right;
         }
 
+        @Override
+        public long getTimestamp(Record rec) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java:85]: this should work generically as in: explicit constants should be treated the same way as implicit constants, e.g. `1720468802 * 1000000` and `1720468802000000` should be a long value.

Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java:85]: this should produce long value
```
select 1720468802 * 1000000;
```

Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java:85]: `+` and `-` should also be overflow aware

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 21 (80.95%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/TimestampAwareIntConstant.java|6|10|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|

File: core/src/test/java/io/questdb/test/griffin/engine/functions/math/AddIntFunctionFactoryTest.java [hunk 3]
```diff
@@ -25,32 +25,25 @@
...
 
 public class AddIntFunctionFactoryTest extends AbstractFunctionFactoryTest {
 
     @Test
-    public void testLeftNull() throws SqlException {
-        call(Numbers.INT_NULL, 10).andAssert(Numbers.INT_NULL);
-    }
-
-    @Test
-    public void testOverflow() throws SqlException {
```
Comment (sklarsa) [inline core/src/test/java/io/questdb/test/griffin/engine/functions/math/AddIntFunctionFactoryTest.java:42]: @bluestreak01 would new treatment of int overflow in addition functions be a breaking change? I've removed this test

Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/griffin/engine/functions/math/AddIntFunctionFactoryTest.java:42]: Yep, it would be a mild breaking change. I don’t think anyone would miss random numbers as a result of overflow

File: core/src/main/java/io/questdb/griffin/engine/functions/math/NegIntFunctionFactory.java [hunk 4]
```diff
@@ -71,6 +71,11 @@ public int getInt(Record rec) {
             return value != Numbers.INT_NULL ? -value : Numbers.INT_NULL;
         }
 
+        @Override
```
Comment (sklarsa) [inline core/src/main/java/io/questdb/griffin/engine/functions/math/NegIntFunctionFactory.java:74]: @bluestreak01 this causes the single test failure in `CompiledFilterRegressionTest.testColumnArithmeticsNullComparison` in a single case:
`result mismatch for query: select * from x where i64+-i32`

Expected returns rows where `i64==null` but actual returns rows where both `i64==null AND i32==null`.

When I delete this function, this test passes

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/AddIntFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/NegIntFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/SubIntFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/AddIntFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/NegIntFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/SubIntFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/AddIntFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/NegIntFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/MulIntFunctionFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/math/SubIntFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
