### PR TITLE
fix(core): fix vacuum command deleting live table columns

### LINKED ISSUE #3588: VACUUM races with UPDATE TABLE
### Describe the bug

_No response_

### To reproduce

During the long-running UPDATE table for column `uuid` a VACUUM table ran it resulting in a missing column file.

```
C i.q.c.h.p.JsonQueryProcessorState [113] error [msg=`could not open read-only [file=/var/lib/questdb/db/logs/2023-02-01T00.499652/uuid.d.20778556]`, errno=2, q=`update logs set uuid = cast(id as uuid) where start_time in '2023-04'`]
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:7.2.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ideoma**
fixes #3588

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|1|1|100.00%|

File: core/src/test/java/io/questdb/test/cairo/TableReaderTest.java [hunk 1]
```diff
@@ -2908,6 +2908,42 @@ public void testRemovePartitionByYearReload() throws Exception {
         testRemovePartitionReload(PartitionBy.YEAR, "2020", 3000, current -> Timestamps.addYear(Timestamps.floorYYYY(current), 1));
     }
```
Comment (bziobrowski) [inline core/src/test/java/io/questdb/test/cairo/TableReaderTest.java:2910]: Is this test related to the change ? It passes even when I revert the change .

**Review by bziobrowski — APPROVED** [review]

File: core/src/test/java/io/questdb/test/cairo/TableReaderTest.java (hunk 1 above)
Comment (ideoma) [reply core/src/test/java/io/questdb/test/cairo/TableReaderTest.java:2910]: This test was supposed to be for #3582
