### PR TITLE
fix(sql): fix stack overflow exception in WITH clause parsing

### LINKED ISSUE #2954: Uh-oh. Error! in logs on questdb 6.7
### Describe the bug

Received the following stack trace in logs:
```
2023-01-27T18:01:57.584921Z I i.q.c.h.p.JsonQueryProcessorState [89] exec [q='WITH all_transactions AS (
  SELECT ts, wallet_address, token_address, sent, received, hash as transaction_id, 'eth' as chain, workspace FROM 'eth_transactions'
  UNION ALL
  SELECT ts, wallet_address, token_address, sent, received, signature as transaction_id, 'sol' as chain, workspace from 'sol_transactions'
), transactions_90_days_ago AS (
  SELECT wallet_address, count() FROM all_transactions WHERE ts BETWEEN dateadd('d', -180, now()) and dateadd('d', -90, now())
), transactions_90_days AS (
  SELECT wallet_address, count() FROM all_transactions WHERE ts >= dateadd('d', -90, now())
), balance as (
  SELECT wallet_address, balance FROM balance WHERE token_address = ('SOL') LATEST ON ts PARTITION BY wallet_address
), balance_all_tokens_native as (
  SELECT wallet_address, balance FROM balance LATEST ON ts PARTITION BY wallet_address
)
SELECT wallet_address, balance FROM balance LATEST ON ts PARTITION BY wallet_address
-- EXPLAIN SELECT * FROM transactions_90_days_ago
-- SELECT wallet_address, chain, transactions_90d 
-- FROM all_transactions LATEST ON ts PARTITION BY wallet_address
']
2023-01-27T18:01:57.584947Z I i.q.c.h.p.QueryCache miss [thread=questdb-shared-2, sql=WITH all_transactions AS (
  SELECT ts, wallet_address, token_address, sent, received, hash as transaction_id, 'eth' as chain, workspace FROM 'eth_transactions'
  UNION ALL
  SELECT ts, wallet_address, token_address, sent, received, signature as transaction_id, 'sol' as chain, workspace from 'sol_transactions'
), transactions_90_days_ago AS (
  SELECT wallet_address, count() FROM all_transactions WHERE ts BETWEEN dateadd('d', -180, now()) and dateadd('d', -90, now())
), transactions_90_days AS (
  SELECT wallet_address, count() FROM all_transactions WHERE ts >= dateadd('d', -90, now())
), balance as (
  SELECT wallet_address, balance FROM balance WHERE token_address = ('SOL') LATEST ON ts PARTITION BY wallet_address
), balance_all_tokens_native as (
  SELECT wallet_address, balance FROM balance LATEST ON ts PARTITION BY wallet_address
)
SELECT wallet_address, balance FROM balance LATEST ON ts PARTITION BY wallet_address
-- EXPLAIN SELECT * FROM transactions_90_days_ago
-- SELECT wallet_address, chain, transactions_90d 
-- FROM all_transactions LATEST ON ts PARTITION BY wallet_address
]
2023-01-27T18:01:57.683972Z C i.q.c.h.p.JsonQueryProcessorState [89] Uh-oh. Error!
java.lang.StackOverflowError
	at io.questdb.std.Chars.lowerCaseAsciiHashCode(Chars.java:595)
	at io.questdb.std.AbstractLowerCaseAsciiCharSequenceHashSet.keyIndex(AbstractLowerCaseAsciiCharSequenceHashSet.java:65)
	at io.questdb.std.LowerCaseAsciiCharSequenceObjHashMap.get(LowerCaseAsciiCharSequenceObjHashMap.java:62)
	at io.questdb.griffin.ExpressionParser.parseExpr(ExpressionParser.java:953)
	at io.questdb.griffin.SqlParser.expr(SqlParser.java:2132)
	at io.questdb.griffin.SqlParser.parseSelectClause(SqlParser.java:1558)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:867)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:899)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:899)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:899)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:899)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:899)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at io.questdb.griffin.SqlParser.parseDml0(SqlParser.java:899)
	at io.questdb.griffin.SqlParser.parseDml(SqlParser.java:794)
	at io.questdb.griffin.SqlParser.parseAsSubQuery(SqlParser.java:2194)
	at io.questdb.griffin.SqlParser.parseAsSubQueryAndExpectClosingBrace(SqlParser.java:350)
	at io.questdb.griffin.SqlParser.parseWith(SqlParser.java:1811)
	at io.questdb.griffin.SqlParser.parseSelectFrom(SqlParser.java:1685)
	at io.questdb.griffin.SqlParser.parseFromClause(SqlParser.java:1088)
	at i2023-01-27T18:01:57.685045Z I i.q.c.h.HttpConnectionContext kicked out [fd=89]
2023-01-27T18:01:57.685048Z I http-server scheduling disconnect [fd=89, reason=5]
2023-01-27T18:01:57.685115Z I http-server disconnected [ip=10.2.18.56, fd=89, src=queue]
```

### To reproduce

query that triggered the error:
```sql
WITH all_transactions AS (
  SELECT ts, wallet_address, token_address, sent, received, hash as transaction_id, 'eth' as chain, workspace FROM 'eth_transactions'
  UNION ALL
  SELECT ts, wallet_address, token_address, sent, received, signature as transaction_id, 'sol' as chain, workspace from 'sol_transactions'
), transactions_90_days_ago AS (
  SELECT wallet_address, count() FROM all_transactions WHERE ts BETWEEN dateadd('d', -180, now()) and dateadd('d', -90, now())
), transactions_90_days AS (
  SELECT wallet_address, count() FROM all_transactions WHERE ts >= dateadd('d', -90, now())
), balance as (
  SELECT wallet_address, balance FROM balance WHERE token_address = ('SOL') LATEST ON ts PARTITION BY wallet_address
), balance_all_tokens_native as (
  SELECT wallet_address, balance FROM balance LATEST ON ts PARTITION BY wallet_address
)
SELECT wallet_address, balance FROM balance LATEST ON ts PARTITION BY wallet_address
-- EXPLAIN SELECT * FROM transactions_90_days_ago
-- SELECT wallet_address, chain, transactions_90d 
-- FROM all_transactions LATEST ON ts PARTITION BY wallet_address
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.7
- **OS**: linux
- **Browser**: N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2954

PR prevents stack overflow on table resolution by using the same list of WITH clauses for each use (and re-evaluation) of WITH alias. 

Example: 
```sql
CREATE TABLE balance (
  address LONG,
  balance DOUBLE
);

WITH balance as ( SELECT * FROM balance WHERE address = 1 ),
          balance_other as ( SELECT * FROM balance )
SELECT * FROM balance;
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 35 / 35 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/WithClauseModel.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/model/WithClauseModel.java [hunk 1]
```diff
@@ -24,36 +24,74 @@
...
+            withClausesInitialized = true;
+        }
+        return withClauses;
+    }
+
+    public void of(int position, LowerCaseCharSequenceObjHashMap<WithClauseModel> withClauses, QueryModel model) {
         this.position = position;
         this.model = model;
+        this.originalWithClauses = withClauses;
+        this.originalWithClausesSize = withClauses.size();
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:72]: nit: `size()` is cheap and can be in-place instead of storing it in a field.

File: core/src/main/java/io/questdb/griffin/model/WithClauseModel.java [hunk 2]
```diff
@@ -24,36 +24,74 @@
...
 
     @Override
     public void clear() {
-        this.position = 0;
-        this.model = null;
+        position = 0;
+        model = null;
+        originalWithClauses = null;
+        originalWithClausesSize = -1;
+        withClauses = null;
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:53]: Don't we need to set `withClausesInitialized` to `false` somewhere here?

File: core/src/main/java/io/questdb/griffin/model/WithClauseModel.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:72]: Do we compile queries on the hot path?

Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:72]: size() is stored in field because withClause can grow between with clause re-evaluations.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 35 / 35 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/WithClauseModel.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/model/WithClauseModel.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:72]: > size() is stored in field because withClause can grow between with clause re-evaluations.

This deserves a comment.

File: core/src/main/java/io/questdb/griffin/model/WithClauseModel.java (hunk 2 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:57]: Good catch ! Fixed in 7d0849b9 .

File: core/src/main/java/io/questdb/griffin/model/WithClauseModel.java (hunk 1 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/model/WithClauseModel.java:76]: Added comment in 7d0849b9 .

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 36 / 36 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/WithClauseModel.java|23|23|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 36 / 36 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/WithClauseModel.java|23|23|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|1|1|100.00%|
