### PR TITLE
fix(pgwire): fix query cache hit logging for prepared statements

### LINKED ISSUE #5187: Query cache is not always used in PGWire
TBD by @kafka1991 

### To reproduce

Modify `PGWireInsertSelectBenchmark` to run only selector threads and change the query to `SELECT 1;`. Uncomment this line:
```java
properties.setProperty("prepareThreshold", String.valueOf(-1));
```
to enabled binary format.

Then run the benchmark. Observe that the query cache isn't always used:
```
2024-11-22T15:22:11.173492Z I i.q.g.e.QueryProgress exe [id=36527256, sql=`select 1`, principal=admin, cache=false, jit=false]
2024-11-22T15:22:11.173492Z I i.q.g.e.QueryProgress exe [id=36527257, sql=`select 1`, principal=admin, cache=true, jit=false]
2024-11-22T15:22:11.173492Z I i.q.g.e.QueryProgress fin [id=36527254, sql=`select 1`, principal=admin, cache=true, jit=false, time=1954]
2024-11-22T15:22:11.173493Z I i.q.g.e.QueryProgress fin [id=36527255, sql=`select 1`, principal=admin, cache=false, jit=false, time=1923]
```

### QuestDB version:

8.2

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kafka1991**
Fixes #5187

There are two scenarios in which PGConn won't use the TypeAndSelect compile cache:
1. When the query is encountered for the first time, or if the cache has expired in TypeAndSelectCache(LRU).
2. When multiple identical queries are received concurrently. Since TypeAndSelectCache is a global cache, only the first "arrive" query will get the cache(`poll()` from `tasCache`), while the others must be rebuilt until a finished query is added back to the cache.

Both two scenarios meets expectations. The problem describe in the issue just a log print problem. In `PGWireInsertSelectBenchmark`, the query execute use prepare-execute mode, which query only need to compile once in prepare stage.
However, the cacheHit variable was set in execute-stage which obtained from prepare stage. There is no much meaning of cacheHit flag for execute-stage. So here we can simplely put cacheHit as true in execute-stage.

WDYT @puzpuzpuz

### CODE REVIEW

File: core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java [hunk 1]
```diff
@@ -1390,7 +1390,7 @@ private void msgExecuteSelect(
             }
 
             sqlExecutionContext.getCircuitBreaker().resetTimer();
-            sqlExecutionContext.setCacheHit(cacheHit);
+            sqlExecutionContext.setCacheHit(true);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java:1393]: `msgExecuteSelect` is used in many modes, except for simple. We can't unconditionally set cache hit flag to true here as it could be the case that the factory wasn't in the query cache, but was just created.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java]: With this approach the very first query execution will print `cache=true` which is incorrect. Maybe it'd be simpler to add a long counter field for the number of `PGPipelineEntry` executions with the same factory instance?

File: core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java [hunk 2]
```diff
@@ -1391,6 +1391,10 @@ private void msgExecuteSelect(
 
             sqlExecutionContext.getCircuitBreaker().resetTimer();
             sqlExecutionContext.setCacheHit(cacheHit);
+            if (preparedStatement && !cacheHit) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java:1394]: It's a good idea to add a clarifying comment here to describe the intent.

Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java:1394]: nit: could be simpilified to
```suggestion
            if (preparedStatement) {
```

**Review by puzpuzpuz — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@kafka1991 thanks for the contribution!
