### PR TITLE
fix(sql): breaking change 💥- invalid column error returned from GROUP BY on joined tables

### LINKED ISSUE #6273: Invalid column error returned from GROUP BY joined tables
### To reproduce

The below query returns `Invalid column: t2.price` error:
```sql
CREATE TABLE trades (sym symbol, price double, amount double, ts timestamp) timestamp(ts) partition by day;
CREATE TABLE trades2 (sym symbol, price double, amount double, ts timestamp) timestamp(ts) partition by day;

SELECT t1.ts, t1.price, t2.price / sum(t1.amount) FROM trades t1 JOIN trades2 t2 ON (sym);
```

A similar error is returned when `t2.price / sum(t1.amount)` is changed to `t1.price / sum(t1.amount)`

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 24.04

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #6273

Other than that, SAMPLE BY queries with selected expressions mixing timestamp and aggregate functions now use multi-threaded execution plan. Example of such query:
```sql
SELECT ts, count()::double / datediff('h', ts, dateadd('d', 1, ts, 'Europe/Copenhagen')) AS Coverage
FROM 'x'
SAMPLE BY 1d ALIGN TO CALENDAR TIME ZONE 'Europe/Copenhagen';
```

Also improves the way we choose execution plan for SAMPLE BY and GROUP BY queries. Namely, now we avoid adding duplicate group keys and, instead, reuse the existing ones. This means that in a query like the following one:
```sql
SELECT symbol, price, price / sum(amount) FROM trades WHERE timestamp in today();
```
we now end up with `symbol, price` as the group keys instead of `symbol, price, price price1` (notice the extra `price1` key).

### Breaking change

When designated timestamp is selected multiple times, under different aliases, the ordered (sorted in asc order) column picked up by the query engine will be the first one. For instance, in the below example column `ts1` will be marked as the ordered column:
```sql
select ts as ts1, ts as ts2, price, amount
from trades;
```

If one of the selected columns is used as the first ORDER BY column, it's always preferred, no matter what its position is in the `SELECT` clause:
```sql
-- here, ts2 is used as the ordered column
select ts as ts1, ts as ts2, price, amount
from trades
order by ts2;
```

Otherwise, unaliased column, i.e. the selected column matching with the designated column name, is preferred.

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
@coderabbitai review

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 1]
```diff
@@ -5202,63 +5250,47 @@ private QueryModel rewriteSampleBy(@Nullable QueryModel model, @Transient SqlExe
...
+                        n--;
+
+                        if (checkForChildAggregates(qc.getAst())) {
+                            // Ok, it's an expression with mixed timestamp references and aggregate functions.
+                            // Replace aggregate functions with aliases and add the functions to the group by model.
+                            // This way an expression like `select timestamp, count() / timestamp::long`
+                            // Is turned into `select timestamp, count / timestamp::long from (select count(), ...`
+                            needRemoveColumns += rewriteTimestampMixedWithAggregates(qc.getAst(), model);
+                        }
+
```
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java:5271]: Nested model holds table name expression and sample by nodes, nothing more.

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 2]
```diff
@@ -4479,8 +4479,18 @@ private RecordCursorFactory generateSelectChoose(QueryModel model, SqlExecutionC
...
+        CharSequence timestampName = null;
+        int timestampNameDot = -1;
+        if (timestampIndex != -1) {
+            timestampName = factory.getMetadata().getColumnName(timestampIndex);
+            timestampNameDot = Chars.indexOfLastUnquoted(timestampName, '.');
+        }
+        final CharSequence firstOrderByColumn = model.getOrderBy().size() > 0 && model.getOrderBy().getQuick(0).type == LITERAL
+                ? model.getOrderBy().getQuick(0).token
+                : null;
+
```
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4507]: The outer `if (index == timestampIndex)` branch guarantees that `timestampName` it not null.

**Comment by ideoma** [comment]
nit: you can remove the ignore tag from `SampleByTest.testSampleByWithProjection2()` and modify the expected results, it's fixed now

**Comment by puzpuzpuz** [comment]
> nit: you can remove the ignore tag from `SampleByTest.testSampleByWithProjection2()` and modify the expected results, it's fixed now

Thanks for the heads-up. I didn't check the disabled tests. Enabled in 6dc3685b2bcdeaefa9c198689df8722023d9829c

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 3]
```diff
@@ -4504,14 +4514,23 @@ private RecordCursorFactory generateSelectChoose(QueryModel model, SqlExecutionC
...
+                // timestamp in case of multiple timestamp aliases, e.g. `select ts, ts as ts1, ...`.
+                // That's to choose the optimal plan in generateOrderBy().
+                // Otherwise, prefer columns with aliases matching the base column name, e.g.
+                // prefer `t1.ts as ts` over `t1.ts as ts2`.
+                if (Chars.equalsIgnoreCaseNc(queryColumn.getAlias(), firstOrderByColumn)
+                        || Chars.equalsIgnoreCase(queryColumn.getAlias(), timestampName, timestampNameDot + 1, timestampName.length())
+                        || !timestampSet) {
+                    queryMetadata.setTimestampIndex(i);
+                    timestampSet = true;
+                }
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4543]: What timestamp will be set to if the execution does not go into the if block? What if `firstOrderByColumn == null`, why do we alter the old behaviour in that case?

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4543]: > What timestamp will be set to if the execution does not go into the if block?

Same as before this change, `-1`, as that's the default in `GenericRecordMetadata`.

> What if `firstOrderByColumn == null`, why do we alter the old behaviour in that case?

If `firstOrderByColumn` is null, only the `Chars.equalsIgnoreCase(queryColumn.getAlias(), timestampName, timestampNameDot + 1, timestampName.length()) || !timestampSet` conditions will be checked. There is a clarifying comment around this branch - do you find it unclear?

Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4543]: No, not very clear, better to be separate if tbh.

What if this condition `Chars.equalsIgnoreCase(queryColumn.getAlias(), timestampName, timestampNameDot + 1, timestampName.length())`  is also false, but the old condition `index == timestampIndex` is true, why do we change the behaviour in this situation? Or is it impossible?

**Comment by puzpuzpuz** [comment]
> Still reviewing, just wanted to ask to boost the overall test coverage, please.

Covered one branch and removed two never-taken in 7372ad2f9189e52cd19d182bfd7d1511dedb46e9. Everything else seems covered.

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 4]
```diff
@@ -1537,66 +1537,67 @@ private boolean createSelectColumn(
...
-        final LowerCaseCharSequenceObjHashMap<CharSequence> translatingAliasMap = translatingModel.getColumnNameToAliasMap();
-        final int index = translatingAliasMap.keyIndex(columnAst.token);
-        if (index < 0) {
-            // check if the column is a duplicate, i.e. already referenced by the group-by model
-            if (!allowDuplicates && groupByModel.getAliasToColumnMap().contains(columnName)) {
-                throw SqlException.duplicateColumn(columnAst.position, columnName);
+        final CharSequence translatedColumnName = translatingModel.getColumnNameToAliasMap().get(columnAst.token);
+        if (translatedColumnName != null) {
+            // the column is already being referenced by the translating model
+            final CharSequence groupByColumnName = groupByModel.getColumnNameToAliasMap().get(translatedColumnName);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/SqlOptimiser.java:1556]: if `isGroupBy == false`, we shouldn't search `groupByModel`, I don't see why it should be even passed as non-null.

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 5]
```diff
@@ -1537,66 +1537,67 @@ private boolean createSelectColumn(
...
                     baseModel
             );
 
-            final QueryColumn translatedColumn = nextColumn(alias, columnAst.position);
-
             // create column that references inner alias we just created
+            final QueryColumn translatedColumn = nextColumn(innerAlias, columnAst.position);
             innerVirtualModel.addBottomUpColumn(translatedColumn);
-            windowModel.addBottomUpColumn(translatedColumn);
             groupByModel.addBottomUpColumn(translatedColumn);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/SqlOptimiser.java:1596]: If `isGroupBy == false`, why do we use `groupByModel`?

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java (hunk 3 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4543]: > What if this condition `Chars.equalsIgnoreCase(queryColumn.getAlias(), timestampName, timestampNameDot + 1, timestampName.length())` is also false, but the old condition `index == timestampIndex` is true, why do we change the behaviour in this situation? Or is it impossible?

That's possible. Before this change we picked up the last matching selected column, now we pick up the first one. Both approaches are equivalent and the scenario is rare enough. Do you think it's worth keeping the old behavior by making the code slightly more complicated?

**Review by ideoma — APPROVED** [review]

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java (hunk 4 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java:1556]: We're using the model to accumulate the columns, but later on it's ignored. I kept this logic as is to avoid breaking the code that may rely on this.

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java (hunk 5 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java:1596]: We're using the model to accumulate the columns, but later on it's ignored. I kept this logic as is to avoid breaking the code that may rely on this.

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java (hunk 3 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4543]: Could you illustrate it with an example of a query that will have a breaking change?

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4543]: Sure. I've added "breaking change" to the PR title and added an illustration to the description.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 119 / 121 (98.35%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|48|49|97.96%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|71|72|98.61%|

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 6]
```diff
@@ -2987,6 +2992,10 @@ private void moveWhereInsideSubQueries(QueryModel model) throws SqlException {
         }
     }
 
+    private QueryColumn nextColumn(CharSequence alias, CharSequence column, int position) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlOptimiser.java]: unused

File: core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java [hunk 7]
```diff
@@ -7354,34 +7565,32 @@ public void testSampleByWithProjection2() throws Exception {
...
+            final String query = "select " +
+                    "symbol || 'abcd' as symbol" +
+                    ", sum(amount)" +
+                    ", vwap(price, amount)" +
+                    ", cast(dateadd('h', 2, to_timezone(timestamp,'EST')) as double) as ts" +
+                    ", cast(dateadd('h', 2, to_timezone(timestamp,'EST')) as double) + sum(amount) NYTime " +
+                    "from trades\n" +
+                    "sample by 5m";
+            assertQueryNoLeakCheck(
+                    "symbol\tsum\tvwap\tts\tNYTime\n" +
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java]: please use text blocks like everywhere else in the class - consistency + warnings

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 119 / 121 (98.35%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|48|49|97.96%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|71|72|98.61%|

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java (hunk 6 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java]: Removed in caee3245ee686439ce92e89ed8e158793261fe02

File: core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java (hunk 7 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java]: Reformatted in caee3245ee686439ce92e89ed8e158793261fe02

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 120 / 121 (99.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|48|49|97.96%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|72|72|100.00%|
