### PR TITLE
fix(ilp): sanitize table name to avoid FS corruption

### LINKED ISSUE #1595: Multiple thread write error
### Describe the bug

Hello. I used QuestDB 6.1.1 in Springboot. I use one client bean to write data, and the bean is used in 16 threads. When the QuestDb works on CentOS , there is a error 

```
2021-11-17T03:29:22.759826Z E i.q.c.l.t.LineTcpConnectionContext [100] could not process line data [table=gs, msg=could not mmap  [size=12288, offset=0, fd=120, memUsed=3361135068, fileLen=12288], errno=19]
``` 

Then I deploy the QuestDB on Windows 10, version 21H2, I got another error, the log on windows just as the attachment
[stdout-2021-11-19T15-16-53.txt](https://github.com/questdb/questdb/files/7569112/stdout-2021-11-19T15-16-53.txt)
:

On line 231, I find that there is a lot of whitespace at the front of  tablename. 
In addition, the error occurs after my program starts about 40s.

Here is my code:

```
@Autowired
private LineTcpSender sender;

@Override
public void addPoint(HistoryDataDTO hisData) {
    sender.put(getLine(hisData));
}

private CharSequence getLine(HistoryDataDTO hisData) {
    return String.format("%s,tagName=%s,objectName=%s value=%f,quality=\"%s\" %d\n",
            hisData.getTenantName(),
            hisData.getTagName(),
            hisData.getMetricName(),
            Double.parseDouble(hisData.getValue().toString()),
            hisData.getQuality(),
            hisData.getTime() * 1000000);
}
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
Fixes #1595

We do not sanitize table name, which originates from ILP. The following is not disallowed:

```
../../tab,tag=val
```

```
\0\0\0tab,tag=val
```

```
\0\0\0,tag=val
```

etc...

Additionally disallowing the following characters in table names and columns: `\`,`/`,`.` and `\0`

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 59 (98.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|58|59|98.31%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 59 (98.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|58|59|98.31%|

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java [hunk 1]
```diff
@@ -430,9 +416,15 @@ private boolean expectEntityValue(byte endOfEntityByte, long bufHi) {
     private boolean expectTableName(byte endOfEntityByte, long bufHi) {
         tagsComplete = endOfEntityByte == (byte) ' ';
         if (endOfEntityByte == (byte) ',' || tagsComplete) {
-            measurementName.of(entityLo, bufAt - nEscapedChars);
-            entityHandler = entityNameHandler;
-            return true;
+            long hi = sanitizeEnd(entityLo, bufAt - nEscapedChars);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:419]: I'm not sure we have to tolerate \0 at the end of measurement name. 

From another hand ending table name with `.` is allowed in SQL in QuestDB atm:
```
create table "a."  (col int)
select * from "a."
```

and I don't see why we cannot allow ILP to use it in the table name.

`\ a` in ILP is also valid and means same as table `" a"` in SQL

I think we need to strip leading `\0` only and add protection in QuestDB engine to check table names as well as

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java [hunk 2]
```diff
@@ -64,15 +64,51 @@
...
     private long timestamp;
-    private final EntityHandler entityTimestampHandler = this::expectTimestamp;
-    private final EntityHandler entityValueHandler = this::expectEntityValue;
-    private final EntityHandler entityNameHandler = this::expectEntityName;
+    private final EntityHandler entityTimestampHandler = this::expectTimestamp;    private final EntityHandler entityTableHandler = this::expectTableName;
     private int nQuoteCharacters;
     private boolean scape;
     private boolean nextValueCanBeOpenQuote;
-    private boolean hasNonAscii;
+    private boolean hasNonAscii;    private final EntityHandler entityValueHandler = this::expectEntityValue;
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:72]: IntelliJ fails to format this source file, it messes source up every time :(

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java (hunk 1 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:419]: I could be missing something, but we do not tolerate `\0` neither at start nor at end. The `.` is only removed at start, to avoid `../table` shenanigans. At end it is allowed.

```
I'm not sure we have to tolerate \0 at the end of measurement name.
```

If you meant to say here we should allow `\0` at end - it is useless. When creating directory we use zero-terminated strings.

I'm going to remove ` ` from sanitisation though, ILP parser takes care of that already

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java [hunk 3]
```diff
@@ -64,15 +64,51 @@
...
+                case '.':
+                case '/':
+                    p++;
+                    break;
+                default:
+                    break OUT;
+            }
+        }
+        return p;
+    }    private final EntityHandler entityNameHandler = this::expectEntityName;
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java]: IntelliJ really doesn't like this file

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 57 (98.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|56|57|98.25%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 57 (98.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|56|57|98.25%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 57 (98.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|56|57|98.25%|

**Comment by ideoma** [comment]
When I send 
```
0gs/../../asdf,building=ba1aa618-4de4-40be-a4f7-72e341274b91
```

I still get attempted to create table in the wrong folder

E i.q.c.TableUtils cannot open '/questdb-root/db/0gs/../../asdf.lock' to lock [errno=2]
E i.q.c.p.WriterPool could not lock [table=`0gs/../../asdf`, thread=16]

I believe we should reject creating tables with special characters in name like /, \ , \0 not at the start / end but anywhere. We should simply reject those lines as invalid without trying to clean them up.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 57 (98.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|56|57|98.25%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 57 (98.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|56|57|98.25%|

**Comment by bluestreak01** [comment]
ILP ingestion performance degraded due to checks. Not finished

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 51 / 52 (98.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|51|52|98.08%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 51 / 52 (98.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|51|52|98.08%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 55 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|54|55|98.18%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 55 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|54|55|98.18%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 55 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|54|55|98.18%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 55 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|54|55|98.18%|

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java [hunk 4]
```diff
@@ -564,7 +564,7 @@ void createMeasurementEvent(
                         case LineTcpParser.ENTITY_TYPE_INTEGER:
                             Unsafe.getUnsafe().putByte(bufPos, entity.getType());
                             bufPos += Byte.BYTES;
-                            Unsafe.getUnsafe().putLong(bufPos, entity.getIntegerValue());
+                            Unsafe.getUnsafe().putLong(bufPos, entity.getLongValue());
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java:567]: Can you please explain why it should be `getLongValue` here?

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java [hunk 5]
```diff
@@ -219,13 +225,25 @@ public ParseResult parseMeasurement(long bufHi) {
...
                 default:
                     appendByte = true;
                     nextValueCanBeOpenQuote = false;
                     break;
+
+                case '\0':
+                    LOG.info().$("could not parse [byte=\\0]").$();
+                    return getError();
+                case '/':
+                case '.':
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:240]: `.` is quite Innocent without slashes, I don't see why we should restrict it

**Review by ideoma — DISMISSED** [review]
It can go this way if you `getLongValue` is not a typo

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java (hunk 5 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:240]: there is big performance hit differentiating `..` and `.` and `../`. This is compilated by TCP fragmentation, where `.` can be in one buffer and `./` in another. Such case requires penalising second pass over data or significant state machine changes

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java (hunk 4 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java:567]: Because return value was and still is `long` and not Integer. We also had separate field `timestamp` which was used as long and prohibited code reuse

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java (hunk 5 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:240]: I'd think refusing anything with `/` would cover fragmented cases of `./`, `../`

**Comment by bluestreak01** [comment]
not a typo :)

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java (hunk 5 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java:240]: And I don't see problems with `.`, `..` anywhere in table, column name

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 55 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|54|55|98.18%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 55 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|54|55|98.18%|

File: core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java (hunk 5 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java]: agreed, changed

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 53 / 56 (94.64%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|53|56|94.64%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 53 / 56 (94.64%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|53|56|94.64%|
