### PR TITLE
fix(ooo): table writers might steal each other work and handle it incorrectly

### LINKED ISSUE #955: O3 concurrent insert into multiple tables becomes unstable when OS limits are breached
Two threads inserting into two separate tables. Tables must come from the same pool, so they share O3 workers. When OS begins to run out of file descriptors these threads become unstable. There are two symptoms:

- one thread finishes and one hands
- process crashes with segmentation fault

### PR DESCRIPTION
**Pull request by bluestreak01**
Closes #955

### CODE REVIEW

File: core/src/main/java/io/questdb/cairo/O3PurgeDiscoveryJob.java [hunk 1]
```diff
@@ -189,22 +189,20 @@ private static void processDir(
...
-                    configuration.getRoot(),
-                    task.getTableName(),
-                    task.getPartitionBy(),
-                    task.getTimestamp(),
-                    task.getTxnScoreboard()
-            );
-        } finally {
-            subSeq.done(cursor);
-        }
+        final boolean useful = discoverPartitions(
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/O3PurgeDiscoveryJob.java:192]: Why is it better than try finally? You don't want to release sequence in case of exception?

Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/O3PurgeDiscoveryJob.java:192]: This is because exception is never thrown from that code block. Eg there is no code to throw exception. 

Having finally on other hand reduces test coverage. Tools highlight finally block that is never triggered by exception
