### PR TITLE
fix(cairo): fix mmap offset page alignment in o3

### LINKED ISSUE #1521: CairoException [22] could not mmap when running tsbs benchmark
### Describe the bug

Errors in the server logs may be observed when running TSBS. Full log:
```
2021-11-04T15:02:26.828257Z I server-main os scheduled [name=questdb-worker-3]
2021-11-04T15:02:34.211841Z I http-server connected [ip=127.0.0.1, fd=65]
2021-11-04T15:02:34.215315Z I i.q.c.h.p.JsonQueryProcessorState [65] exec [q='SHOW TABLES']
2021-11-04T15:02:34.215446Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=SHOW TABLES]
2021-11-04T15:02:34.216593Z I i.q.c.h.p.JsonQueryProcessorState [65] execute-new [skip: 0, stop: 9223372036854775807]
2021-11-04T15:02:34.217268Z I i.q.c.h.p.JsonQueryProcessorState [65] timings [compiler: 1077349, count: 0, execute: 2042136, q=`SHOW TABLES`]
2021-11-04T15:02:34.217400Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=65, lastRequestBytesSent=322, nCompletedRequests=1, totalBytesSent=0]
2021-11-04T15:02:34.217516Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-3, sql=SHOW TABLES]
2021-11-04T15:02:34.217832Z I tcp-line-server connected [ip=127.0.0.1, fd=66]
2021-11-04T15:02:34.217897Z I tcp-line-server connected [ip=127.0.0.1, fd=67]
2021-11-04T15:02:34.218030Z I tcp-line-server connected [ip=127.0.0.1, fd=68]
2021-11-04T15:02:34.248435Z I i.q.c.l.t.LineTcpMeasurementScheduler creating table [tableName=cpu]
2021-11-04T15:02:34.248851Z I i.q.c.CairoEngine locked [table=`cpu`, thread=13]
2021-11-04T15:02:34.262618Z I i.q.c.p.WriterPool created [table=`cpu`, thread=13]
2021-11-04T15:02:34.262870Z I i.q.c.TableWriter open 'cpu'
2021-11-04T15:02:34.266342Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/questdb/db/cpu]
2021-11-04T15:02:34.266675Z I i.q.c.CairoEngine unlocked [table=`cpu`]
2021-11-04T15:02:34.268993Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned cpu to thread 0
2021-11-04T15:02:34.269059Z I i.q.c.l.t.LineTcpMeasurementScheduler network IO thread using table [workerId=0, tableName=cpu, nNetworkIoWorkers=1]
2021-11-04T15:02:34.269255Z I i.q.c.p.ReaderPool open 'cpu' [at=0:0]
2021-11-04T15:02:34.273520Z I i.q.c.l.t.LineTcpMeasurementScheduler assigned table to writer thread [tableName=cpu, threadId=0]
2021-11-04T15:02:34.273623Z I i.q.c.p.WriterPool >> [table=`cpu`, thread=12]
2021-11-04T15:02:34.274552Z I i.q.c.TableWriter switched partition [path='/tmp/questdb/db/cpu/2016-01-01]
2021-11-04T15:04:04.285182Z I http-server scheduling disconnect [fd=65, reason=12]
2021-11-04T15:04:04.769951Z I http-server disconnected [ip=127.0.0.1, fd=65, src=queue]
2021-11-04T15:04:31.249339Z I i.q.c.TableWriter switched to o3 [table=cpu]
2021-11-04T15:04:31.363014Z I tcp-line-server scheduling disconnect [fd=68, reason=0]
2021-11-04T15:04:31.363172Z I tcp-line-server disconnected [ip=127.0.0.1, fd=68, src=queue]
2021-11-04T15:04:31.363592Z I tcp-line-server scheduling disconnect [fd=66, reason=0]
2021-11-04T15:04:31.363637Z I tcp-line-server disconnected [ip=127.0.0.1, fd=66, src=queue]
2021-11-04T15:04:31.363729Z I tcp-line-server scheduling disconnect [fd=67, reason=0]
2021-11-04T15:04:31.363778Z I tcp-line-server disconnected [ip=127.0.0.1, fd=67, src=queue]
2021-11-04T15:04:56.829976Z E i.q.c.l.t.LineTcpMeasurementScheduler could not commit [table=cpu]
2021-11-04T15:04:56.829987Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=207, memUsed=1122638677, fileLen=150994944]
]
2021-11-04T15:04:56.830036Z I i.q.c.TableWriter tx rollback [name=cpu]
2021-11-04T15:04:56.836386Z I i.q.c.TableWriter purging non attached partitions [path=/tmp/questdb/db/cpu]
2021-11-04T15:04:56.837214Z I i.q.c.TableWriter switched partition [path='/tmp/questdb/db/cpu/2016-01-01]
2021-11-04T15:04:56.837429Z I i.q.c.TableWriter tx rollback complete [name=cpu]
2021-11-04T15:04:56.837449Z I i.q.c.p.WriterPool << [table=`cpu`, thread=12]
2021-11-04T15:04:56.839811Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=66, memUsed=787094357, fileLen=150994944]
]
2021-11-04T15:04:56.841132Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=67, memUsed=803871573, fileLen=150994944]
]
2021-11-04T15:04:56.842479Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=68, memUsed=820648789, fileLen=150994944]
]
2021-11-04T15:04:56.843695Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=207, memUsed=837426005, fileLen=150994944]
]
2021-11-04T15:04:56.844897Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=208, memUsed=854203221, fileLen=150994944]
]
2021-11-04T15:04:56.846186Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=209, memUsed=870980437, fileLen=150994944]
]
2021-11-04T15:04:56.847445Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=210, memUsed=887757653, fileLen=150994944]
]
2021-11-04T15:04:56.848700Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=211, memUsed=904534869, fileLen=150994944]
]
2021-11-04T15:04:56.849894Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=4886616, fd=212, memUsed=921312085, fileLen=150994944]
]
2021-11-04T15:04:56.851132Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=213, memUsed=938089301, fileLen=285212672]
]
2021-11-04T15:04:56.852485Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=214, memUsed=954866517, fileLen=285212672]
]
2021-11-04T15:04:56.853742Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=215, memUsed=971643733, fileLen=285212672]
]
2021-11-04T15:04:56.854944Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=216, memUsed=988420949, fileLen=285212672]
]
2021-11-04T15:04:56.856139Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=217, memUsed=1005198165, fileLen=285212672]
]
2021-11-04T15:04:56.857335Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=218, memUsed=1021975381, fileLen=285212672]
]
2021-11-04T15:04:56.858545Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=219, memUsed=1038752597, fileLen=285212672]
]
2021-11-04T15:04:56.859892Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=220, memUsed=1055529813, fileLen=285212672]
]
2021-11-04T15:04:56.861140Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=221, memUsed=1072307029, fileLen=285212672]
]
2021-11-04T15:04:56.862358Z E server-main unhandled error [job=io.questdb.cairo.O3CallbackJob@34079b7e, ex=
io.questdb.cairo.CairoException: [22] could not mmap  [size=9773232, fd=222, memUsed=1089084245, fileLen=285212672]
]
2021-11-04T15:05:01.253139Z I i.q.c.l.t.LineTcpMeasurementScheduler network IO thread released table [workerId=0, tableName=cpu, nNetworkIoWorkers=0]
2021-11-04T15:05:01.253212Z I i.q.c.l.t.LineTcpMeasurementScheduler active table going idle [tableName=cpu]
2021-11-04T15:05:01.253797Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2021-11-04T15:04:31.362000Z[tableName=cpu]
```

### To reproduce

1. Checkout the following TSBS version: https://github.com/puzpuzpuz/tsbs/tree/add-questdb-makefile-targets
2. Run `make`
3. Generate benchmark data:
```bash
$ cd bin
$ ./tsbs_generate_data --use-case="cpu-only" --seed=123 --scale=4000 --timestamp-start="2016-01-01T00:00:00Z" --timestamp-end="2016-01-02T00:00:00Z" --log-interval="10s" --format="influx" > /tmp/data
```
4. Start latest `master` snapshot of QuestDB (e.g. c5d9eb8407a5ee8c4fb045bc4f789ac6897c5de2)
5. Start the benchmark worker:
```bash
$ ./tsbs_load_questdb --file /tmp/data --workers 3
```
6. Wait for a while once the benchmark ends (~30-60 seconds).

### Expected Behavior

No error messages in the logs.

### Environment

```markdown
- **QuestDB version**: latest `master`, OpenJDK v11.0.11
- **OS**: Ubuntu 20.04, 64-bit, 5.10.0-1050-oem kernel
- **Browser**: N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #1521

Linux (and probably other POSIX-compliant systems) requires mmap's offset to be page size aligned. Under certain conditions O3 writes led to unmapped pages being open with unaligned offset value.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacade.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacade.java|1|1|100.00%|

File: core/src/main/java/io/questdb/std/FilesFacade.java [hunk 1]
```diff
@@ -64,6 +64,10 @@
 
     long getPageSize();
 
+    default long alignedOffset(long offset) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/std/FilesFacade.java:67]: We have `Files.ceilPageSize()` method, this looks like should be `Files.floorPageSize()`

File: core/src/main/java/io/questdb/cairo/TableUtils.java [hunk 2]
```diff
@@ -470,12 +470,18 @@ public static long mapRO(FilesFacade ff, long fd, long size, int memoryTag) {
         return mapRO(ff, fd, size, 0, memoryTag);
     }
 
+    /**
+     * Maps a file in read-only mode.
+     *
+     * Important note. Linux requires the offset to be page aligned.
+     */
     public static long mapRO(FilesFacade ff, long fd, long size, long offset, int memoryTag) {
         final long address = ff.mmap(fd, size, offset, Files.MAP_RO, memoryTag);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/TableUtils.java:479]: We can put assert here so that all platforms will check that offset is page aligned

File: core/src/main/java/io/questdb/cairo/TableUtils.java [hunk 3]
```diff
@@ -488,6 +494,11 @@ public static long mapRW(FilesFacade ff, long fd, long size, int memoryTag) {
...
     }
 
+    /**
+     * Maps a file in read-write mode.
+     *
+     * Important note. Linux requires the offset to be page aligned.
+     */
     public static long mapRW(FilesFacade ff, long fd, long size, long offset, int memoryTag) {
         allocateDiskSpace(ff, fd, size + offset);
         long addr = ff.mmap(fd, size, offset, Files.MAP_RW, memoryTag);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/TableUtils.java:504]: Same assert can go here too

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacade.java|1|1|100.00%|

File: core/src/main/java/io/questdb/cairo/TableWriter.java [hunk 4]
```diff
@@ -3152,9 +3157,12 @@ private void o3MoveUncommitted0(
                 long sourceAddress = srcDataMem.addressOf(srcFixOffset);
                 Vect.memcpy(appendAddress, sourceAddress, extendedSize);
             } else {
-                long sourceAddress = mapRO(ff, srcDataMem.getFd(), extendedSize, srcFixOffset, MemoryTag.MMAP_TABLE_WRITER);
-                Vect.memcpy(appendAddress, sourceAddress, extendedSize);
-                ff.munmap(sourceAddress, extendedSize, MemoryTag.MMAP_TABLE_WRITER);
+                // Linux requires the mmap offset to be page aligned
+                long alignedOffset = ff.alignedOffset(srcFixOffset);
+                long alignedExtraSize = srcFixOffset - alignedOffset;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/TableWriter.java:3162]: same name as first time would be better `alignedExtraLen`

File: core/src/main/java/io/questdb/std/FilesFacade.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/std/FilesFacade.java]: Moved and renamed in 9678f2dec1966a917f63dd78de06e01c1d2d0740

File: core/src/main/java/io/questdb/cairo/TableUtils.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/TableUtils.java:480]: Added assert in 9678f2dec1966a917f63dd78de06e01c1d2d0740

File: core/src/main/java/io/questdb/cairo/TableUtils.java (hunk 3 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/TableUtils.java:506]: Added assert in 9678f2dec1966a917f63dd78de06e01c1d2d0740

File: core/src/main/java/io/questdb/cairo/TableWriter.java (hunk 4 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/TableWriter.java]: Renamed in 9678f2dec1966a917f63dd78de06e01c1d2d0740

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the code review!
