### PR TITLE
fix(ilp): fix incorrect storage of non-ascii characters that can lead to incorrect SQL results

### LINKED ISSUE #4872: SELECT DISTINCT giving incorrect results for VARCHAR
### To reproduce

Take the attached CSV. Create this table:

```sql
CREATE TABLE 'betfairRunners' (
  venue SYMBOL CAPACITY 128 CACHE INDEX CAPACITY 256,
  distance INT,
  id INT,
  trap BYTE,
  runner VARCHAR,
  grade SYMBOL CAPACITY 128 CACHE INDEX CAPACITY 256,
  age BYTE,
  wght FLOAT,
  fin BYTE,
  bends SYMBOL CAPACITY 2048 CACHE INDEX CAPACITY 256,
  gng INT,
  split FLOAT,
  wintm FLOAT,
  caltm FLOAT,
  remarks SYMBOL CAPACITY 2048 CACHE INDEX CAPACITY 256,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY MONTH WAL
DEDUP UPSERT KEYS(timestamp, id);
```

Run this script:

```python
import pandas as pd
from questdb.ingress import Sender

df = pd.read_csv("ballymac_fifra.csv", parse_dates=["timestamp"])

sender = Sender.from_conf("http::addr=localhost:9000;")
sender.establish()

sender.dataframe(df, table_name="betfairRunners", at='timestamp')
sender.flush()
sender.close()
```

Then run a distinct query:

```sql
SELECT DISTINCT runner FROM betfairRunners
```

image

If you convert to string instead, it works correctly:

```sql
SELECT DISTINCT (runner::string)::varchar as runner FROM betfairRunners
```

image

Count distinct is also broken:

```sql
select count_distinct(runner) from betfairRunners
```

image

All the varchars are the same length (14). There are 151 entries.

Checking in textedit, it finds 151 matches:

image

Issue seems to occur here: https://github.com/questdb/questdb/blob/fba356e67ae8b3ce77bfff2b68a1a83c86da63ad/core/src/main/java/io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java#L151-L161

Whatever match it is performing hits true twice.

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

MacOS

### File System, in case of Docker specify Host File System:

APFS

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

[ballymac_fifra.csv](https://github.com/user-attachments/files/16627680/ballymac_fifra.csv)

### LINKED ISSUE #4873: Flaky ServerMainBackupDatabaseTest.testServerMainBackupDatabase
### To reproduce

Reproducible on Linux with both ext4 and ZFS. Random seeds: 1292636664526599L, 1723798038419L

```
java.lang.AssertionError: expected min rows: 74839, actual: 65263

	at junit@4.13.2/org.junit.Assert.fail(Assert.java:89)
	at junit@4.13.2/org.junit.Assert.assertTrue(Assert.java:42)
	at io.questdb.test/io.questdb.test.ServerMainBackupDatabaseTest.lambda$testServerMainBackupDatabase$1(ServerMainBackupDatabaseTest.java:198)
	at io.questdb.test/io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:685)
	at io.questdb.test/io.questdb.test.ServerMainBackupDatabaseTest.testServerMainBackupDatabase(ServerMainBackupDatabaseTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at junit@4.13.2/org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at junit@4.13.2/org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at junit@4.13.2/org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at junit@4.13.2/org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at junit@4.13.2/org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at junit@4.13.2/org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at junit@4.13.2/org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at junit@4.13.2/org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4, zfs

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
fixes #4872
fixes #4873 - removed the flaky test. It exercises "BACKUP DATABASE", which is no longer supported method of backing up QuestDB

EDIT (NW): 

Users with existing `VARCHAR` columns who encounter any issues with distinct or join queries should run the following SQL to correct the issue:

```sql
UPDATE table_name set varchar_column = (varchar_column::string)::varchar
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 26 (88.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineWalAppender.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
failed flapping test https://github.com/questdb/questdb/issues/4823

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 26 (88.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineWalAppender.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 33 / 36 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineWalAppender.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|

File: core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java [hunk 1]
```diff
@@ -1,374 +0,0 @@
...
-import java.util.concurrent.atomic.AtomicBoolean;
-import java.util.concurrent.atomic.AtomicLong;
-import java.util.concurrent.atomic.AtomicReference;
-
-import static io.questdb.test.griffin.TableBackupTest.executeCreateTableStmt;
-import static io.questdb.test.griffin.TableBackupTest.executeInsertGeneratorStmt;
-import static io.questdb.test.tools.TestUtils.assertMemoryLeak;
-import static io.questdb.test.tools.TestUtils.createSqlExecutionCtx;
-
-public class ServerMainBackupDatabaseTest extends AbstractBootstrapTest {
```
Comment (puzpuzpuz) [inline core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java:69]: BACKUP DATABASE is the only way to do a backup on Windows as snapshots/checkpoint aren't supported on this OS. So, we should probably keep it and fix the test. WDYT?

Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java:69]: The backup is consistently confusing subject for our users. We decided a while ago to remove all the branches and only document snapshot (checkpoint - https://github.com/questdb/questdb/pull/4821).

Windows is not a serious production system either, the way to backup database is to stop the instance and backup.

We still have `BACKUP DATABASE`, i just don't think it is worthwhile exercise to make sure it works on ZFS (linux) :(

Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java:69]: The test is flaky on ext4, not only zfs. If we remove the test, backup may get broken unnoticeably. To me, as long as we keep the feature around, we should fix the test instead of removing it.

Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java:69]: the issues is - the backup is probably broken already. I don't want to spend time and effort fixing it though and also waste time re-running CI. "backup" SQL has already been removed from the documentation.

Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java:69]: Got it, let's remove the test then.

> I would remove "backup" SQL entirely, but it is just a bigger change for this PR :)

Sounds like a great idea for another PR.

File: core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java [hunk 2]
```diff
@@ -66,4 +73,69 @@ public void testDisconnectOnErrorWithWAL() throws Exception {
...
+
+                    drainWalQueue(engine);
+
+                    CompiledQuery result = sqlCompiler.compile("select distinct runner from betfairRunners", sqlExecutionContext);
+
+                    try (
+                            RecordCursorFactory factory = result.getRecordCursorFactory();
+                            RecordCursor cursor = factory.getCursor(sqlExecutionContext)
+                    ) {
+                        cursor.hasNext();
```
Comment (puzpuzpuz) [inline core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java:123]: nit:
```suggestion
                        Assert.assertTrue(cursor.hasNext());
```

**Review by puzpuzpuz — DISMISSED** [review]

File: core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java (hunk 2 above)
Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java]: this was actually an issue with test, fixed in https://github.com/questdb/questdb/pull/4876/commits/d2f1d91c1479ac80e3daf436b8124b067899e3df

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 33 / 36 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineWalAppender.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|

File: core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java [hunk 3]
```diff
@@ -44,6 +51,81 @@ public void setUp() {
...
+                            sender.table("betfairRunners").symbol("remarks", "(R8) LdRnIn військові").
+                                    stringColumn("runner", "BallyMac Fifra")
+                                    .longColumn("id", 548738)
+                                    .longColumn("age", 58)
+                                    .at(TimestampFormatUtils.parseTimestamp("2024-06-17T00:00:00Z"), ChronoUnit.MICROS);
+                            sender.flush();
+                        }
+                    }
+
+                    // server main already runs Apply2Wal job in the background. We have to wait for the table to catchup
```
Comment (puzpuzpuz) [inline core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java:94]: nit: we have `assertEventually` for this purpose.

**Review by puzpuzpuz — APPROVED** [review]

File: core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java (hunk 3 above)
Comment (ideoma) [reply core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java:94]: Let's do it in another PR
