### PR TITLE
test(core): fix flaky testRenameTableSameMeta

### LINKED ISSUE #3495: Flaky LineTcpReceiverTest.testRenameTableSameMeta
### Describe the bug

```
2023-06-16T09:49:46.552139Z I i.q.c.m.EngineMigration upgrading database [version=427]
2023-06-16T09:49:46.552196Z I i.q.c.m.EngineMigration upgraded tables to 427
2023-06-16T09:49:46.552365Z I i.q.c.TableNameRegistryFileStore reloading tables file [path=/tmp/junit13246187388419942853/dbRoot/tables.d.0]
2023-06-16T09:49:46.557038Z I i.q.t.AbstractTest Starting test LineTcpReceiverTest#testRenameTableSameMeta[WITH_WAL]
2023-06-16T09:49:46.557438Z I i.q.c.TableNameRegistryFileStore reloading tables file [path=/tmp/junit13246187388419942853/dbRoot/tables.d.0]
2023-06-16T09:49:46.557625Z A IODispatcher listening on 0.0.0.0:9002 [fd=19 backlog=64]
2023-06-16T09:49:46.557889Z I i.q.t.c.l.t.AbstractLineTcpReceiverTest worker pool started [pool=testing]
2023-06-16T09:49:46.558895Z I i.q.t.c.l.t.AbstractLineTcpReceiverTest os scheduled worker started [name=questdb-testing-26]
2023-06-16T09:49:46.558983Z I IODispatcher connected [ip=127.0.0.1, fd=21]
2023-06-16T09:49:46.559230Z I i.q.c.CairoEngine locked [table=`weather~1`, thread=90]
2023-06-16T09:49:46.570788Z I i.q.c.p.WriterPool created [table=`weather~1`, thread=90]
2023-06-16T09:49:46.570852Z I i.q.c.TableWriter open 'weather'
2023-06-16T09:49:46.571519Z I i.q.c.CairoEngine unlocked [table=`weather`]
2023-06-16T09:49:46.572062Z I i.q.c.l.t.LineTcpMeasurementScheduler created table [tableName=weather]
2023-06-16T09:49:46.572082Z I i.q.c.p.WalWriterPool open 'weather~1' [at=0:0]
2023-06-16T09:49:46.572100Z I i.q.c.w.WalWriter open 'weather~1'
2023-06-16T09:49:46.572451Z I i.q.c.w.WalWriter opened WAL segment [path='/tmp/junit13246187388419942853/dbRoot/weather~1/wal1/0/_event.i']
2023-06-16T09:49:46.572593Z I i.q.c.p.MetadataPool open 'weather~1' [at=0:0]
2023-06-16T09:49:46.576454Z I i.q.c.p.WalWriterPool open 'weather~1' [at=0:1]
2023-06-16T09:49:46.576476Z I i.q.c.w.WalWriter open 'weather~1'
2023-06-16T09:49:46.576848Z I i.q.c.w.WalWriter opened WAL segment [path='/tmp/junit13246187388419942853/dbRoot/weather~1/wal2/0/_event.i']
2023-06-16T09:49:46.578763Z I i.q.c.CairoEngine renamed table [from='weather', to='meteorology', wal=2', seqTxn=2]
2023-06-16T09:49:46.578782Z I i.q.t.c.l.t.LineTcpReceiverTest === released WAL writer === weather~1:meteorology
2023-06-16T09:49:46.580174Z I i.q.c.w.WalWriter opened WAL segment [path='/tmp/junit13246187388419942853/dbRoot/weather~1/wal1/1/_event.i']
2023-06-16T09:49:46.580696Z I i.q.c.l.t.TableUpdateDetails closing table writer [tableName=weather]
2023-06-16T09:49:46.580702Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=weather]
2023-06-16T09:49:46.580719Z I i.q.t.c.l.t.LineTcpReceiverTest === released WAL writer === weather~1:meteorology
2023-06-16T09:49:46.580839Z I i.q.c.CairoEngine locked [table=`weather~2`, thread=90]
2023-06-16T09:49:46.595755Z I i.q.c.p.WriterPool created [table=`weather~2`, thread=90]
2023-06-16T09:49:46.595808Z I i.q.c.TableWriter open 'weather'
2023-06-16T09:49:46.596482Z I i.q.c.CairoEngine unlocked [table=`weather`]
2023-06-16T09:49:46.596760Z I i.q.c.l.t.LineTcpMeasurementScheduler created table [tableName=weather]
2023-06-16T09:49:46.596781Z I i.q.c.p.WalWriterPool open 'weather~2' [at=0:0]
2023-06-16T09:49:46.596800Z I i.q.c.w.WalWriter open 'weather~2'
2023-06-16T09:49:46.597129Z I i.q.c.w.WalWriter opened WAL segment [path='/tmp/junit13246187388419942853/dbRoot/weather~2/wal1/0/_event.i']
2023-06-16T09:49:46.597270Z I i.q.c.p.MetadataPool open 'weather~2' [at=0:0]
2023-06-16T09:49:46.598387Z I i.q.c.w.WalWriter opened WAL segment [path='/tmp/junit13246187388419942853/dbRoot/weather~2/wal1/1/_event.i']
2023-06-16T09:49:46.598851Z I i.q.c.w.WalWriter opened WAL segment [path='/tmp/junit13246187388419942853/dbRoot/weather~1/wal1/2/_event.i']
2023-06-16T09:49:46.598962Z I IODispatcher scheduling disconnect [fd=21, reason=0]
2023-06-16T09:49:46.598968Z I IODispatcher disconnected [ip=127.0.0.1, fd=21, src=queue]
2023-06-16T09:49:46.599026Z I i.q.c.l.t.TableUpdateDetails closing table writer [tableName=meteorology]
2023-06-16T09:49:46.599030Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=meteorology]
2023-06-16T09:49:46.613185Z I i.q.t.c.l.t.LineTcpReceiverTest === released WAL writer === weather~1:meteorology
2023-06-16T09:49:46.615311Z I i.q.c.p.WriterPool >> [table=`weather~1`, thread=89]
2023-06-16T09:49:46.615619Z I i.q.c.TableWriter processing WAL [path=/tmp/junit13246187388419942853/dbRoot/weather~1/wal1/0, roLo=0, roHi=2, seqTxn=1, tsMin=2016-06-13T17:43:50.100400Z, tsMax=2016-06-13T17:43:50.100500Z, commitToTimestamp=294247-01-10T04:00:54.775807Z]
2023-06-16T09:49:46.615802Z I i.q.c.TableWriter switched partition [path='/tmp/junit13246187388419942853/dbRoot/weather~1/2016-06-13']
2023-06-16T09:49:46.616133Z I i.q.c.TableWriter removed [path=/tmp/junit13246187388419942853/dbRoot/weather~1/2016-06-13]
2023-06-16T09:49:46.616154Z I i.q.c.TableWriter o3 partition task [table=meteorology, partitionIsReadOnly=false, srcOooBatchRowSize=2, srcOooLo=0, srcOooHi=1, srcOooMax=2, o3RowCount=2, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.100400Z, o3Timestamp=2016-06-13T17:43:50.100400Z, o3TimestampMax=2016-06-13T17:43:50.100500Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=-1, partitionSize=2, maxTimestamp=, last=false, append=false, pCount=1, flattenTimestamp=false, memUsed=19150159]
2023-06-16T09:49:46.616558Z I i.q.c.TableWriter switched partition [path='/tmp/junit13246187388419942853/dbRoot/weather~1/2016-06-13']
2023-06-16T09:49:46.616906Z I i.q.c.TableWriter processing WAL [path=/tmp/junit13246187388419942853/dbRoot/weather~1/wal1/1, roLo=0, roHi=2, seqTxn=3, tsMin=2016-06-13T17:43:50.100600Z, tsMax=2016-06-13T17:43:50.100700Z, commitToTimestamp=2016-06-13T17:43:50.101000Z]
2023-06-16T09:49:46.617004Z I i.q.c.TableWriter o3 partition task [table=meteorology, partitionIsReadOnly=false, srcOooBatchRowSize=2, srcOooLo=0, srcOooHi=1, srcOooMax=2, o3RowCount=2, o3LagRowCount=0, srcDataMax=2, o3TimestampMin=2016-06-13T17:43:50.100600Z, o3Timestamp=2016-06-13T17:43:50.100600Z, o3TimestampMax=2016-06-13T17:43:50.100700Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=4, maxTimestamp=2016-06-13T17:43:50.100500Z, last=true, append=true, pCount=1, flattenTimestamp=false, memUsed=31766157]
2023-06-16T09:49:46.617183Z I i.q.c.TableWriter processing WAL [path=/tmp/junit13246187388419942853/dbRoot/weather~1/wal1/2, roLo=0, roHi=1, seqTxn=4, tsMin=2016-06-13T17:43:50.101000Z, tsMax=2016-06-13T17:43:50.101000Z, commitToTimestamp=294247-01-10T04:00:54.775807Z]
2023-06-16T09:49:46.617254Z I i.q.c.TableWriter o3 partition task [table=meteorology, partitionIsReadOnly=false, srcOooBatchRowSize=1, srcOooLo=0, srcOooHi=0, srcOooMax=1, o3RowCount=1, o3LagRowCount=0, srcDataMax=4, o3TimestampMin=2016-06-13T17:43:50.101000Z, o3Timestamp=2016-06-13T17:43:50.101000Z, o3TimestampMax=2016-06-13T17:43:50.101000Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=0, partitionSize=5, maxTimestamp=2016-06-13T17:43:50.100700Z, last=true, append=true, pCount=1, flattenTimestamp=false, memUsed=31766113]
2023-06-16T09:49:46.617367Z I i.q.c.w.ApplyWal2TableJob job finished [table=weather~1, seqTxn=4, transactions=3, rows=5, time=1ms, rate=3071rows/s, physicalWrittenRowsMultiplier=1.0]
2023-06-16T09:49:46.617398Z I i.q.c.p.WriterPool << [table=`weather~1`, thread=89]
2023-06-16T09:49:46.617426Z I i.q.c.p.WriterPool >> [table=`weather~2`, thread=89]
2023-06-16T09:49:46.617530Z I i.q.c.TableWriter processing WAL [path=/tmp/junit13246187388419942853/dbRoot/weather~2/wal1/0, roLo=0, roHi=2, seqTxn=1, tsMin=2016-06-13T17:43:50.100800Z, tsMax=2016-06-13T17:43:50.100900Z, commitToTimestamp=294247-01-10T04:00:54.775807Z]
2023-06-16T09:49:46.617619Z I i.q.c.TableWriter switched partition [path='/tmp/junit13246187388419942853/dbRoot/weather~2/2016-06-13']
2023-06-16T09:49:46.617826Z I i.q.c.TableWriter removed [path=/tmp/junit13246187388419942853/dbRoot/weather~2/2016-06-13]
2023-06-16T09:49:46.617838Z I i.q.c.TableWriter o3 partition task [table=weather, partitionIsReadOnly=false, srcOooBatchRowSize=2, srcOooLo=0, srcOooHi=1, srcOooMax=2, o3RowCount=2, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2016-06-13T17:43:50.100800Z, o3Timestamp=2016-06-13T17:43:50.100800Z, o3TimestampMax=2016-06-13T17:43:50.100900Z, partitionTimestamp=2016-06-13T00:00:00.000000Z, partitionIndex=-1, partitionSize=2, maxTimestamp=, last=false, append=false, pCount=1, flattenTimestamp=false, memUsed=31766011]
2023-06-16T09:49:46.618094Z I i.q.c.TableWriter switched partition [path='/tmp/junit13246187388419942853/dbRoot/weather~2/2016-06-13']
2023-06-16T09:49:46.618219Z I i.q.c.w.ApplyWal2TableJob job finished [table=weather~2, seqTxn=1, transactions=1, rows=2, time=0ms, rate=2828rows/s, physicalWrittenRowsMultiplier=1.0]
2023-06-16T09:49:46.618242Z I i.q.c.p.WriterPool << [table=`weather~2`, thread=89]
2023-06-16T09:49:46.618423Z I i.q.c.p.ReaderPool open 'weather~1' [at=0:0]
2023-06-16T09:49:46.618655Z I i.q.c.TableReader open partition /tmp/junit13246187388419942853/dbRoot/weather~1/2016-06-13 [rowCount=5, partitionNameTxn=-1, transientRowCount=5, partitionIndex=0, partitionCount=1]
2023-06-16T09:49:46.618813Z I i.q.c.p.ReaderPool open 'weather~2' [at=0:0]
2023-06-16T09:49:46.618988Z I i.q.c.TableReader open partition /tmp/junit13246187388419942853/dbRoot/weather~2/2016-06-13 [rowCount=2, partitionNameTxn=-1, transientRowCount=2, partitionIndex=0, partitionCount=1]
2023-06-16T09:49:46.619191Z E i.q.t.c.l.t.AbstractLineTcpReceiverTest Stopping ILP worker pool because of an error
java.lang.AssertionError: expected:<location	temperature	timestamp
west5	50.0	2016-06-13T17:43:50.100800Z
east6	60.0	2016-06-13T17:43:50.100900Z
south7	70.0	2016-06-13T17:43:50.101000Z
> but was:<location	temperature	timestamp
west5	50.0	2016-06-13T17:43:50.100800Z
east6	60.0	2016-06-13T17:43:50.100900Z
>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:351)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:334)
	at io.questdb.test.tools.TestUtils.assertCursor(TestUtils.java:128)
	at io.questdb.test.AbstractCairoTest.assertCursor(AbstractCairoTest.java:551)
	at io.questdb.test.AbstractCairoTest.assertCursorTwoPass(AbstractCairoTest.java:555)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.assertTable(AbstractLineTcpReceiverTest.java:253)
	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.lambda$testRenameTableSameMeta$27(LineTcpReceiverTest.java:780)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$2(AbstractLineTcpReceiverTest.java:299)
	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$4(AbstractCairoTest.java:285)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:540)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:282)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:291)
	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.testRenameTableSameMeta(LineTcpReceiverTest.java:753)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:833)

2023-06-16T09:49:46.619452Z I i.q.c.l.t.TableUpdateDetails closing table writer [tableName=weather]
2023-06-16T09:49:46.619457Z I i.q.c.l.t.TableUpdateDetails closing table parsers [tableName=weather]
2023-06-16T09:49:46.619806Z I i.q.t.c.l.t.LineTcpReceiverTest === released WAL writer === weather~2:weather
2023-06-16T09:49:46.619876Z I i.q.t.c.l.t.AbstractLineTcpReceiverTest cleaned worker [name=testing, worker=0, total=1]
2023-06-16T09:49:46.619885Z I i.q.t.c.l.t.AbstractLineTcpReceiverTest os scheduled worker stopped [name=questdb-testing-26]
2023-06-16T09:49:46.620348Z I i.q.c.l.t.LineTcpWriterJob line protocol writer closing [threadId=0]
2023-06-16T09:49:46.620409Z I IODispatcher closed
2023-06-16T09:49:46.620413Z E i.q.t.c.l.t.AbstractLineTcpReceiverTest Stopping ILP receiver because of an error
java.lang.AssertionError: expected:<location	temperature	timestamp
west5	50.0	2016-06-13T17:43:50.100800Z
east6	60.0	2016-06-13T17:43:50.100900Z
south7	70.0	2016-06-13T17:43:50.101000Z
> but was:<location	temperature	timestamp
west5	50.0	2016-06-13T17:43:50.100800Z
east6	60.0	2016-06-13T17:43:50.100900Z
>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:351)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:334)
	at io.questdb.test.tools.TestUtils.assertCursor(TestUtils.java:128)
	at io.questdb.test.AbstractCairoTest.assertCursor(AbstractCairoTest.java:551)
	at io.questdb.test.AbstractCairoTest.assertCursorTwoPass(AbstractCairoTest.java:555)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.assertTable(AbstractLineTcpReceiverTest.java:253)
	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.lambda$testRenameTableSameMeta$27(LineTcpReceiverTest.java:780)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$2(AbstractLineTcpReceiverTest.java:299)
	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$4(AbstractCairoTest.java:285)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:540)
	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:282)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:291)
	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.testRenameTableSameMeta(LineTcpReceiverTest.java:753)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:833)

2023-06-16T09:49:46.621035Z I i.q.c.p.ReaderPool closed 'weather~2' [at=0:0, reason=POOL_CLOSED]
2023-06-16T09:49:46.621091Z I i.q.c.p.ReaderPool closed 'weather~1' [at=0:0, reason=POOL_CLOSED]
2023-06-16T09:49:46.621560Z I i.q.c.TableWriter closed 'weather'
2023-06-16T09:49:46.621565Z I i.q.c.p.WriterPool closed [table=`weather~2`, reason=POOL_CLOSED, by=89]
2023-06-16T09:49:46.621756Z I i.q.c.TableWriter closed 'meteorology'
2023-06-16T09:49:46.621759Z I i.q.c.p.WriterPool closed [table=`weather~1`, reason=POOL_CLOSED, by=89]
2023-06-16T09:49:46.621808Z I i.q.c.w.s.TableSequencerAPI releasing idle table sequencer [tableDir=weather~2]
2023-06-16T09:49:46.621834Z I i.q.c.w.s.TableSequencerAPI releasing idle table sequencer [tableDir=weather~1]
2023-06-16T09:49:46.621841Z I i.q.c.p.MetadataPool closed 'weather~2' [at=0:0, reason=POOL_CLOSED]
2023-06-16T09:49:46.621845Z I i.q.c.p.MetadataPool closed 'weather~1' [at=0:0, reason=POOL_CLOSED]
2023-06-16T09:49:46.621931Z I i.q.c.w.WalWriter closed 'weather'
2023-06-16T09:49:46.621934Z I i.q.c.p.WalWriterPool closed 'weather~2' [at=0:0, reason=POOL_CLOSED]
2023-06-16T09:49:46.622005Z I i.q.c.w.WalWriter closed 'meteorology'
2023-06-16T09:49:46.622006Z I i.q.c.p.WalWriterPool closed 'weather~1' [at=0:0, reason=POOL_CLOSED]
2023-06-16T09:49:46.622054Z I i.q.c.w.WalWriter closed 'meteorology'
2023-06-16T09:49:46.622056Z I i.q.c.p.WalWriterPool closed 'weather~1' [at=0:1, reason=POOL_CLOSED]
2023-06-16T09:49:46.622104Z I i.q.t.AbstractCairoTest Tearing down test LineTcpReceiverTest#testRenameTableSameMeta[WITH_WAL]
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ideoma**
fixes #3495

### CODE REVIEW

File: core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverTest.java [hunk 1]
```diff
@@ -745,6 +746,7 @@ public int openRW(LPSZ name, long opts) {
                                 --count == 0
                 ) {
                     renameTable(weather, meteorology);
+                    Os.sleep(100);
```
Comment (amunra) [inline core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverTest.java:749]: Sleeps in tests are usually a hack. What is this actually waiting for?

Comment (ideoma) [reply core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverTest.java]: debug debris, removed

**Review by amunra — APPROVED** [review]
Looking good!
