### PR TITLE
fix(cutlass): adjusts column order during csv import

### LINKED ISSUE #1758: Bulk CSV import ignores column header
### Describe the bug

I am trying to stream data in via bulk csv import, since my data comes in big chunks.  The issue is my data will come in with a timing column, and a few data columns a/b/c, and the data columns can come in random order.
So with two files as below:
table 1

| timing | a   | b   | c   |
| ------ | --- | --- | --- |
| time1  | 1   | 0   | 0   |
| time2  | 1   | 0   | 0   |
| time3  | 1   | 0   | 0   |

table 2

| timing | c   | b   | a   |
| ------ | --- | --- | --- |
| time4  | 1   | 0   | 0   |
| time5  | 1   | 0   | 0   |
| time6  | 1   | 0   | 0   |

i see the following in questdb

| timing | a   | b   | c   |
| ------ | --- | --- | --- |
| time1  | 1   | 0   | 0   |
| time2  | 1   | 0   | 0   |
| time3  | 1   | 0   | 0   |
| time4  | 1   | 0   | 0   |
| time5  | 1   | 0   | 0   |
| time6  | 1   | 0   | 0   |

it appears to be ignoring column header, even playing with params doesnt seem to correct this issue.  It correctly sorts the time, so that if i send the latter portion, it puts it after the earlier data in questdb.  Just the columns are incorrect.

I am using the requests.post.  Applying and using params timestamp, overwrite, forceHeader, partitionby.

requests.post response says it correctly imported and no errors reported.  The odd thing is, it knows its sending C | B | A in that order, as it shows it in the response out of order.

it is on an air gapped system, posting code by hand.

### To reproduce

_No response_

### Expected Behavior

| timing | a   | b   | c   |
| ------ | --- | --- | --- |
| time1  | 1   | 0   | 0   |
| time2  | 1   | 0   | 0   |
| time3  | 1   | 0   | 0   |
| time4  | 0   | 0   | 1   |
| time5  | 0   | 0   | 1   |
| time6  | 0   | 0   | 1   |

### Environment

```markdown
- **QuestDB version**: 6.1.2
- **OS**: RHEL 7.9
- **Browser**: 
- **requests**: 2.11.1 
- **python**: 3.8.8
```

### Additional context

```python
import requests
data1 = open('data1.csv', 'rb').read()
data2 = open('data2.csv', 'rb').read()

payload = {'data': ('test', data1)}

response = requests.post(url='localhost:9000/imp', files=payload,
                         params={
    'timestamp': 'timing',
    'forceHeader': 'true',
    'partitionBy': 'MONTH',
    })

print response.text

payload = {'data': ('test', data2)}

response = requests.post(url='localhost:9000/imp', files=payload,
                         params={
    'timestamp': 'timing',
    'forceHeader': 'true',
    'partitionBy': 'MONTH',
    })

print response.text
```

may not work, i had to hand type since i couldn't copy/paste

### PR DESCRIPTION
**Pull request by eugenels**
Fixes #1758

### CODE REVIEW

**Comment by eugenels** [comment]
Fixes https://github.com/questdb/questdb/issues/1758

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|10|10|100.00%|

File: core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java [hunk 1]
```diff
@@ -225,7 +227,8 @@ private void logTypeError(int i) {
 
     private boolean onField(long line, DirectByteCharSequence dbcs, TableWriter.Row w, int i) {
         try {
-            types.getQuick(i).write(w, i, dbcs);
+            final int tableIndex = remapIndex.size() > 0 ? remapIndex.get(i) : i;
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:230]: can we create NOOP remap so that we don't have to have conditional here?

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|10|10|100.00%|

File: core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java [hunk 2]
```diff
@@ -68,6 +68,7 @@
     private TimestampAdapter timestampAdapter;
     private final TextLexer.Listener partitionedListener = this::onFieldsPartitioned;
     private int warnings;
+    private final IntIntHashMap remapIndex = new IntIntHashMap();
```
[the remark this answers is not in the document]
Comment (eugenels) [reply core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:71]: IntList name is misleading here. It's array based and a good match for task but was "filtered out" cuz "List" part in the name.

File: core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java (hunk 1 above)
Comment (eugenels) [reply core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:230]: By NOOP do you mean prefilled i -> i mapping in case no column reorder?

I'm expecting branch predictor optimisation as size() is invariant here.
 Need to test.

Comment (eugenels) [reply core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:230]:
```
// remapIndex.size() == 0
Benchmark                                     Mode  Cnt   Score   Error  Units
BranchOverIndexAccessBenchmark.testCondition  avgt    5  11.135 ± 0.655  ns/op

// remapIndex.size() == 32
Benchmark                                     Mode  Cnt   Score   Error  Units
BranchOverIndexAccessBenchmark.testCondition  avgt    5  16.546 ± 1.505  ns/op

// remapIndex.size() == 32
Benchmark                 Mode  Cnt   Score   Error  Units
IndexBenchmark.testIndex  avgt    5  16.835 ± 2.407  ns/op

@Benchmark
public long testCondition() {
    long sum = 0;
    for (int i = 0; i < COLUMNS; i++) {
        final int idx = remapIndex.size() > 0 ? remapIndex.get(i) : i;
        sum += data.get(idx);
    }
    return sum;
}

@Benchmark
public long testIndex() {
    long sum = 0;
    for (int i = 0; i < COLUMNS; i++) {
        sum += data.get(remapIndex.get(i));
    }
    return sum;
}
```

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|10|10|100.00%|

File: core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java (hunk 1 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:230]: cool, thank you for the test, i'm convinced :)

**Review by bluestreak01 — APPROVED** [review]

**Comment by sammystevens1983** [comment]
Is this published in the current version, or is this for the upcoming version?
