### PR TITLE
fix(pgwire): fix NPE for prepared statements with filters on indexed column

### LINKED ISSUE #1421: Execution of prepared statement fails if one of the parameters is timestamp
**To Reproduce**
1. Create table:
```
create table numeric_column_value_1(device_id symbol index, column_name symbol index, value double, timestamp timestamp) timestamp(timestamp) partition by day;

insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.1, '2021-10-05T11:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.2, '2021-10-05T12:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.3, '2021-10-05T13:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.4, '2021-10-05T14:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.1, '2021-10-05T11:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.2, '2021-10-05T12:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.3, '2021-10-05T13:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.4, '2021-10-05T14:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.5, '2021-10-05T15:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.1, '2021-10-05T11:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.2, '2021-10-05T12:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.3, '2021-10-05T13:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.4, '2021-10-05T14:31:35.878Z');
```
2. Query table using JDBC template:
a.  Use one parameter that is not timestamp
```
        val result = jdbcTemplate.query({ connection ->
            val preparedStatement = connection.prepareStatement(
                "select * from numeric_column_value_1 where device_id = ?"
            )
            preparedStatement.setString(1, "d1")
            preparedStatement
        }, { resultSet, _ ->
            NumericColumnValue(
                resultSet.getString(1),
                resultSet.getString(2),
                resultSet.getDouble(3),
                resultSet.getTimestamp(4)
            )
        })
```
Result: correct data is returned
Note: works well with two non timestamp parameters as well

b. Use one parameter that is timestamp
```
        val result = jdbcTemplate.query({ connection ->
            val preparedStatement = connection.prepareStatement(
                "select * from numeric_column_value_1 where timestamp > ?"
            )
            preparedStatement.setTimestamp(1, Timestamp(Instant.parse("2021-10-05T15:31:35.878Z").toEpochMilli()))
            preparedStatement
        }, { resultSet, _ ->
            NumericColumnValue(
                resultSet.getString(1),
                resultSet.getString(2),
                resultSet.getDouble(3),
                resultSet.getTimestamp(4)
            )
        })
```
Result: correct data is returned
Note: works well with two timestamp parameters as well, ex: between clause

c. Use one timestamp parameter, another non timestamp
```
        val result = jdbcTemplate.query({ connection ->
            val preparedStatement = connection.prepareStatement(
                "select * from numeric_column_value_1 where device_id = ? and timestamp > ?"
            )
            preparedStatement.setString(1, "d1")
            preparedStatement.setTimestamp(2, Timestamp(Instant.parse("2021-10-05T15:31:35.878Z").toEpochMilli()))
            preparedStatement
        }, { resultSet, _ ->
            NumericColumnValue(
                resultSet.getString(1),
                resultSet.getString(2),
                resultSet.getDouble(3),
                resultSet.getTimestamp(4)
            )
        })
```
Result: request just hangs, no errors are returned.
QuestDB log shows the following:
```
2021-10-11T11:08:27.598688Z I i.q.c.p.PGConnectionContext parse [q=SHOW TRANSACTION ISOLATION LEVEL]
2021-10-11T11:08:27.618054Z I i.q.c.p.PGConnectionContext parse [q=select * from numeric_column_value_1 where device_id = $1 and timestamp > $2]
2021-10-11T11:08:27.618456Z I i.q.c.p.ReaderPool open 'numeric_column_value_1' [at=0:0]
2021-10-11T11:08:27.620890Z I i.q.g.SqlCompiler plan [q=`select-choose device_id, column_name, value, timestamp from (select [device_id, column_name, value, timestamp] from numeric_column_value_1 timestamp (timestamp) where device_id = $1 and timestamp > $2)`, fd=41]
2021-10-11T11:08:27.621921Z E server-main unhandled error [job=io.questdb.cutlass.pgwire.PGWireServer$1@49c6c24f, ex=
java.lang.NullPointerException
	at io.questdb.cutlass.pgwire.AbstractTypeContainer.copyTypesFrom(AbstractTypeContainer.java:60)
	at io.questdb.cutlass.pgwire.TypesAndSelect.of(TypesAndSelect.java:51)
	at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1061)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1444)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:1943)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1393)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:371)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:69)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:76)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:91)
	at io.questdb.mp.Worker.run(Worker.java:112)
]
```

Environment:
QuestDB version: 6.0.7.1
Spring boot version: 2.5.4

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #1421

Includes the following changes:
* Fix NPE for prepared statements with filters on indexed column
* Fix bind variables support in queries with indexed column in filter
  - A bind variable in a query with a filter over an indexed column was completely removed from the filter by the intristics. That led to the incorrect query result since the bind variable literal, e.g. '$1', was used for the index lookup instead of the user provided bind variable value.
* Fix NOT IN over bind variable symbol values
* Fix intrinsics not being used for not equals on bind variables (for both timestamp and indexed symbol column)
* Add missing thread-local path cleaner for PG Wire and HTTP worker pools

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|

**Comment by puzpuzpuz** [comment]
Pushed 3c89899efd24b9cd88ceef624277bacb1dff2b76 to add missing thread-local path cleaner for PG Wire and HTTP worker pools

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
Changing this one back to draft since I've spotted some issues around the bugfix.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AbstractTypeContainer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /usr/share/vsts-agent/_work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 159 / 164 (96.95%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|20|22|90.91%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|107|110|97.27%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 159 / 164 (96.95%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|20|22|90.91%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|107|110|97.27%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 168 / 176 (95.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|108|111|97.30%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 168 / 176 (95.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|108|111|97.30%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 229 / 236 (97.03%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|108|111|97.30%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 229 / 236 (97.03%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|108|111|97.30%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java [hunk 1]
```diff
@@ -113,20 +134,58 @@ public boolean getBool(Record rec) {
...
+                }
                 testFunc = intTest;
             } else {
+                if (deferredValues != null) {
+                    deferredSet.clear();
+                    for (int i = 0, n = deferredValues.size(); i < n; i++) {
+                        final Function func = deferredValues.getQuick(i);
+                        final int typeTag = ColumnType.tagOf(func.getType());
+                        if (typeTag == ColumnType.CHAR) {
+                            deferredSet.add(String.valueOf(func.getChar(null)));
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java:170]: Note: here we allocate on the query execution path. I'll push a patch to fix that tomorrow.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 272 (97.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java]: Simplified the function in a36593b43a5973c3e16d0b6279e124e0bc089a1f

Now it supports bind variables of only string type which is fine considering that it's the right way to define a symbol bind variable.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 264 / 267 (98.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 264 / 267 (98.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 264 / 267 (98.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java [hunk 2]
```diff
@@ -79,7 +89,7 @@ public Function newInstance(int position, ObjList<Function> args, IntList argPos
         if (var.isConstant()) {
             return BooleanConstant.of(set.contains(var.getSymbol(null)));
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java:90]: This may not work with bind variables

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java:90]: We shouldn't get here unless the IN contents are a mix of constant literals and bind variables (e.g. `in (42, $1)`). That's because the `if` block checks `isConstant()` result and bind variable functions return `false` in this method. Am I missing anything?

Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java:90]: I think it's about case of

``` 
where cast('s' as symbol) in ($0)
```

`var` is the symbol column. I cannot think why it may be constant in real queries

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java:91]: My bad, I misread the code. Fixed the (weird-looking) fast path in 41dc078a91eb00d5c058f6d902e883b66d350583

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 268 (98.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java [hunk 3]
```diff
@@ -69,5 +77,10 @@ private void prepare() {
         for (int i = 0, n = symbolKeys.size(); i < n; i++) {
             map.put(symbolKeys.get(i), 0);
         }
+        if (deferredSymbolKeys != null) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java:80]: suspicious that `map` is never cleaned and re-evaluated

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 265 / 268 (98.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java (hunk 3 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java:80]: That's a good point. Fixed that in 4cfbdc97ba000ed59637388dccbe6938c83db062

The same problem is present in `FilterOnExcludedValuesRecordCursorFactory`, but this PR doesn't change that class. I'm going to fix it in a separate one.

File: core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java [hunk 4]
```diff
@@ -59,44 +59,47 @@ public AbstractDeferredTreeSetRecordCursorFactory(
...
+        this.deferredSymbolFuncs = deferredFuncs;
     }
 
     @Override
     protected AbstractDataFrameRecordCursor getCursorInstance(
             DataFrameCursor dataFrameCursor,
             SqlExecutionContext executionContext
     ) throws SqlException {
-        if (deferredSymbols != null && deferredSymbols.size() > 0) {
+        if (deferredSymbolFuncs != null) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java:94]: I'd rather have 1 map to lookup in row by row evaluation instead of 2.
I understand we need to keep `symbolKeys` and top them up with `deferredSymbolKeys` on every `getCursorInstance` but I think it's better to store the prepared results in 1 map instead of 2.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java:94]: There should be only one of the maps in use effectively. The only case when both of them would contain values is a mix of constant literals (`in ('known_symbol', 'unknown_symbol')`) used for the key column filter. I didn't like the idea of having to rebuild the map on each query execution in the situation when the query doesn't use bind variables, so decided to keep two separate maps: "static" and "dynamic" one. WDTY?

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java [hunk 5]
```diff
@@ -67,6 +63,7 @@ public RowCursor getCursor(DataFrame dataFrame) {
     @Override
     public void prepareCursor(TableReader tableReader, SqlExecutionContext sqlExecutionContext) {
         if (symbolKey == SymbolTable.VALUE_NOT_FOUND) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java:65]: I believe this code will cache `symbolKey` and never re-evaluate it which was fine before using with bind variables. Now this `if` should go away.

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java [hunk 6]
```diff
@@ -89,5 +93,10 @@ private void prepare() {
         for (int i = 0, n = symbolKeys.size(); i < n; i++) {
             map.put(symbolKeys.get(i), 0);
         }
+        if (deferredSymbolKeys != null) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:93]: also suspicious why map is never cleaned

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java (hunk 5 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java]: Nice catch. Fixed in 3fcfb1a9977e3a79b52a5e289a70e7754f0bba34

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java (hunk 6 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:93]: Yes, it's the same problem as in `LatestByValuesFilteredRecordCursor`. Fixed in dadeded966de06cedbbe5ccfbfe2d163569aa027

File: core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java (hunk 4 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java:94]: I only now understood how these interrelated lists are used around, so it' fine to have 2 list of keys here.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java:94]: Let me add some comments to improve the code clarity then.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 271 / 274 (98.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java [hunk 7]
```diff
@@ -162,19 +162,22 @@ private void addEvaluateDynamicIntervals(LongList outIntervals, SqlExecutionCont
 
                     outIntervals.extendAndSet(divider + 1, hi);
                     outIntervals.setQuick(divider, lo);
+                    if (divider == 0 && negated) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java:165]: I'm not sure why `divider==0` condition is here, could you explain please?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 271 / 274 (98.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java (hunk 7 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java:165]: When `divider > 0` and the operation is subtraction, there will be a later `IntervalUtils.subtract(outIntervals, divider)` call on L192. But if the dynamic interval is the very first one, we need to negate it here.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 270 / 273 (98.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java (hunk 7 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java:165]: I think I now got why, nw

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 270 / 273 (98.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the thoughtful review!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 270 / 273 (98.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 270 / 273 (98.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 270 / 273 (98.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 270 / 273 (98.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|132|135|97.78%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredTreeSetRecordCursorFactory.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedRowCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursorFactory.java|3|3|100.00%|
