### PR TITLE
fix(sql): fix out-of-memory errors when using count_distinct() symbol function

### LINKED ISSUE #2898: count_distinct() on symbol column may lead to OOME
### Describe the bug

`count_distinct()` on symbol column may have very high on-heap memory footprint.

### To reproduce

The below example leads to an `OutOfMemoryError` with the default JVM settings. That's due to `IntList` being used in bitset style in the `CountSymbolGroupByFunction` class. With an `IntList`, it's enough for a single large enough symbol key to appear in the group to trigger a `IntList` growth in size up to the key code value.

```sql
create table x as (
  select rnd_symbol(100, 10, 10, 0) sym1,
         rnd_symbol(100, 10, 10, 0) sym2,
         rnd_symbol(181000, 10, 10, 0) sym3,
         cast(172800000000 as timestamp) ts
  from long_sequence(1000000)
) timestamp(ts) partition by day;

select ts, sym1, sym2, count_distinct(sym3) from x;
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.6.1
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2898

Reduces footprint of `count_distinct()` function on all supported types except LONG256. Yet, the most noticeable change is for symbols.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 155 / 187 (82.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/CompactLongHashSet.java|14|37|37.84%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|40|44|90.91%|
|:large_blue_circle:|io/questdb/std/CompactIntHashSet.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/std/LongHashSet.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|3|3|100.00%|

**Comment by bluestreak01** [comment]
@puzpuzpuz thank you! Does this reference an issue at all ?

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz thank you! Does this reference an issue at all ?

Nope, this fix is based on the issue discussed in this lengthy Slack thread: https://questdb.slack.com/archives/C1NFJEER0/p1672082889636169

Let me create a GH issue with a reproducer and reference it here.

**Comment by ideoma** [comment]
`CompactLongHashSet` test coverage is very low, is it because it's copy / paste from better covered `CompactCharSequenceHashSet`?

File: core/src/main/java/io/questdb/std/CompactIntHashSet.java [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+
+import java.util.Arrays;
+
+/**
+ * Unlike {@link IntHashSet} doesn't keep an additional list for faster iteration and index-based access
+ * and also has a slightly higher load factor.
+ */
+public class CompactIntHashSet extends AbstractIntHashSet {
+
+    private static final int MIN_INITIAL_CAPACITY = 16;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/std/CompactIntHashSet.java:35]: Should this be 1 or something lower than 16 to save the size?

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java [hunk 2]
```diff
@@ -32,15 +32,15 @@
...
+import io.questdb.std.CompactIntHashSet;
 import io.questdb.std.Numbers;
 import io.questdb.std.ObjList;
 
 import static io.questdb.cairo.sql.SymbolTable.VALUE_IS_NULL;
 
 public class CountSymbolGroupByFunction extends LongFunction implements UnaryFunction, GroupByFunction {
     private final Function arg;
-    private final ObjList<IntList> lists = new ObjList<>();
+    private final ObjList<CompactIntHashSet> sets = new ObjList<>();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java:43]: It may be enough to have 1 `CompactLongHashSet` and store there 2 integers as 1 long : group_id, symbol_id

**Review by ideoma — COMMENTED** [review]
Seems like biased change towards the case with when many groups and many distinct symbols. Would be good to have a test of how it impacts `count_distinct` without grouping (which is mainstream imho)

Also suggested some further optimisations

**Comment by puzpuzpuz** [comment]
> `CompactLongHashSet` test coverage is very low, is it because it's copy / paste from better covered `CompactCharSequenceHashSet`?

Nope, it's a copy-paste of `LongHashSet` which in its turn is a copy-paste of `IntHashSet`. Let me double check the coverage and improve it across all these sets.

File: core/src/main/java/io/questdb/std/CompactIntHashSet.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/std/CompactIntHashSet.java:35]: Current initial size is much more compact than the old `IntList`. It should be enough to fit 9 items. I'm not sure if it makes sense to fine-tune initial size and load factor without knowing anything about data. Why do you think we should shrink it? Java object headers themselves are quite something, so setting capacity to 1 would lead to an awful metadata:data ratio.

**Comment by puzpuzpuz** [comment]
> Seems like biased change towards the case with when many groups and many distinct symbols. Would be good to have a test of how it impacts `count_distinct` without grouping (which is mainstream imho)

```
create table x as (
  select rnd_symbol(100, 10, 10, 0) sym1,
         rnd_symbol(100, 10, 10, 0) sym2,
         rnd_symbol(181000, 10, 10, 0) sym3,
         cast(172800000000 as timestamp) ts
  from long_sequence(1000000)
) timestamp(ts) partition by day;

select count_distinct(sym3) from x;
```

Both `master` and this branch show around 25-30ms query execution time on my machine.

**Comment by puzpuzpuz** [comment]
> Let me double check the coverage and improve it across all these sets.

Good spot. I forgot to replace `LongHashSet` with `CompactLongHashSet` in the test, hence low coverage percentage. Fixed in ad0010f74da7a881a2c1c05a406720264265623b

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 189 / 201 (94.03%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|40|44|90.91%|
|:large_blue_circle:|io/questdb/std/CompactIntHashSet.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/std/CompactLongHashSet.java|48|51|94.12%|
|:large_blue_circle:|io/questdb/std/LongHashSet.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|3|3|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java (hunk 2 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java:43]: `ObjList<CompactIntHashSet>` wins by factor of 2 when there is > 10 items in the group, otherwise it loses because of min size. It also can create 1000s of heap objects.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java:43]: Now I get what you're proposing. I'd better create a `FastSet` similar to what we have in `FastMap` and use it in all `count_distinct()` implementations for fixed-size types. WDYT?

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java]: Replaced all `Compact*HashSet` sets and `Long256HashSet` with `FastMap` in 35870a06b459957fae88757be32c518f94bf8abf

Going to measure performance now. A side note: #2868 will improve performance of `FastMap`, so that's something to keep in mind.

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java [hunk 3]
```diff
@@ -48,41 +56,43 @@ public CountDistinctIntGroupByFunction(Function arg) {
...
+    public void computeFirst(MapValue mapValue, Record record) {
         final int val = arg.getInt(record);
         if (val != Numbers.INT_NaN) {
-            set.add(val);
-            mapValue.putLong(valueIndex, 1L);
+            MapKey groupedMapKey = groupedValues.withKey();
+            groupedMapKey.putInt(groupId);
+            groupedMapKey.putInt(val);
+            groupedMapKey.createValue();
+            mapValue.putLong(valueIndex, 1);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java:78]: Can it be `putBoolean()` instead to reduce the memory?

**Review by ideoma — COMMENTED** [review]
Good idea with fast map

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java]: Here are the results:
```sql
create table x as (
  select rnd_symbol(100, 10, 10, 0) sym1,
         rnd_symbol(100, 10, 10, 0) sym2,
         rnd_symbol(181000, 10, 10, 0) sym3,
         cast(172800000000 as timestamp) ts
  from long_sequence(1000000)
) timestamp(ts) partition by day;

select count_distinct(sym3) from x; -- 100ms vs. 30ms before FastMap

select ts, sym1, sym2, count_distinct(sym3) from x; -- 250ms vs 180ms before FastMap
```

So, 3-4x worse times. I've checked if there is any clustering (hash code collisions), but in this scenario there are none. It seems that we spend most of the time comparing keys. See the below flame graph collected while running the first query.

So far, I don't think `eq()` is very inefficient and there are a lot of opportunities to improve it significantly. Looks like we need to decide whether we want to pay the price of on-heap allocations (GC pressure and potential OOMEs) and better performance when the data volume is small or we want to use `FastMap` in `count_distinct()` and, maybe, try to optimize it.

cc @jerrinot who was also complaining about `FastMap` recently.

Screenshot from 2023-01-06 11-44-19

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 198 / 199 (99.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LongHashSet.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|32|32|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|32|32|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|32|32|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|31|31|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java (hunk 3 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java:78]: This `valueIndex` map column stores the `count_distinct()` result, so the `long` counter. Are you referring to another line or I'm missing something?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 198 / 199 (99.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LongHashSet.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|32|32|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|32|32|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|32|32|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|31|31|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java (hunk 2 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java]: Sounds like `ObjList<CompactIntHashSet>` is better than `FastMap`. Why `FastMap`, not `CompactLongHashSet`?

From where it stands now, first implementation iteration was better than the second.

What's your opinion, you think `FastMap` is good enough or you want to try something else? Binary Search Tree can be a candidate, it's compact and insertion / search is logarithmic but we will need to write the data structure, which will take quite some time.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java]: > Why `FastMap`, not `CompactLongHashSet`?

That's because `FastMap` applies to all `count_distinct()` overloads, not just int and symbol. The main advantage is that the data is stored off-heap instead of lots of on-heap objects.

> What's your opinion, you think `FastMap` is good enough or you want to try something else? Binary Search Tree can be a candidate

In this particular test there were no collisions, so a binary tree would have no advantage. The time seems to be spend mostly on key equality check which is inevitable with search in any data structure. We might want to spend some time optimizing `FastMap` once all in-flight PRs are merged.

I'm going to revert `FastMap`-related commits for now as this fix is important for one of our users.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java:43]: Reverted the changes in 5536c9a96b2d78d978e45477f1aa37146aaae4e7 and 1b45cb7941a851bf9be5ebae670611967517ef57

Going to give a try optimizing `FastMap` in a separate PR, probably next week.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 189 / 201 (94.03%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|40|44|90.91%|
|:large_blue_circle:|io/questdb/std/CompactIntHashSet.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/std/CompactLongHashSet.java|48|51|94.12%|
|:large_blue_circle:|io/questdb/std/LongHashSet.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|3|3|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 189 / 201 (94.03%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|40|44|90.91%|
|:large_blue_circle:|io/questdb/std/CompactIntHashSet.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/std/CompactLongHashSet.java|48|51|94.12%|
|:large_blue_circle:|io/questdb/std/LongHashSet.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|3|3|100.00%|
