### PR TITLE
fix(griffin) - insert as select without nominating timestamp - fixed #364 #349

### LINKED ISSUE #364: Reporting unknown function error when the function is valid but arguments are wrong
**Describe the bug**
When function is called with incorrect arguments, the error sent to user says that the function is unknown, even though the function is valid. It should tell the user that the argument is incorrect and what was expected.
` unknown function: timestamp_sequence(TIMESTAMP,LONG)`

**To Reproduce**
timestamp_sequence(systimestamp(), 1)

### PR DESCRIPTION
**Pull request by jaugsburger**
To summarise, this is what it's fixed on  the PR:
1. insert as select without nominating timestamp
2. timestamp_sequence can take systimestamp()
3. invalid argument(s) for function is not longer reported as unknown function

### CODE REVIEW

File: core/src/main/java/io/questdb/griffin/SqlCompiler.java [hunk 1]
```diff
@@ -1464,7 +1404,7 @@ private CompiledQuery insertAsSelect(ExecutionModel executionModel, SqlExecution
             final int cursorTimestampIndex = cursorMetadata.getTimestampIndex();
 
             // fail when target table requires chronological data and cursor cannot provide it
-            if (writerTimestampIndex > -1 && cursorTimestampIndex == -1) {
+            if (writerTimestampIndex > -1 && cursorTimestampIndex == -1 && cursorMetadata.getColumnType(writerTimestampIndex) != ColumnType.TIMESTAMP) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlCompiler.java:1407]: hmm, lets consider the following:

- user is inserting "string" into timestamp column? what do they get as an error?
- user chose not to populate timestamp column of writer? what do they get as an error?
- user assigned column X to timestamp column of the writer, but somehow nominated Y to be column of the cursor? what do they get as an error?

File: core/src/main/java/io/questdb/std/StationaryMicrosClock.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+ *  See the License for the specific language governing permissions and
+ *  limitations under the License.
+ *
+ ******************************************************************************/
+
+package io.questdb.std;
+
+import io.questdb.std.microtime.MicrosecondClock;
+
+public class StationaryMicrosClock implements MicrosecondClock {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/std/StationaryMicrosClock.java:29]: could we move this to test source tree?
