### PR TITLE
fix(sql): fix SAMPLE BY FILL crash with array column aggregates

### LINKED ISSUE #6810: SAMPLE BY FILL crashes with array column aggregates
### To reproduce

Queries that combine array aggregate functions (last, first, last_not_null) with SAMPLE BY FILL(NULL) or SAMPLE BY FILL(value) crash with an UnsupportedOperationException:

```
  -- crashes
  SELECT last(arr) FROM t SAMPLE BY 1h FILL(NULL)

  -- also crashes
  SELECT last(arr) FROM t SAMPLE BY 1h FILL(42)

  FILL(NONE), FILL(PREV), and FILL(LINEAR) are not affected.
```

  Reproduction

On demo box you can do
```
select timestamp, last(bids) from market_data
where timestamp in '$now-1m..$now'
sample by 10s FILL(null)
```

Or locally
```
  CREATE TABLE t (ts TIMESTAMP, arr DOUBLE[]) TIMESTAMP(ts) PARTITION BY DAY;
  INSERT INTO t VALUES
    ('1970-01-01T00:00:00.000000Z', ARRAY[1.0, 2.0]),
    ('1970-01-01T00:00:20.000000Z', ARRAY[3.0, 4.0]);

  -- this crashes with UnsupportedOperationException at Record.getArray()
  SELECT ts, last(arr) FROM t SAMPLE BY 10s FILL(NULL);
```

  Expected behavior

  - FILL(NULL) should produce null arrays in gap buckets
  - FILL(value) should produce null arrays in gap buckets, since arrays cannot be filled with scalar values

### QuestDB version:

9.3.2

### OS, in case of Docker specify Docker and the Host OS:

both ubuntu and osx

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

javier

### Affiliation:

questdb

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by javier**
Fixes #6810

## Summary

- SAMPLE BY with FILL(NULL), FILL(value), or FILL(PREV) crashed when the query included array column aggregates (e.g., `last(arr)`). The fill record types did not implement `getArray()`, and the null/value fill factories did not handle array column types when constructing fill constants.
- `SampleByFillRecord`: add `getArray()` override that delegates to the underlying function, covering FILL(NULL), FILL(PREV), and FILL(LINEAR).
- `SampleByFillNullRecordCursorFactory` / `SampleByFillValueRecordCursorFactory`: handle array types by yielding `NullConstant.NULL` (arrays cannot be filled with scalar values).
- `FillRangeRecordCursorFactory.FillRangeRecord`: add `getArray()` override for the ALIGN TO CALENDAR / FROM ... TO code path.

## Test plan

- Add 7 tests in `LastArrayGroupByFunctionFactoryTest` covering all SAMPLE BY FILL modes with array columns: FILL(NONE), FILL(NULL) keyed, FILL(NULL) not-keyed, FILL(PREV), FILL(value), ALIGN TO CALENDAR, and FROM ... TO ... FILL(NULL)
- The ALIGN TO CALENDAR and FROM ... TO tests specifically exercise the `FillRangeRecordCursorFactory` path
- Verify FILL(NULL) with array columns returns null (arrays cannot be filled with scalar values)
- Verify FILL(value) with array columns raises a clear error ("not supported") instead of the previous uncontrolled crash

### CODE REVIEW

**Comment by javier** [comment]
please @coderabbitai, review this bug fix critically

**Comment by javier** [comment]
@coderabbitai Thanks for the thorough review. Here's what was addressed and what was not:

**Finding 1 - FILL(LINEAR) not covered**: This is already handled at compile time by `GroupByUtils`, which checks the `SAMPLE_BY_FILL_LINEAR` flag on each group-by function. `LastArrayGroupByFunction` does not set this flag, so `FILL(LINEAR)` with array columns is rejected before reaching `InterpolationGroupByFunction`. Added a negative test to verify this behavior explicitly.

**Finding 2 - FILL(value) silently returns NULL**: Agreed, this was wrong. Changed `createPlaceHolderFunction()` to throw `SqlException` with a clear message directing users to use `FILL(NULL)` instead of silently substituting NULL. Replaced the old test with a negative test.

**Finding 3 - Test coverage for other array types (INT[], LONG[], etc.)**: QuestDB currently only supports DOUBLE[] for array group-by functions (`first_array`, `last_array`, and the upcoming `array_agg`). There are no INT[] or LONG[] array group-by functions to test.

**Finding 4 - SampleByFirstLastRecordCursorFactory**: This factory is only used for SAMPLE BY without FILL modes, so it does not need `getArray()` overrides.

**Finding 5 - FillRangeRecord.getArray() ignores columnType**: This is consistent with all other getter methods in fill records - the fill function provides the value directly and does not need the column type parameter. The `columnType` is only meaningful when delegating to the base record, which the non-gapfilling branch already does.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastArrayGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/FillRangeRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNullRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillRecord.java|1|1|100.00%|

**Comment by RaphDal** [comment]
The default implementation of `getSampleByFlags` in `GroupByFunction.java` returns all the sample by flags: `SAMPLE_BY_FILL_VALUE | SAMPLE_BY_FILL_NONE | SAMPLE_BY_FILL_NULL | SAMPLE_BY_FILL_PREVIOUS`.

If I understand correctly, arrays doesn't support `SAMPLE_BY_FILL_VALUE`.
This PR does update the `getSampleByFlags` in [LastArrayGroupByFunction.java](https://github.com/questdb/questdb/pull/6811/changes#diff-fc957e830278ad3865a62708451f419727b68707714c5032102a91ea8cfc1424) but it doesn't update the remaining `*ArrayGroupByFunction`:

- FirstArrayGroupByFunction
- FirstNotNullArrayGroupByFunction
- LastNotNullArrayGroupByFunction

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 1]
```diff
@@ -781,7 +781,14 @@ private static boolean allGroupsFirstLastWithSingleSymbolFilter(QueryModel model
...
 
-                if (columnAst.rhs.type != LITERAL || metadata.getColumnIndex(columnAst.rhs.token) < 0) {
+                if (columnAst.rhs.type != LITERAL) {
+                    return false;
+                }
+                int argColIndex = metadata.getColumnIndex(columnAst.rhs.token);
+                if (argColIndex < 0) {
+                    return false;
+                }
+                if (ColumnType.isArray(metadata.getColumnType(argColIndex))) {
```
Comment (RaphDal) [inline core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:793]: Can we have a comment explaining why we don't allow arrays in this case please.

**Comment by questdb-butler** [comment]
## ⚠️ Enterprise CI Failed

The enterprise test suite failed for this PR.

**Build:** [View Details](https://dev.azure.com/questdb/questdb-enterprise/_build/results?buildId=217758)
**Tested Commit:** `471293a6ff9c1e8ba0ad27bd3c6b3c7adadd6608`

Please investigate the failure before merging.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 21 (95.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstArrayGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastArrayGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/FillRangeRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNullRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillRecord.java|1|1|100.00%|

**Comment by questdb-butler** [comment]
## ⚠️ Enterprise CI Failed

The enterprise test suite failed for this PR.

**Build:** [View Details](https://dev.azure.com/questdb/questdb-enterprise/_build/results?buildId=217973)
**Tested Commit:** `3413c9c2b1aa3b60a7b8c593cbfea430a7ffd803`

Please investigate the failure before merging.
