### PR TITLE
fix(sql): fixed PG ODBC driver compatibility problems

### LINKED ISSUE #2026: 6.2.1 version have problem accessed from postgres and  odbc
### Describe the bug

image

the 6.2.0 version can access from postgres odbc ,but 6.2.1 can't

I can get records from odbc and "pass through"  in 6.2.0 version ,but failed in 6.2.1

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version 6.2.1:
- **OS**: windows and linux
- **Browser**:
```

### Additional context

image

### PR DESCRIPTION
**Pull request by bluestreak01**
Fixed #2026

- fixed few more PG metadata SQLs
- fixed double-free in join generator, in case there is exception
- fixed incorrect join optimisation, which lead to assertion errors
- improved PG SQL compatibility

PG can execute the following SQL, while without this PR we could not
```sql
select a.f, b.p from (tab1 a join tab2 b on id)
```

Notice that `join` is inside braces, which QuestDB was interpreting as sub-query and could not reference tables within by aliases `a` and `b`. Now SQL parser will remove bracket in this simplified case to rewrite the above SQL as:

```sql
select a.f, b.p from tab1 a join tab2 b on id
```
to allow aliases to be used.

All "real" sub-queries are not affected.

Also, fixed SQL execution from Excel:

image

image

image

image

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 323 / 329 (98.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|74|77|96.10%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 318 / 329 (96.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|69|77|89.61%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|75|76|98.68%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlParser.java [hunk 1]
```diff
@@ -950,69 +939,52 @@ private QueryModel parseDmlUpdate(GenericLexer lexer) throws SqlException {
...
 
-            if (tok.length() != 1 || tok.charAt(0) != ',') {
+            // do not collapse aliased sub-queries or those that have timestamp()
+            // select * from (table) x
+            if (tok == null || (tableAliasStop.contains(tok) && !SqlKeywords.isTimestampKeyword(tok))) {
+
+                final QueryModel target = proposedNested.getNestedModel();
+                // when * is artificial, there is no union, there is no "where" clause inside sub-query,
+                // e.g. there was no "select * from" we should collapse sub-query to a regular table
+                if (
```
Comment (bziobrowski) [inline core/src/main/java/io/questdb/griffin/SqlParser.java:957]: What if there's group by or joined model(s) contain where clause, union model, etc. ?

Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlParser.java:957]: yeah, this is taken into account. Full condition is below your comment:

```
          proposedNested.isArtificialStar()
                                && proposedNested.getUnionModel() == null
                                && target.getWhereClause() == null
                                && target.getOrderBy().size() == 0
                                && target.getLatestBy().size() == 0
                                && target.getNestedModel() == null
                                && proposedNested.getLimitLo() == null
                                && proposedNested.getLimitHi() == null
```

Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/SqlParser.java:957]: Conditional checks if : 
- proposedNested doesn't have set operations & limit clause 
- target doesn't have where clause, order by, latest by or nested model 
Could proposedNested itself contain e.g. group by, joins, latest by that could disappear  because only tablename, alias, timestamp and joins are copied ?

Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlParser.java:957]: There are no existing unit tests that would need additional checks. I will try to see if these are actual possible combinations, considering how models are created and nested.

@bziobrowski if you already have an idea of SQLs' that might not work correctly with this feature, please share

Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlParser.java:957]: you were right, there were side effects with sample & group by. Fixed here: https://github.com/questdb/questdb/pull/2031/commits/52ca146d5f5c5ba1bae85d1106945040337c1378

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 320 / 331 (96.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|69|77|89.61%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/IntArrayDereferenceHackFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqBooleanCharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|77|78|98.72%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowStandardConformingStringsCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTransactionIsolationLevelCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttrDefCatalogueFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PgGetSIExprFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SingleValueRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|69|69|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedAttrDefCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowSearchPathCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowMaxIdentifierLengthCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/PrefixedPgGetSIExprFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/IntValueRecord.java|4|4|100.00%|

**Review by bziobrowski — APPROVED** [review]
👍
