### PR TITLE
fix(pgwire): fix pg wire network send error

### LINKED ISSUE #3677: NoSpaceLeftInResponseBufferException while querying data with PgWire
### Describe the bug

_No response_

### To reproduce

Long running Pg query resulted in 
```
2023-08-21T17:08:39.868260Z C i.q.c.p.PGWireServer internal error [ex=io.questdb.network.NoSpaceLeftInResponseBufferException: no space left in response buffer
	at io.questdb.mp.Worker.run(Worker.java:118)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:120)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:178)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:83)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:412)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1643)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExec(PGConnectionContext.java:2165)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processExecute(PGConnectionContext.java:2176)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(PGConnectionContext.java:2572)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(PGConnectionContext.java:2588)
	at io.questdb.cutlass.pgwire.PGConnectionContext.appendRecord(PGConnectionContext.java:801)
	at io.questdb.cutlass.pgwire.PGConnectionContext.appendSymbolColumn(PGConnectionContext.java:933)
	at io.questdb.std.str.CharSink.encodeUtf8(CharSink.java:37)
	at io.questdb.std.str.CharSink.encodeUtf8(CharSink.java:45)
	at io.questdb.std.str.CharSink.putUtf8Special(CharSink.java:178)
	at io.questdb.cutlass.pgwire.PGConnectionContext$ResponseAsciiSink.put(PGConnectionContext.java:2931)
	at io.questdb.cutlass.pgwire.PGConnectionContext$ResponseAsciiSink.ensureCapacity(PGConnectionContext.java:3025)
	at io.questdb.network.NoSpaceLeftInResponseBufferException.<clinit>(NoSpaceLeftInResponseBufferException.java:33)
2023-08-21T17:08:39.870337Z I pg-server scheduling disconnect [fd=640807, reason=17]
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:6.7
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ideoma**
fixes #3677

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 2 / 11 (18.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|11|18.18%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 2 / 11 (18.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|11|18.18%|

**Comment by ideoma** [comment]
The fix is covered by `Table2IlpTest.copyAllColumnTypes` test if running multiple times.

File: core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java [hunk 1]
```diff
@@ -2453,6 +2453,20 @@ private void sendAndReset() throws PeerDisconnectedException, PeerIsSlowToReadEx
         responseAsciiSink.reset();
     }
 
+    private void sendAndResetWait() throws PeerDisconnectedException {
+        // This is simplified waited send for very limited use cases where introducing another state is an overkill.
+        // This method busy waits to send buffer.
+        while (true) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:2459]: Would be nice to check the circuit breaker around this place to avoid a potentially infinite loop. WDYT?

Comment (ideoma) [reply core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:2459]: good idea

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 2 / 17 (11.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|12|16.67%|

File: core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java (hunk 1 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:2459]: done

**Review by puzpuzpuz — APPROVED** [review]
