### PR TITLE
fix(sql): compilation error for symbol column to symbol cast in group by query

### LINKED ISSUE #6071: 500 error when self-casting a symbol
### To reproduce

reproducible on demo:

```sql
SELECT cast(timestamp as LONG) AS timestamp, symbol::SYMBOL AS "ID",round(avg(price))::LONG AS "Evt1" 
FROM 'trades' 
WHERE timestamp IN '2025-05-24';
```

Image

Fails at:

https://github.com/questdb/questdb/blob/75335d33b1d7e60ee3b4ff26d5cc0680361864a3/core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java#L97

### QuestDB version:

9.0.2

### OS, in case of Docker specify Docker and the Host OS:

N/A

### File System, in case of Docker specify Host File System:

N/A

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #6071

Also removes string sinks from `IPv4Function`: they were only used in UPDATEs. UPDATEs will now generate a wrapper cast function, like it's done with most other fixed-size types.

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
@nwoolmer could you review this one when you have the time?

File: core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java [hunk 1]
```diff
@@ -187,64 +190,65 @@ public static void assembleGroupByFunctions(
...
+                final int index = findColumnKeyIndex(node, func, baseMetadata);
+                if (index != -1) {
+                    if (index != timestampIndex || timestampUnimportant) {
+                        // when we have the same column several times in a row,
+                        // we only add it once to map keys
+                        if (lastIndex != index) {
+                            columnKeyCount++;
+                            lastIndex = index;
+                        }
+                    }
```
Comment (nwoolmer) [inline core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java:203]: This assumes a sorted order for the column indices. Is this an invariant?

File: core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java [hunk 2]
```diff
@@ -405,6 +401,9 @@ public static boolean isEarlyExitSupported(ObjList<GroupByFunction> functions) {
         return true;
     }
 
+    // prepareGroupByFunctions must be called first to get the idea of how many map values
+    // we will have. Map value count is needed to calculate offsets for map key columns.
+
```
Comment (nwoolmer) [inline core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java]: Was the comment relocation intentional? Maybe we can pin it to a function by making it a docstring

**Comment by puzpuzpuz** [comment]
@coderabbitai review

File: core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java:203]: I guess, that's a best-effort attempt to reuse column keys / reduce their number. So, if the keys are something like `col1, col2, col1, col2`, it won't kick in.

File: core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java]: No, it wasn't intentional. The comment is obsolete, so I fixed it in 2c95fd224595b8b23fb000641d1ab913f180b8b2. It's now attached to `prepareWorkerGroupByFunctions()`.

File: core/src/main/java/io/questdb/griffin/engine/functions/columns/IPv4Column.java [hunk 3]
```diff
@@ -25,33 +25,26 @@
 package io.questdb.griffin.engine.functions.columns;
 
 import io.questdb.cairo.sql.Record;
-import io.questdb.cairo.sql.Function;
-import io.questdb.griffin.PlanSink;
 import io.questdb.griffin.engine.functions.IPv4Function;
 import io.questdb.std.Numbers;
 
-public class IPv4Column extends IPv4Function implements Function {
+public class IPv4Column extends IPv4Function implements ColumnFunction {
```
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/columns/IPv4Column.java:34]: I removed redundant sinks from `IPv4Function`.

**Comment by puzpuzpuz** [comment]
@nwoolmer thanks for the review!

File: core/src/main/java/io/questdb/griffin/engine/functions/columns/ColumnFunction.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+ *  limitations under the License.
+ *
+ ******************************************************************************/
+
+package io.questdb.griffin.engine.functions.columns;
+
+import io.questdb.cairo.sql.Function;
+import io.questdb.griffin.PlanSink;
+
+public interface ColumnFunction extends Function {
```
Comment (jerrinot) [inline core/src/main/java/io/questdb/griffin/engine/functions/columns/ColumnFunction.java:34]: this would deserve a description - who is supposed to implement it? why?

File: core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java [hunk 5]
```diff
@@ -613,4 +611,19 @@ private static boolean compareNodesGroupByFunctionKey(
...
+    /**
+     * Returns the column index from the given base metadata in two cases:
+     * 1. it's a column literal
+     * 2. cast(a_column as same_type) which is compiled as a_column (the case is no-op)
+     */
+    private static int findColumnKeyIndex(ExpressionNode node, Function func, RecordMetadata baseMetadata) {
+        if (node.type == LITERAL) {
+            return baseMetadata.getColumnIndexQuiet(node.token);
+        }
+        if (SqlKeywords.isCastKeyword(node.token) && func instanceof ColumnFunction) {
```
Comment (jerrinot) [inline core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java:623]: a wild guess: will this work with JSONs? ~`SqlOptimizer`~ `SqlParser` does some sorcery with JSON and casting. 

edit: SqlParser, not optimizer. See `rewriteJsonExtractCast()`

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java:623]: JSON-backed keys won't use `ColumnFunction`, so this doesn't affect them.

File: core/src/main/java/io/questdb/griffin/engine/functions/columns/ColumnFunction.java (hunk 4 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/columns/ColumnFunction.java:34]: Added javadoc in f4a0ff6bf577bbede043fad7906b1060bf30b0c4

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 80 / 87 (91.95%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/IPv4Column.java|7|8|87.50%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|36|41|87.80%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/DateColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/CharColumn.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/StrColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/VarcharColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/BooleanColumn.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/ArrayColumn.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/FloatColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/Long128Column.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/ColumnFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/Long256Column.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/ShortColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/BinColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IPv4Function.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/DoubleColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/UuidColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/LongColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/TimestampColumn.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/ByteColumn.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/IntColumn.java|1|1|100.00%|
