### PR TITLE
fix(cairo): fix table locked on concurrent reads and create table

### LINKED ISSUE #1575: CREATE TABLE IF NOT EXISTS produces SqlException: [27] cannot acquire table lock [lockedReason=busyReader]
### Describe the bug

Concurrent writes and reads lead to `io.questdb.griffin.SqlException: [27] cannot acquire table lock [lockedReason=busyReader]` if `CREATE TABLE IF NOT EXISTS` SQL is called before each `TableWriter#commit`

### To reproduce

1. Clone https://github.com/zhmaeff/questdb-reproducer
2. Run `QuestdbReproducerApplicationTests#exceptionsDuringConcurrentWritesAndReads` test
3. Open `Test Results - QuestdbReproducerApplicationTests_exceptionsDuringConcurrentWritesAndReads.html` in your browser to see one of my exported test results from IntelliJ IDEA.

NOTE: There is also `QuestdbReproducerApplicationTests#noExceptionsDuringConcurrentWritesAndReads` test, where `CREATE TABLE IF NOT EXISTS` is called only once before all writes. In this scenario, there are no exceptions.

### Expected Behavior

No exceptions during concurrent writes and reads using Java Embedded API and SQL

### Environment

```markdown
- **QuestDB version**: 6.1.1-jdk8
- **OS**: macOS Monterey 12.0.1
- **Browser**: N/A
```

### Additional context

Reproducer repo: https://github.com/zhmaeff/questdb-reproducer

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #1575

**Important note**. Obviously, in the original scenario readers may face `table does not exist` SqlException in case when a writer didn't create the table yet. This is the expected behavior and this fix does not change it.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|6|83.33%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|6|83.33%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

File: core/src/test/java/io/questdb/EmbeddedApiTest.java [hunk 1]
```diff
@@ -158,4 +165,129 @@ public void testReadWrite() throws Exception {
...
+                            writer.commit();
+                        }
+                    } catch (SqlException e) {
+                        errors.incrementAndGet();
+                        e.printStackTrace();
+                    }
+                }
+                latch.countDown();
+            } catch (Exception e) {
+                e.printStackTrace();
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/EmbeddedApiTest.java:289]: could we perhaps bump done latch and error count here too? Or may be restructure exception handling ?

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

File: core/src/test/java/io/questdb/EmbeddedApiTest.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/EmbeddedApiTest.java:280]: Sounds reasonable. Did that in d31c145608446cf494d308002c84771b4e1e8f65

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

File: core/src/test/java/io/questdb/EmbeddedApiTest.java (hunk 1 above)
Comment (bluestreak01) [reply core/src/test/java/io/questdb/EmbeddedApiTest.java:280]: thank you Andrey 👍
