### PR TITLE
fix(sql): fix SELECT DISTINCT queries with table name prefixed columns

### LINKED ISSUE #6058: questdb 9.0.2: invalid table name or alias
### To reproduce

Run this simple query (it works in 8.3.3, stopped working on 9.0.0):

select distinct samples.sensor_id,sensors.apptype
from samples
inner join sensors on sensors.sensor_id = samples.sensor_id
;
ERROR:  Invalid table name or alias
LINE 1: select distinct samples.sensor_id,sensors.apptype
        ^

Table definitions as following:

create table if not exists sensors (
  -- sensor ID, UUID
  sensor_id SYMBOL capacity 1000000 cache,
  UUID SYMBOL capacity 1000000 cache,

--  app_instance_id LONG,
  event_id INT,
  condition_id INT,

  -- enterprise
  network_name SYMBOL,

  -- building data
  building_name SYMBOL,
  building_description SYMBOL,

  -- device data
  device_name SYMBOL,
  device_location SYMBOL,
  device_area_code SYMBOL,
  device_city SYMBOL,
  device_address SYMBOL,

  -- node data
  node_serial_number SYMBOL,
  node_name SYMBOL,

  -- source (probe, FCC)
  source SYMBOL,
  apptype INT,

  -- probe data
  probe_description SYMBOL,
  probe_address SYMBOL,
  model_id INT,
  feature SYMBOL,
  feature_idx INT,
  feature_description SYMBOL,

  -- tag (probe/advanced monitoring)
  tag SYMBOL,

  -- timestamp is mandatory
  ts TIMESTAMP
) timestamp (ts)
partition by day
wal;

create table if not exists samples (
  sensor_id SYMBOL cache,
  "sample" FLOAT,

  ts TIMESTAMP
), index(sensor_id)
timestamp(ts)
partition by day
ttl 5 years
wal
;

### QuestDB version:

9.0.2

### OS, in case of Docker specify Docker and the Host OS:

Red Hat Enterprise Linux release 9.5 (Plow)

### File System, in case of Docker specify Host File System:

xfs

### Full Name:

Andrea Moretto

### Affiliation:

HyperMatrix

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #6066: join goes AWOL in select distinct query
### To reproduce

SQL steps:

```sql
create table historical (
    account_id int
);

create table metrics (
    metric int
);

create table current (
    account_id int,
    metric int
);

EXPLAIN
SELECT distinct h.account_id, m.metric
  FROM historical h
  cross join metrics m
  LEFT JOIN current c ON h.account_id = c.account_id and m.metric = c.metric
  WHERE c.account_id IS NULL;
```

In `SqlOptimiser.optimise` at the `rewriteSelectClause` step, it will fail. rewrittenModel is:

```
select h.account_id, m.metric from ((select-group-by account_id, metric, count() count from (select-choose h.account_id account_id, m.metric metric from (historical h where c.account_id = NULL) h) h) h) h
```

Validation fails in `validateColumnAndGetModelIndex` because `modelAliasesIndexes` does not contain `m`. 

It seems the cross join went missing.

This will work instead:

```
  SELECT h.account_id, m.metric, count()
  FROM historical h
  cross join metrics m
  LEFT JOIN current c ON h.account_id = c.account_id and m.metric = c.metric
  WHERE c.account_id IS NULL;
```

Which is more or less what the rewrite is supposed to do

### QuestDB version:

9.0.2

### OS, in case of Docker specify Docker and the Host OS:

N/A

### File System, in case of Docker specify Host File System:

N/A

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #6058
Fixes #6066 

Queries like
```sql
select distinct sensors.sensor_id, sensors.apptype
from sensors;
```
and any queries that involve table name-prefixed columns in SELECT weren't compiling. That's due to select distinct to group by rewrite combined with expression alias generation. The alias generation kept `sensors.sensor_id` as the column alias, without any quotes, and later `SqlOptimiser` removed the `sensors.` leading to broken column references between the outer and the nested query models.

The fix is to use `sensor_id` instead of `sensors.sensor_id` as the implicit alias.

### CODE REVIEW

File: core/src/main/java/io/questdb/griffin/SqlUtil.java [hunk 1]
```diff
@@ -96,17 +96,28 @@ public static CharSequence createExprColumnAlias(
...
-        if (!quote && aliasToColumnMap.excludes(base) && len > 0 && len <= maxLength && base.charAt(len - 1) != ' ') {
+        if (!quote && aliasToColumnMap.excludes(base) && len > 0 && len <= maxLength && base.charAt(len - 1) != ' ' && indexOfDot == -1) {
             return base;
         }
-
+        // special case for table.column expressions
         final CharacterStoreEntry entry = store.newEntry();
+        if (!nonLiteral && indexOfDot > -1) {
+            entry.put(base, indexOfDot + 1, base.length());
+            return createExprColumnAlias(
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlUtil.java]: i feel like recursion here could be simplified to a loop. The `base` more often then not is already an "entry". It can just be squashed. Can we do without recursion and excessive string copying?

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlUtil.java]: > Can we do without recursion and excessive string copying?

Sure, initial version had no recursion, but the code was bulkier. I'll remove the recursion.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlUtil.java]: Done in 6eddd20fa79a6190166f9d1d26d2c651b18c9cd8

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|13|13|100.00%|

**Comment by ideoma** [comment]
@coderabbitai review

File: core/src/test/java/io/questdb/test/griffin/SqlUtilTest.java [hunk 2]
```diff
@@ -91,29 +102,64 @@ public void testExprColumnAliasSimpleCase() {
...
+        );
+
+        for (int i = 0; i < 100; i++) {
+            Assert.assertEquals(
+                    "basic_" + (i + 2),
+                    SqlUtil.createExprColumnAlias(store, "table.basic", aliasMap, 64).toString()
+            );
+            aliasMap.put("basic_" + (i + 2), null);
+        }
     }
```
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/griffin/SqlUtilTest.java]: Done in 380a0e8c24a7c0a575a1104e227894018e5eedca

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 35 / 35 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|25|25|100.00%|

**Comment by bluestreak01** [comment]
really solid PR, thanks @puzpuzpuz 👍

**Comment by puzpuzpuz** [comment]
@bluestreak01 thanks for the review!
