### PR TITLE
chore(ilp): fixing flapping ILP tests

### LINKED ISSUE #2082: Flaky LineTcpCommitTest.testCommitIntervalBasedDefaultLagZero test
Occured on mac-other:
```
2022-04-27T07:01:48.8839170Z 2022-04-27T07:01:47.936944Z I i.q.c.AbstractCairoTest Tearing down test LineTcpCommitTest#testCommitIntervalBasedDefaultLagZero
2022-04-27T07:01:48.8842470Z 2022-04-27T07:01:47.965650Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.line.tcp.LineTcpCommitTest.testCommitIntervalBasedDefaultLagZero : 
2022-04-27T07:01:48.9121740Z java.lang.AssertionError: Timed out on waiting for the data to be committed
2022-04-27T07:01:48.9224260Z 	at org.junit.Assert.fail(Assert.java:89)
2022-04-27T07:01:48.9236340Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:435)
2022-04-27T07:01:48.9239090Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:365)
2022-04-27T07:01:48.9241200Z 	at io.questdb.cutlass.line.tcp.LineTcpCommitTest.testCommitIntervalBasedDefaultLagZero(LineTcpCommitTest.java:78)
2022-04-27T07:01:48.9242970Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-27T07:01:48.9244620Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-27T07:01:48.9246450Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-27T07:01:48.9248080Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-04-27T07:01:48.9281300Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-04-27T07:01:48.9282230Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-04-27T07:01:48.9283110Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-04-27T07:01:48.9284000Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-04-27T07:01:48.9285360Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-04-27T07:01:48.9286350Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-04-27T07:01:48.9287200Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-04-27T07:01:48.9288320Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
2022-04-27T07:01:48.9289580Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
2022-04-27T07:01:48.9290780Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-27T07:01:48.9291680Z 	at java.lang.Thread.run(Thread.java:829)
```

### LINKED ISSUE #2083: Flaky LineTcpReceiverFuzzTest.testDuplicatesReorderingColumnsSendSymbolsWithSpace test
Occured on mac-other:
```
2022-04-27T07:05:26.4646870Z 2022-04-27T07:05:26.418552Z E i.q.c.l.t.AbstractLineTcpReceiverTest Stopping ILP receiver because of an error
2022-04-27T07:05:26.4647780Z java.lang.AssertionError: Timed out on waiting for the data to be ingested
2022-04-27T07:05:26.4648510Z 	at org.junit.Assert.fail(Assert.java:89)
2022-04-27T07:05:26.4649390Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.assertTable(AbstractLineTcpReceiverFuzzTest.java:169)
2022-04-27T07:05:26.4650470Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.lambda$runTest$3(AbstractLineTcpReceiverFuzzTest.java:426)
2022-04-27T07:05:26.4651860Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$0(AbstractLineTcpReceiverTest.java:214)
2022-04-27T07:05:26.4652870Z 	at io.questdb.cairo.AbstractCairoTest.lambda$assertMemoryLeak$1(AbstractCairoTest.java:357)
2022-04-27T07:05:26.4653770Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:408)
2022-04-27T07:05:26.4654650Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:354)
2022-04-27T07:05:26.4655550Z 	at io.questdb.cairo.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:349)
2022-04-27T07:05:26.4656500Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:204)
2022-04-27T07:05:26.4657550Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:390)
2022-04-27T07:05:26.4658590Z 	at io.questdb.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.runTest(AbstractLineTcpReceiverFuzzTest.java:365)
2022-04-27T07:05:26.4659720Z 	at io.questdb.cutlass.line.tcp.LineTcpReceiverFuzzTest.testDuplicatesReorderingColumnsSendSymbolsWithSpace(LineTcpReceiverFuzzTest.java:73)
2022-04-27T07:05:26.4660690Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-27T07:05:26.4661610Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-27T07:05:26.4662590Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-27T07:05:26.4663450Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-04-27T07:05:26.4664270Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-04-27T07:05:26.4665190Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-04-27T07:05:26.4666090Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-04-27T07:05:26.4666990Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-04-27T07:05:26.4667880Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-04-27T07:05:26.4668760Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-04-27T07:05:26.4669590Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-04-27T07:05:26.4670490Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
2022-04-27T07:05:26.4671480Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
2022-04-27T07:05:26.4672360Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-27T07:05:26.4673080Z 	at java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by glasstiger**
- LineTcpCommitTest close socket only after assertions are done on the data
- dump content of ilp socket read buffer if there is anything left unprocessed before closing the socket on the server

Fixes #2082
Fixes #2083

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|3|3|100.00%|

File: core/src/main/java/io/questdb/network/AbstractIODispatcher.java [hunk 1]
```diff
@@ -263,6 +263,8 @@ protected void doDisconnect(C context, int src) {
         if (context == null || context.invalid()) {
             return;
         }
+        context.dumpBuffer();
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/network/AbstractIODispatcher.java:266]: is this debug leftover ?

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/questdb/network/AbstractIODispatcher.java (hunk 1 above)
Comment (glasstiger) [reply core/src/main/java/io/questdb/network/AbstractIODispatcher.java:266]: no, that is intentional.
idea is that if anything left in the buffer it will be dumped to the logs so we will see that something was not processed.

Comment (bluestreak01) [reply core/src/main/java/io/questdb/network/AbstractIODispatcher.java:266]: in this case it should be printer as binary rather than assumed to be UTF8 encoded anything. We do have a method for it:

```
Chars.toSink(BinarySequence sequence, CharSink sink)
```

Comment (glasstiger) [reply core/src/main/java/io/questdb/network/AbstractIODispatcher.java:266]: changed it

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|8|8|100.00%|

**Comment by bluestreak01** [comment]
@glasstiger does this PR fix any of these issues?

https://github.com/questdb/questdb/labels/Schr%C3%B6dinger%27s%20bug

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|8|8|100.00%|

**Comment by glasstiger** [comment]
> @glasstiger does this PR fix any of these issues?
> 
> [ Schrödinger's bug](https://github.com/questdb/questdb/labels/Schr%C3%B6dinger%27s%20bug)

Potentially fixes 2 of them.
Added those to the description of the PR.

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|8|8|100.00%|

**Review by bluestreak01 — APPROVED** [review]
