### PR TITLE
fix(pgwire): fix Rust sqlx crate

### LINKED ISSUE #3204: Queries timing out with Rust's sqlx
### Describe the bug

When using Rust sqlx v0.6.2, I am able to connect to a QuestDB database but unable to perform any query. I get the `Error: PoolTimedOut` on the client's side and no explicit error on QuestDB's log.

### To reproduce

```rust
use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&pool)
    .await?;

    Ok(())
}
```

With the following dependencies:
```
[dependencies]
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
tokio = { version = "1", features = ["full"] }
```

### Expected Behavior

Get a row with an int of value 150.

### Environment

```markdown
- **QuestDB version**: 7.1.1 (self-hosted) running in Docker.
- **OS**: macOS 13.2.1 (22D68) on the client side.
- **Browser**: Firefox 112.0 (64-bit).
- **sqlx**: 0.6.2.
```

### Additional context

The issue has been [reproduced](https://questdb.slack.com/archives/C1NFJEER0/p1681734372002929?thread_ts=1681655792.172009&cid=C1NFJEER0) by @jerrinot.

### PR DESCRIPTION
**Pull request by jerrinot**
fixes #3204

The sqlx crate sends SYNC request right after login and it expects it receive ReadyNewQuery response.

### CODE REVIEW

**Comment by jerrinot** [comment]
sending as a draft to run all existing tests while turning an ad-hoc Rust code into a hex test-case

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 71 / 76 (93.42%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|71|76|93.42%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 71 / 76 (93.42%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|71|76|93.42%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 80 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|72|80|90.00%|

File: core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java [hunk 1]
```diff
@@ -1220,9 +1220,12 @@ public void testAsyncPgExecutesTableDoesNotExists() throws Exception {
...
                 ">500000003e5f5f6173796e6370675f73746d745f315f5f0053454c454354202a2046524f4d20746869737461626c65646f65736e6f7465786973743b0000004400000018535f5f6173796e6370675f73746d745f315f5f004800000004\n" +
-                "<450000004b433030303030004d7461626c6520646f6573206e6f74206578697374205b7461626c653d746869737461626c65646f65736e6f7465786973745d00534552524f520050313500005a0000000549\n" +
-                ">5300000004510000004753454c4543542070675f61647669736f72795f756e6c6f636b5f616c6c28293b0a434c4f534520414c4c3b0a554e4c495354454e202a3b0a524553455420414c4c3b00\n" +
-                "<540000002f000170675f61647669736f72795f756e6c6f636b5f616c6c0000000000000100000413ffffffffffff0000440000000a0001ffffffff430000000d53454c4543542031004300000008534554004300000008534554004300000008534554005a0000000549\n";
+                "<450000004b433030303030004d7461626c6520646f6573206e6f74206578697374205b7461626c653d746869737461626c65646f65736e6f7465786973745d00534552524f52005031350000\n" +
+                ">5300000004\n" +
+                "<5a0000000549\n" +
```
Comment (jerrinot) [inline core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java:1225]: The old behaviour: On error, QuestDB would send an error message followed immediately by ReadyForQuery(IDLE)
The new behaviour: On error, QuestDB sends an error message only. The server sends ReadForQuery(IDLE) is only upon receiving a SYNC message from a client. That's what the pgwire protocol mandates. 

This is meant to be an explanation for reviewers, feel free to resolve it upon reading.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 80 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|72|80|90.00%|

File: core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java [hunk 2]
```diff
@@ -413,18 +415,34 @@ public void handleClientOperation(
...
-                                (int) (recvBufferWriteOffset - recvBufferReadOffset),
-                                compiler
-                        );
+                        try {
+                            parseMessage(
+                                    recvBuffer + recvBufferReadOffset,
+                                    (int) (recvBufferWriteOffset - recvBufferReadOffset),
+                                    compiler
+                            );
+                        } catch (SqlException e) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:431]: can we unnest exception handing pls?

File: core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java [hunk 3]
```diff
@@ -1625,72 +1648,83 @@ private void parse(
...
-                break;
-            default:
-                LOG.error().$("unknown message [type=").$(type).$(']').$();
-                throw BadProtocolException.INSTANCE;
+
+        // after an error we only accept sync and flush messages. everything else is ignored. from the postgres protocol documentation:
+        // "[...] The purpose of Sync is to provide a resynchronization point for error recovery. When an error is detected
+        // while processing any extended-query message, the backend issues ErrorResponse, then reads and discards
+        // messages until a Sync is reached, then issues ReadyForQuery and returns to normal message processing. [...]"
+        if (!inErrorState || type == 'S' || type == 'H') {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:1659]: can we assume that all clients always send sync ? I don't think so, at least we need to validate this. If they don't, error never clears

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java (hunk 2 above)
Comment (jerrinot) [reply core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:431]: yeah, I was unsure how exactly the resume processors work. let me have a look, it should be possible to simplify it.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 90 / 101 (89.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|90|101|89.11%|

File: core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java (hunk 3 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:1661]: clients also disconnect and contexts are reused, this state needs also be cleared on disconnect. Otherwise clearing it on sync is probably ok, may be also on parse? When brand new query comes in - i don't really know. It feels very strict.

Comment (jerrinot) [reply core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:1661]: > clients also disconnect and contexts are reused, this state needs also be cleared on disconnect. 

that's a good one! shouldn't we clear context state on each disconnect? error or not. 
we probably want to clear parsed queries, etc, don't we?

fwiw: if you feel uneasy about potentially disruptive nature of this changeset then the very first commit in this PR offers an alternative: https://github.com/questdb/questdb/pull/3237/commits/f70d561707d67d15b617c68e48893cb9054a9860 - this makes the rust sqlx client working. The rest of this PR is an attempt to make QuestDB more compliant with the protocol, but it's not without risks.

Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java:1661]: right, if the fix is the one liner we should have that (that should be the first course of action next time). Rest is nice to have. To imlement protocol compliance we should source a test, client or anything else that helps us reproduce lack of compliance and create fix taget. Making changes to comply with a badly written documentation is a losing game.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|4|5|80.00%|

**Review by bluestreak01 — APPROVED** [review]
