### PR TITLE
fix(core): prevent inserting designated timestamp beyond year 9999, this would create invalid partition name

### LINKED ISSUE #5469: cannot drop or force drop partitions after Year 9999
### To reproduce

Repro branch here: https://github.com/questdb/questdb/commit/e62f214c5ea55d27dfe465159e7e91a415e0d216

Steps:

- create a table with hourly partitions
- insert a row with `now()`
- insert a row with `now() * 1000`
- observe a partition created with format like this: `57167-12-29T13` i.e `yyyyy-MM-ddTHH`.
- try to DROP or FORCE DROP the partition
- error thrown, partition is not dropped

This is because we try to parse the given partition name as a timestamp, and our parser only supports up to 'yyyy' (ISO).

Branch has the first parts of a fix, but the attempted fix requires adding new implementations in `TimestampFormatCompiler` to handle  the extra `y`s.

We need to support up to 6 `y`s and also a negative timestamps. `now() * 5000` gives year `277972`. `now() * 7000` gives `-196182`. Or we need to somehow handle this with validation. Or maybe we should just drop the partition and not parse it at all.

Banning partitions after Year 9999 may not work, because we create partitions on the fly and maybe that would suspend the table.

This is a nasty problem, because users can mess up a timestamp conversion and accidentally create a far future partition. The partition becomes active, meaning normal ingestion into earlier partitions will have performance degradation (every write is now O3, and partitions are eagerly merged back together).

Worse, it requires manual intervention to fix - either stopping the database and manually deleting the partition, or otherwise truncating the table and reloading data.

### QuestDB version:

8.2.3-SNAPSHOT

### OS, in case of Docker specify Docker and the Host OS:

N/A

### File System, in case of Docker specify Host File System:

N/A

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mtopolnik**
Closes #5469

### CODE REVIEW

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 19 (84.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|18|83.33%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 19 (84.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|18|83.33%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|

File: core/src/main/java/io/questdb/cairo/TableWriter.java [hunk 1]
```diff
@@ -496,8 +496,25 @@ public static int getSecondaryColumnIndex(int index) {
...
+        if (timestamp == Numbers.LONG_NULL) {
+            throw CairoException.nonCritical().put("designated timestamp column cannot be NULL");
+        }
+        if (timestamp < Timestamps.O3_MIN_TS) {
+            throw CairoException.nonCritical().put("designated timestamp before 1970-01-01 is not allowed");
+        }
+    }
+
+    public static void validatePartitioningTimestampBounds(long timestamp) {
+        validateDesignatedTimestampBounds(timestamp);
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cairo/TableWriter.java:513]: i don't get why do we have two separate validation methods that are no used consistently?

File: core/src/main/java/io/questdb/cairo/TableWriter.java [hunk 2]
```diff
@@ -2313,44 +2330,32 @@ public Row newRow() {
...
                 }
-
                 bumpMasterRef();
                 updateMaxTimestamp(timestamp);
                 break;
             case ROW_ACTION_NO_TIMESTAMP:
                 bumpMasterRef();
                 break;
             case ROW_ACTION_O3:
+                validatePartitioningTimestampBounds(timestamp);
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cairo/TableWriter.java:2345]: why can't we validate timestamp on entry to this method?

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/questdb/cairo/TableWriter.java (hunk 1 above)
Comment (mtopolnik) [reply core/src/main/java/io/questdb/cairo/TableWriter.java:513]: Partitioning timestamp has more restrictions than a general designated timestamp. A non-partitioned table can have a designated timestamp, and we currently don't enforce the upper bound in that case.

File: core/src/main/java/io/questdb/cairo/TableWriter.java (hunk 2 above)
Comment (mtopolnik) [reply core/src/main/java/io/questdb/cairo/TableWriter.java:2345]: Same reasoning as above, I wanted to first distinguish whether the timestamp is used for partitioning or not.

File: core/src/main/java/io/questdb/cairo/TableWriter.java (hunk 1 above)
Comment (mtopolnik) [reply core/src/main/java/io/questdb/cairo/TableWriter.java]: I changed the code to apply the same restriction in a non-partitioned table as well.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|
