### PR TITLE
fix(cairo): fixed errors with truncate() and addIndex()

### LINKED ISSUE #1562: Truncate table fails
### Describe the bug

After a very painful exercise indexing existing data as described here: #1561 I got

```
2021-11-11T16:27:13.408660Z E i.q.c.h.p.JsonQueryProcessorState [1204] internal error [q=`truncate table cpu`, ex=
io.questdb.cairo.CairoException: [1224] Cannot truncate fd=4936 to 16777216 bytes
]
```

after trying to truncate the table

### To reproduce

Perform step in #1561 then run

```sql
truncate table cpu;
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**: Windows - this could be windows specific, error 1224 - someone else holding the file mapped
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
Fixes #1562,#1563

The following issues were fixed:

- inability to add index to empty, partitioned table
- `alter table add index` sql was adding indexer at incorrect position. This was apparent when adjacent columns were indexed
- `TableWriter.truncate()` did not clear symbol map files, issue became apparent on re-ingesting the same dataset after truncate
- `TableWriter.trucate()` would SEGFAULT if called in-transaction
- `TableWriter.inTransaction` was true after calling `TableWriter.rollback`. This lead to subsequent commit to SEGFAULT
- symbol capacity 0 (which could be 0 via _txn file) lead to oversized index files slowing down indexing
- index files were using 16M page size to initially allocate files, ignoring configuration values
- renamed `StaticSymbolTable.size()` to `StaticSymbolTable.getSymbolCount()` to disambiguate the return value
- removed unnecessary column truncate operation when partitioned table is truncated. We delete partitions anyway.

### CODE REVIEW

File: core/src/test/java/io/questdb/cairo/TableWriterTest.java [hunk 1]
```diff
@@ -1592,28 +1602,7 @@ public int findNext(long findPtr) {
                 }
                 return super.findNext(findPtr);
             }
-        }, true);
-    }
-
-    @Test
-    public void testDayPartitionTruncateError() throws Exception {
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/cairo/TableWriterTest.java:1599]: removed these tests because we no longer truncate columns in partitioned table, we remove partitions instead

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 28 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 28 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

File: core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java [hunk 2]
```diff
@@ -133,7 +133,7 @@ public void of(CairoConfiguration configuration, Path path, CharSequence columnN
             final long offsetMemSize = SymbolMapWriter.keyToOffset(symbolCount) + Long.SIZE;
             LOG.debug().$("offsetMem.of [columnName=").$(path).$(",offsetMemSize=").$(offsetMemSize).I$();
             this.offsetMem.of(ff, path, offsetMemSize, offsetMemSize, MemoryTag.MMAP_INDEX_READER);
-            symbolCapacity = offsetMem.getInt(SymbolMapWriter.HEADER_CAPACITY);
+            this.symbolCapacity = SymbolMapWriter.getSymbolCapacity(configuration, offsetMem);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java:136]: if you set reader symbol capacity to 

``` 
Math.max(configuration.getDefaultSymbolCapacity(), offsetMem.getInt(HEADER_CAPACITY))
```

when someone changes config default symbol capacity to a large number the readers will not be able to read old symbol columns

File: core/src/main/java/io/questdb/cairo/SymbolMapWriter.java [hunk 3]
```diff
@@ -134,6 +133,10 @@ public SymbolMapWriter(
         }
     }
 
+    static int getSymbolCapacity(CairoConfiguration configuration, MemoryR offsetMem) {
+        return Math.max(configuration.getDefaultSymbolCapacity(), offsetMem.getInt(HEADER_CAPACITY));
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/SymbolMapWriter.java:137]: perhaps use default if `offsetMem.getInt` returns 0

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 33 / 33 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SortedSymbolIndexRowCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|

**Review by ideoma — APPROVED** [review]
