### PR TITLE
fix(sql): return error on REINDEX table with no indexed columns

### LINKED ISSUE #2489: Success/Failure log message for `REINDEX`
### Describe the bug

When executing `REINDEX` for a table without any index, the log message suggest that the operation is completed successfully.
My query:

```
REINDEX TABLE 'taxi_no_index'  LOCK EXCLUSIVE;
```
The message:
image

However, reindexing the same table with column specified shows an error message:

```
REINDEX TABLE 'taxi_no_index' COLUMN payment_type LOCK EXCLUSIVE;
```
Message:
image

### To reproduce

_No response_

### Expected Behavior

While both are correct (you can complete the operation without reindexing anything as there is no index), it'd be useful to have consistency between the two.
Ideally, I think showing an error message indicating no indexed column is more useful for the users.

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**: MacOS
- **Browser**:Chrome
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sreenath-tm**
Fixes #2489 

Issue: Consistency of error message of REINDEX operation for both "REINDEX TABLE 'taxi_no_index'  LOCK EXCLUSIVE;" and "REINDEX TABLE 'taxi_no_index' COLUMN payment_type LOCK EXCLUSIVE;" queries in scenarios where the table does not have any indexes.

Approach : Using the existing functionality of isSupportedColumn I have went through the entire columns and if there is atleast one index for the table the functionality remains as is.Suppose the table does not have any indexes irrespective of whether the REINDEX operation is column based or for the whole column a consistent error message "Table does not have any indexes".

The commented out code contains an alternate approach were a new functionality isSupportedTable is added in IndexBuilder class to tackle the same issue. 

Please take a look at it and let me know which approach would be suited to the scenario.

Testing and Validation : I have tested and validated the same and it is working as expected and the new fix is not affecting any scenarios where the table is having indexes.

### CODE REVIEW

File: core/src/main/java/io/questdb/cairo/IndexBuilder.java [hunk 1]
```diff
@@ -47,6 +47,7 @@ public class IndexBuilder extends RebuildColumnBase {
     public IndexBuilder() {
         super();
         unsupportedColumnMessage = "Column is not indexed";
+        unsupportedTableMessage = "Table does not have any indexes";
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/IndexBuilder.java:50]: This assignment is redundant.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 2]
```diff
@@ -46,6 +46,7 @@ public abstract class RebuildColumnBase implements Closeable, Mutable {
     protected CairoConfiguration configuration;
     protected int rootLen;
     protected String unsupportedColumnMessage = "Wrong column type";
+    protected String unsupportedTableMessage = "Wrong Table type";
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:49]:
```suggestion
    protected String unsupportedTableMessage = "Table does not have any indexes";
```

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 3]
```diff
@@ -264,37 +265,49 @@ private void reindexOneOrAllColumns(
...
+        for (int i = 0, n = metadata.getColumnCount(); i < n; i++){
+            if(isSupportedColumn(metadata,i)){
+                isIndexed=true;
+                break;
+            }
+        }
+
+        if(isIndexed) {
+            if (columnIndex == REBUILD_ALL_COLUMNS) {
+                for (int i = 0, n = metadata.getColumnCount(); i < n; i++) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:281]: It's much simpler to introduce `boolean hasIndexedColumns = false;` variable before this loop and assign it to `true` if there is at least one indexed column. Then we could have the following check after the loop:
```java
if (!hasIndexedColumns) {
    throw CairoException.nonCritical().put(unsupportedTableMessage);
}
```

**Review by puzpuzpuz — COMMENTED** [review]
Please include a test to validate the new error message.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java (hunk 3 above)
Comment (sreenath-tm) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:281]: I had thought about the same approach but in the scenario where the REINDEX operation is called in a column based manner the flow will not go into this loop and it will display the error messade " The column does not have any index" . The issue had specified to have a consistent error message "Table does not have any index" for both the table based and column based REINDEX operation.

Alternatively the approach suggested by you also solves the issue where success message is displayed when the table wise REINDEX operation is performed. Even though the error message will be different for both table based and column based REINDEX operation ,this approach will solve the issue addressed.

If the consistent message for both the flows is not required I will go ahead and make the changes as suggested by you.

Comment (sreenath-tm) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:281]: Sure will make the changes and push again.

**Comment by puzpuzpuz** [comment]
Hi @sreenath-tm 

Do you have any plans to complete this PR any time soon? It's fine if you don't have the time. Then we'll handle it ourselves.

**Comment by sreenath-tm** [comment]
> Hi @sreenath-tm
> 
> Do you have any plans to complete this PR any time soon? It's fine if you don't have the time. Then we'll handle it ourselves.

I have completed the suggested code changes and added a new commit, but I am finding it difficult to understand how to add the test cases.I will add the test cases also within few days.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 4]
```diff
@@ -264,12 +265,15 @@ private void reindexOneOrAllColumns(
             long partitionTimestamp,
             long partitionSize
     ) {
+        boolean isIndexed=false;
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:268]:
```suggestion
        boolean isIndexed = false;
```

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 5]
```diff
@@ -264,12 +265,15 @@ private void reindexOneOrAllColumns(
...
         tempStringSink.clear();
         partitionDirFormatMethod.format(partitionTimestamp, null, null, tempStringSink);
 
+
         if (columnIndex == REBUILD_ALL_COLUMNS) {
             for (int i = 0, n = metadata.getColumnCount(); i < n; i++) {
                 if (isSupportedColumn(metadata, i)) {
+                    isIndexed=true;
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:276]:
```suggestion
                    isIndexed = true;
```

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 6]
```diff
@@ -296,6 +300,11 @@ private void reindexOneOrAllColumns(
                 throw CairoException.nonCritical().put(unsupportedColumnMessage);
             }
         }
+        //To validate if the table has any index or not
+        if(isIndexed) {
+            throw CairoException.nonCritical().put(unsupportedTableMessage);
+        }
+
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:307]: Redundant new line.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 7]
```diff
@@ -296,6 +300,11 @@ private void reindexOneOrAllColumns(
                 throw CairoException.nonCritical().put(unsupportedColumnMessage);
             }
         }
+        //To validate if the table has any index or not
+        if(isIndexed) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:304]:
```suggestion
        if (isIndexed) {
```

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 8]
```diff
@@ -296,6 +300,11 @@ private void reindexOneOrAllColumns(
                 throw CairoException.nonCritical().put(unsupportedColumnMessage);
             }
         }
+        //To validate if the table has any index or not
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:303]: This check should be in the `if (columnIndex == REBUILD_ALL_COLUMNS)` block, under the loop.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 9]
```diff
@@ -147,7 +148,7 @@ abstract protected void doReindex(
     );
 
     protected abstract boolean isSupportedColumn(RecordMetadata metadata, int columnIndex);
-
+    //protected abstract boolean isSupportedTable(RecordMetadata metadata);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:151]: This line should be removed.

**Review by puzpuzpuz — COMMENTED** [review]
Left some comments, mostly around code style issues.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 10]
```diff
@@ -147,7 +148,6 @@ abstract protected void doReindex(
     );
 
     protected abstract boolean isSupportedColumn(RecordMetadata metadata, int columnIndex);
-
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:150]: This newline should be kept as it separates the methods.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 11]
```diff
@@ -281,6 +283,10 @@ private void reindexOneOrAllColumns(
                     );
                 }
             }
+            //To validate if the table has any index or not
+            if (isIndexed) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:287]: We definitely don't want to return an error if the table has indexes.
```suggestion
            if (!isIndexed) {
```

Comment (sreenath-tm) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java]: Will make the changes.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java (hunk 10 above)
Comment (sreenath-tm) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java]: The changes have been added.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java (hunk 5 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:262]: This one is still actual.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java [hunk 12]
```diff
@@ -268,6 +271,10 @@ private void reindexOneOrAllColumns(
                     );
                 }
             }
+            //To validate if the table has any index or not
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/RebuildColumnBase.java:274]: nit: this comment is redundant as the code is self-explaining.

Comment (sreenath-tm) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java]: The comment has been removed.

File: core/src/main/java/io/questdb/cairo/RebuildColumnBase.java (hunk 5 above)
Comment (sreenath-tm) [reply core/src/main/java/io/questdb/cairo/RebuildColumnBase.java]: Changes have been added.

**Review by puzpuzpuz — APPROVED** [review]
LGTM. Thanks for your contribution!
