### PR TITLE
fix(sql): overflow in materialized view refresh step calculation on large sample by interval

### LINKED ISSUE #6257: Overflow in materialized view refresh step calculation on large sample by interval
### To reproduce

Minimal reproducer:
```sql
create table x (ts timestamp) timestamp(ts) partition by day;
insert into x values('2000-01-01T12:00'),('2010-01-01T12:00'),('2020-01-01T12:00');
create materialized view x_1y as select ts, first(ts) as first_ts from x sample by 10y;
```

The view gets marked as invalid after the initial refresh with the `timestamp out of replace range` reason.

### QuestDB version:

9.1

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 24.04

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #6257

`SampleByIntervalIterator` got an overflow when calculating the high boundary on large SAMPLE BY intervals and relatively large step value. This is fixed by introducing a new `cairo.mat.view.max.refresh.step` configuration property (1y by default). The property defines maximum step interval after which refresh falls back to a single SAMPLE BY interval. Example: if refresh job calculates the step of 100 SAMPLE BY 2y intervals, after the check it will fall back to a single 2y interval to avoid overflow issues.

### CODE REVIEW

File: core/src/main/java/io/questdb/cairo/CairoConfiguration.java [hunk 1]
```diff
@@ -317,6 +317,8 @@ default IOURingFacade getIOURingFacade() {
 
     int getMatViewMaxRefreshRetries();
 
+    long getMatViewMaxRefreshStepUs();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/CairoConfiguration.java:320]: nit: why micros? Why not seconds or days? 
Do we practically need this configured, what is the situation where 1 year will not work?

File: core/src/main/java/io/questdb/cairo/mv/MatViewRefreshJob.java [hunk 2]
```diff
@@ -422,7 +422,16 @@ private RefreshContext findRefreshIntervals(
             final TimestampSampler timestampSampler = viewDefinition.getTimestampSampler();
             final long rowsPerBucket = estimateRowsPerBucket(driver, baseTableReader, timestampSampler.getApproxBucketSize());
             final int rowsPerQuery = configuration.getMatViewRowsPerQueryEstimate();
-            final int step = Math.max(1, (int) (rowsPerQuery / rowsPerBucket));
+            int step = Math.max(1, (int) (rowsPerQuery / rowsPerBucket));
+            try {
+                final long approxStepDuration = Math.multiplyExact(step, timestampSampler.getApproxBucketSize());
+                if (approxStepDuration > driver.fromMicros(configuration.getMatViewMaxRefreshStepUs())) {
+                    // the step is too large, fallback to step of a single SAMPLE BY interval
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/mv/MatViewRefreshJob.java]: Please add the reason why in the comment

File: core/src/main/java/io/questdb/cairo/CairoConfiguration.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/CairoConfiguration.java:320]: > why micros? Why not seconds or days?

Micros are convenient for the comparison done in the refresh job. The user can specify arbitrary time unit in the config file.

> Do we practically need this configured, what is the situation where 1 year will not work?

In some very niche cases like a sparse in the number of rows, but wide in time table configuring this value may be helpful. Other than that, no strong reason to have a config prop for it, but in principle we tend to introduce config props instead of hardcoded values when there is a small chance that the value may need to be changed as a workaround.

File: core/src/main/java/io/questdb/cairo/mv/MatViewRefreshJob.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/mv/MatViewRefreshJob.java]: Added the clarification in 71150d41bb1f5f6ce7babde07117ac9671c55453

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/mv/MatViewRefreshJob.java|8|10|80.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the snappy review!
