### PR TITLE
fix(sql): fix to_date function to accept varchar type

### LINKED ISSUE #4739: VARCHAR columns cannot be converted to Date with to_date
### To reproduce

1. Go to quest db web interface
2. Run the following commands in order:

``` sql
CREATE TABLE TEST (field varchar, ts TIMESTAMP) TIMESTAMP(ts);

INSERT INTO TEST VALUES ('1999-07-05', now());

SELECT * FROM TEST WHERE to_date(field, 'yyyy-MM-dd') = to_date('1999-07-05', 'yyyy-MM-dd');
```
3. This produces the error: 

unexpected argument for function: to_date. expected args: (STRING,STRING constant). actual args: (VARCHAR,STRING constant)

However when using the to_timestamp function, everything works so it seems like an inconcistency.

### QuestDB version:

Enterprise Ultimate 2.0.3

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04 lts (Docker)

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Gustav Hagland

### Affiliation:

Vermiculus

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ideoma**
fixes #4739

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 33 / 38 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToPgDateFunctionFactory.java|12|15|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java|21|23|91.30%|

File: core/src/main/java/io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+        public Function getArg() {
+            return arg;
+        }
+
+        @Override
+        public long getDate(Record rec) {
+            Utf8Sequence value = arg.getVarcharA(rec);
+            try {
+                if (value != null && value.isAscii()) {
+                    return dateFormat.parse(value.asAsciiCharSequence(), locale);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java:87]: This function won't work correctly with non-English (non-ASCII) `DateLocale`. We need to decode UTF-16 to UTF-8 when the sequence is not ASCII. It would be great to add a test around that.

File: core/src/main/java/io/questdb/griffin/engine/functions/date/VarcharToPgDateFunctionFactory.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+        @Override
+        public Function getArg() {
+            return arg;
+        }
+
+        @Override
+        public long getDate(Record rec) {
+            Utf8Sequence value = arg.getVarcharA(rec);
+            try {
+                if (value != null &&  value.isAscii()) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/date/VarcharToPgDateFunctionFactory.java:70]: nit: missing auto-formatting here
```suggestion
                if (value != null && value.isAscii()) {
```

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 33 / 38 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToPgDateFunctionFactory.java|12|15|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java|21|23|91.30%|

File: core/src/main/java/io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java (hunk 1 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java:90]: Thanks, I changed to handle non-en locale case

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 89 (80.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToTimestampVCFunctionFactory.java|16|24|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToPgDateFunctionFactory.java|12|15|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/VarcharToDateFunctionFactory.java|32|38|84.21%|
|:large_blue_circle:|io/questdb/std/datetime/DateLocale.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/ToStrDateFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/ToTimestampVCFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/ToDateFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/DateLocaleFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatFactory.java|1|1|100.00%|

**Review by puzpuzpuz — APPROVED** [review]
