### PR TITLE
fix(core): fix internal errors due to bad implicit casting

### LINKED ISSUE #6429: UnsupportedOperationException in RndDoubleArrayFunctionFactory
### To reproduce

Execute `select rnd_double_array(1, 0.1) from long_sequence(100);`

```
2025-11-21T15:05:44.200072Z E i.q.g.FunctionParser exception in function factory: 
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.functions.DoubleFunction.getLong(DoubleFunction.java:149)
	at io.questdb.griffin.engine.functions.rnd.RndDoubleArrayFunctionFactory.validateAndGetArg(RndDoubleArrayFunctionFactory.java:121)
	at io.questdb.griffin.engine.functions.rnd.RndDoubleArrayFunctionFactory.newInstance(RndDoubleArrayFunctionFactory.java:80)
	at io.questdb.griffin.FunctionParser.checkAndCreateFunction(FunctionParser.java:625)
	at io.questdb.griffin.FunctionParser.createFunction(FunctionParser.java:1201)
	at io.questdb.griffin.FunctionParser.visit(FunctionParser.java:436)
	at io.questdb.griffin.PostOrderTreeTraversalAlgo.traverse(PostOrderTreeTraversalAlgo.java:105)
	at io.questdb.griffin.FunctionParser.parseFunction(FunctionParser.java:330)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectVirtualWithSubQuery(SqlCodeGenerator.java:5223)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectVirtual(SqlCodeGenerator.java:5188)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:4544)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:4044)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:4032)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:641)
	at io.questdb.griffin.SqlCompilerImpl.generateSelectOneShot(SqlCompilerImpl.java:4346)
[...]
```

### QuestDB version:

9.2.0

### OS, in case of Docker specify Docker and the Host OS:

-

### File System, in case of Docker specify Host File System:

-

### Full Name:

Jaromir Hamala

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
This change fixes internal errors caused by the database being too lenient with type checking. 

Example no. 1 - default values for lead/lag window functions:
```sql
create table tab (ts TIMESTAMP, i long, d double) timestamp(ts);
insert into tab values (now(), 0, 0.0);
select lead(i, 1, d) over () from tab; -- note, using a `double` value as a default for `long` function
```

Example no. 2 - array access
```sql
CREATE TABLE tango AS (SELECT ARRAY[
   [ [ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9] ],
   [ [10, 11, 12], [13, 14, 15], [16, 17, 18] ],
   [ [19, 20, 21], [22, 23, 24], [25, 26, 27] ]
] arr from long_sequence(1));
SELECT arr[1, 3.0] subarr FROM tango;
```

Example no. 3 - rnd_double_array() SQL function:
```sql
select rnd_double_array(1, 0.0, 10) from long_sequence(5);
```

Before this change, all of the examples above would fail with an internal error. After the change, they fail gracefully and produce a sensible error message. 

#### Implementation details:
I suspect the main contributor to these bugs was poor naming: `ColumnType.isAssignableFrom(fromType, toType)` creates the impression that if it returns true for some combination of `TypeA` and `TypeB`, then it's legal to invoke `typeAFunction.getTypeB()`. Without adding any cast function. However, this is not the contract of `isAssignableFrom()`. This method merely indicates if it's possible to convert typeA and typeB at all, even it might requires a casting function. To prevent this confusion I renamed it from `isAssignableFrom()` to `isConvertibleFrom()` + added JavaDoc to explain the meaning. + I replaced the obviously bad invocations of  `isAssignableFrom()` with `isBuiltInWideningCast()` or `isSameOrBuiltInWideningCast()`. 

This PR also fixes another bug: `ColumnType.isBuiltInWideningCast()` indicated some types were convertible between each other without any casting function even that was not the case. Example: `ShortFunction.getTimestamp()` throws `UnsupportedOperationException` but `isBuiltInWideningCast(short, timestamp)` used to return true. This is no longer the case. There were 3 cases in total, where the function used to lie:

1. from BYTE to CHAR, DATE and TIMESTAMP
2. from SHORT to DATE and TIMESTAMP
2. from CHAR to DATE and TIMESTAMP

All these cases are now fixed. Insert used to rely on these bugs - since they would propagate to `isToSameOrWider()` and the insert machinery would create a casting function. After removing these cases from `isBuiltInWideningCast()`, I had to re-add them to `isImplicitParsingCast()` where they belongs anyway. It is a widening cast, but it is not built-in to base functions. 

There is one more change to `isBuiltInWideningCast()`: It used to indicate that STRING can be converted to numeric (which is the case), but it would not advertise that VARCHAR can be converted to numeric just as well. I suspect this could have led to creating unnecessary casting functions. So I fixed this too. 

I added a test validating that if `isBuiltInWideningCast()` returns true for some pair of types then we won't get the `UnsupportedOperationException` when we try to use them as such. I also tried to add the inverse test - that if `isBuiltInWideningCast()` returns `false` then types cannot be converted without a casting function, but this is more complicated - for example `BooleanFunction` has a function implementation of `getByte()`, but `isBuiltInWideningCast()` does not advertise it. I assume it's because it's not merely widening, but an actual conversion which should always be explicit. There are other cases like this, so I decided to just print them, instead of failing the test. Here is a list of these pairs:

```
  INFO: isBuiltInWideningCast(BOOLEAN, BYTE) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, SHORT) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, CHAR) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, INT) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, LONG) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, DATE) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, TIMESTAMP) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, FLOAT) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, DOUBLE) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, STRING) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, SYMBOL) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(BOOLEAN, VARCHAR) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(CHAR, BYTE) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(CHAR, STRING) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(CHAR, VARCHAR) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(TIMESTAMP, DATE) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(STRING, SYMBOL) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(STRING, IPv4) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(STRING, VARCHAR) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(SYMBOL, CHAR) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(SYMBOL, INT) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(SYMBOL, TIMESTAMP) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(SYMBOL, STRING) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(SYMBOL, VARCHAR) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(LONG256, LONG) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(unknown, GEOHASH) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(UUID, LONG128) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(GEOHASH, unknown) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(LONG128, UUID) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(VARCHAR, STRING) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(VARCHAR, SYMBOL) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(VARCHAR, IPv4) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(unknown, DECIMAL) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(unknown, unknown) = false, but getter works without UnsupportedOperationException
  INFO: isBuiltInWideningCast(DECIMAL, unknown) = false, but getter works without UnsupportedOperationException
```

fixes #6429

Considerations for reviewers: The bugs caused by accidental usage of `isAssignableFrom()` are directly connected to function signatures with vararg. Since without vararg `FunctionParser` creates casting functions as necessary and the target function receives arguments already converted to the expected type. However, functions accepting varargs are on their own - ideally, they should create implicit casting functions consistently with FunctionParser. That is NOT the case with this current state of the PR! This means even the fixed function will NOT perform implicit casting unless the casting is builtin. 

tandem: https://github.com/questdb/questdb-enterprise/pull/797

### CODE REVIEW

**Comment by jerrinot** [comment]
@coderabbitai - please review

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 34 / 34 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadDateFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadLongFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/LongSequenceFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndDoubleArrayFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagLongFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagDoubleFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagTimestampFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/DoubleArrayAccessFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadDoubleFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadTimestampFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagDateFunctionFactory.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
@jerrinot please send Ent tandem

**Comment by jerrinot** [comment]
@bluestreak01 done: https://github.com/questdb/questdb-enterprise/pull/797

**Comment by puzpuzpuz** [comment]
@jerrinot you're still unlucky:
```
[ERROR] Errors: 
[ERROR]   WindowFunctionTest.testLeadLagTimestampMixedDefaultValue:4294->AbstractCairoTest.assertMemoryLeak:1219->AbstractCairoTest.assertMemoryLeak:1236->AbstractCairoTest.lambda$assertMemoryLeak$9:1241->lambda$testLeadLagTimestampMixedDefaultValue$23:4302->AbstractCairoTest.assertQuery:1894->AbstractCairoTest.assertMemoryLeak:1219->AbstractCairoTest.assertMemoryLeak:1236->AbstractCairoTest.lambda$assertMemoryLeak$9:1241->AbstractCairoTest.lambda$assertQuery$16:1894->AbstractCairoTest.assertQueryFullFatNoLeakCheck:1960->AbstractCairoTest.assertQueryNoLeakCheck:1974 » Sql [30] default value must be can cast to timestamp

```

File: core/src/main/java/io/questdb/cairo/ColumnType.java [hunk 1]
```diff
@@ -443,22 +439,39 @@ public static boolean isBoolean(int columnType) {
...
+        final short toTag = tagOf(toType);
+
+        boolean isNumericWidening = (fromTag >= BYTE && toTag >= BYTE && toTag <= DOUBLE && fromTag < toTag)
+                && (fromTag != BYTE || (toTag != CHAR && toTag != DATE && toTag != TIMESTAMP)) // exception #1: cannot widen byte to char/temporal
+                && (fromTag != SHORT || (toTag != DATE && toTag != TIMESTAMP)) // exception #2: cannot widen short to temporal
+                && (fromTag != CHAR || (toTag != DATE && toTag != TIMESTAMP)); // exception #3: cannot widen char to temporal
+
+        return isNumericWidening
+                || fromTag == NULL
+                || (fromTag == CHAR && toTag == SHORT)  // Special: CHAR can converted to SHORT
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/ColumnType.java]:
```suggestion
                || (fromTag == CHAR && toTag == SHORT)  // Special: CHAR can be converted to SHORT
```

File: core/src/main/java/io/questdb/cairo/ColumnType.java [hunk 2]
```diff
@@ -443,22 +439,39 @@ public static boolean isBoolean(int columnType) {
...
+                || (fromTag == TIMESTAMP && toTag == LONG)  // Temporal to long
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/ColumnType.java]: nit: the two lines can be combined
```suggestion
                || ((fromTag == TIMESTAMP || fromTag == DATE) && toTag == LONG)  // Temporal to long
```

File: core/src/main/java/io/questdb/cairo/ColumnType.java [hunk 3]
```diff
@@ -746,11 +786,13 @@ private static boolean isIPv4Cast(int fromType, int toType) {
     private static boolean isImplicitParsingCast(int fromType, int toType) {
         final int toTag = tagOf(toType);
         return switch (fromType) {
-            case CHAR -> toTag == GEOBYTE && getGeoHashBits(toType) < 6;
+            case CHAR -> (toTag == GEOBYTE && getGeoHashBits(toType) < 6) || (toTag == DATE || toTag == TIMESTAMP);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/ColumnType.java:800]: Could you clarify when do we parse a char as a timestamp/date?

Comment (jerrinot) [reply core/src/main/java/io/questdb/cairo/ColumnType.java:800]: it's used here: https://github.com/questdb/questdb/blob/020ec80464f953dccbe9e5728675cf33a293b483/core/src/main/java/io/questdb/griffin/RecordToRowCopierUtils.java#L780

these tests rely on that: https://github.com/questdb/questdb/blob/f0ba2861f7e05d78c5acaee91012eeaf59dcd1a3/core/src/test/java/io/questdb/test/griffin/InsertCastTest.java#L251

the usefulness is limited, but we should not break it.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/ColumnType.java:800]: That `testCastCharTimestampFunc` test looks completely synthetic - let's keep it as is, but I don't think there is anyone relying on this cast.

**Comment by jerrinot** [comment]
@puzpuzpuz the failing test is now fixed

**Review by puzpuzpuz — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 39 / 40 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadDateFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadLongFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/LongSequenceFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndDoubleArrayFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagLongFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagDoubleFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagTimestampFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/array/DoubleArrayAccessFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadDoubleFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LeadTimestampFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagDateFunctionFactory.java|1|1|100.00%|
