### PR TITLE
fix(sql): fix the comparison refer to 'infinity'

### LINKED ISSUE #2112: Comparison between "infinities" isn't as expected
### Describe the bug

Consider such query:
```sql
select 'inf'::real = 'inf'::double precision  -- true in psql, regardless the precision of inf
select cast('Infinity' as float) = cast('Infinity' as double)  -- false in QDB, even when they are in the same type
```

the behavior of `inf = inf` is different from both Java (follows IEEE754):
```java
Float.POSITIVE_INFINITY == Double.POSITIVE_INFINITY  // true, vice versa for negative
```
and Postgres ("Ideally, QuestDB should behave as Postgres.")

### To reproduce

_No response_

### Expected Behavior

Should at least return true for the following examples:
```sql
select cast('Infinity' as float) = cast('Infinity' as double);
select cast('Infinity' as float) = cast('Infinity' as float);
select cast('Infinity' as double) = cast('Infinity' as double);
```
An alternative solution: provide some function like `is_infinity(float)` + `is_infinity(double)`

### Environment

- **QuestDB version**: 6.3

### Additional context

[IEEE 754](https://irem.univ-reunion.fr/IMG/pdf/ieee-754-2008.pdf): Ch 6.1 (pp. 34) may be helpful.

### PR DESCRIPTION
**Pull request by KevinChen16**
Fixes #2112
Adding special judgment of 'infinity' in SQL commands to make `Infinity = Infinity` and `-Infinity = -Infinity`, no matter in float or in double.

Updated changed files:
- `EqDoubleFunctionFactory.java`: adding judgment using equality besides using subtraction
- `EqDoubleFunctionFactoryTest.java`: adding tests for direct equal operation
- `CastTest.java`: adding tests for using infinity in SQL commands

### CODE REVIEW

**Comment by KevinChen16** [comment]
Hi @bluestreak01 and @jerrinot! Please let me know what I could improve to fix the bug. Thanks!

**Comment by KevinChen16** [comment]
Hi @marregui and @puzpuzpuz ! Please check and let me know what I could improve to fix the bug. Thanks!

**Comment by KevinChen16** [comment]
Really thanks to @jerrinot for helping me simplify the solution and adding an extra significant test!

**Review by jerrinot — APPROVED** [review]

File: core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public Func(Function left, Function right) {
         public boolean getBool(Record rec) {
             final double l = left.getDouble(rec);
             final double r = right.getDouble(rec);
-            return negated != (l != l && r != r || Math.abs(l - r) < 0.0000000001);
```
Comment (jerrinot) [inline core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java:112]: perhaps this would deserve a comment. it's not immediately obvious why `Math.abs(l - r) < 0.0000000001` is insufficient.

Comment (KevinChen16) [reply core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java:112]: OK, I'll add it now!

**Review by jerrinot — APPROVED** [review]

**Review by jerrinot — APPROVED** [review]

**Comment by KevinChen16** [comment]
Thanks, @bluestreak01!
