### PR TITLE
fix(build): disable chown by default in docker entrypoint

### LINKED ISSUE #3169: Get started  docker image changed owner of directory
### Describe the bug

Using the Get Started info for docker, I opened a terminal window and ran the docker command from here:  https://questdb.io/docs/get-started/docker/
```
docker run \
  -p 9000:9000 -p 9009:9009 -p 8812:8812 -p 9003:9003 \
  -v "$(pwd):/var/lib/questdb" \
  questdb/questdb:7.1
```

Starting getting errors after the image was downloaded and started to run.  Local user account became unusable as I started getting errors of 'Permission Denied'.

Killed terminal and switched users.  Most of the files in the user's in the home directory had been changed to be owned by user 10001.    

### To reproduce

Run this from your home directory:

``` 
docker run \
  -p 9000:9000 -p 9009:9009 -p 8812:8812 -p 9003:9003 \
  -v "$(pwd):/var/lib/questdb" \
  questdb/questdb:7.1
```

### Expected Behavior

I expected docker to start the database and allow me to connect to the web console.

### Environment

```markdown
- **QuestDB version**: 7.1
- **OS**: Ubuntu 22.10
- **Browser**: Firefox
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mariusgheorghies**
Fixes #3169

We will not find and chown by default, only when `FIND_AND_OWN_DIR` env variable is provided.
Also we will own only directories db/, conf/ and public/

### CODE REVIEW

**Comment by bluestreak01** [comment]
let me suggest the following:

- remove user creation (questdb:10001) from docker script
- allow docker container to run as root for users who do not want to read instructions
- create instructions on how to run docker questdb as a user, including using external directory
- create instructions on how to migrate docker container from being run as root to run as a user
- change Helm chart to run questdb as a user
- change cloud infra to run questdb as an externally specified user (rather than relying on docker container creating a user)

File: core/docker-entrypoint.sh [hunk 1]
```diff
@@ -4,12 +4,62 @@ export QDB_PACKAGE=${QDB_PACKAGE:-docker}
...
+
+
+If you want to run QuestDB as root, you can add the RUN_AS_ROOT environment variable when running questdb. 
+For example, you can use the command:
+  docker run -it -v /local-questdb-path:/var/lib/questdb -e RUN_AS_ROOT=true questdb/questdb
+
+EOF
+
+
+if [ -z "${LOCALDIRS:-}" ]
```
Comment (bluestreak01) [inline core/docker-entrypoint.sh:39]: what is `LOCALDIRS` ? Can we add a comment why we need this and what is the intent of ths branch?

File: core/docker-entrypoint.sh [hunk 2]
```diff
@@ -37,9 +87,12 @@ fi
...
-    find_and_own_dir ${QUESTDB_DATA_DIR}
+    find_and_own_dir $(id -u questdb) $(id -g questdb)
     exec gosu questdb "$@"
 fi
 
-echo "Running as $(id -un) user"
-exec "$@"
\ No newline at end of file
+if [ "$(id -u)" != '0' ] ; then
+    find_files_and_dirs_not_owned_by_user $(id -u 2>/dev/null) $(id -g 2>/dev/null)
```
Comment (bluestreak01) [inline core/docker-entrypoint.sh:95]: can we do `id -u` and `id -g` once, give the value a name?

File: core/docker-entrypoint.sh [hunk 3]
```diff
@@ -37,9 +87,12 @@ fi
 
 if [ "$(id -u)" = '0' ] && [ "${QUESTDB_DATA_DIR%/}" != "/root/.questdb" ] && [ "$RUN_AS_ROOT" = "false" ] ; then
     echo "Running as questdb user"
-    find_and_own_dir ${QUESTDB_DATA_DIR}
+    find_and_own_dir $(id -u questdb) $(id -g questdb)
```
Comment (bluestreak01) [inline core/docker-entrypoint.sh:90]: could you have a look at clickhouse entry point, it flows better: https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/entrypoint.sh

Comment (bluestreak01) [reply core/docker-entrypoint.sh:90]: it would be good to define UID and GID we use for the whole thing at the top of the script and then do things systematically from there. For example clickhouse have explicit `DO_CHOWN` flag, which i think is a good idea.

File: core/docker-entrypoint.sh [hunk 4]
```diff
@@ -4,12 +4,62 @@ export QDB_PACKAGE=${QDB_PACKAGE:-docker}
 
 QUESTDB_DATA_DIR=${QUESTDB_DATA_DIR:-"/var/lib/questdb"}
 IGNORE_DATA_ROOT_MOUNT_CHECK=${IGNORE_DATA_ROOT_MOUNT_CHECK:-"false"}
-IGNORE_FIND_AND_OWN_DIR=${IGNORE_FIND_AND_OWN_DIR:-"false"}
+FIND_AND_OWN_DIR=${FIND_AND_OWN_DIR:-"false"}
```
Comment (bluestreak01) [inline core/docker-entrypoint.sh:7]: `DO_CHOWN` may be a better name?

Comment (mariusgheorghies) [reply core/docker-entrypoint.sh:7]: we also have `FIND_AND_OWN_DIR`, maybe i should move it before i call `find_and_own_dir` and not inside the function
