### PR TITLE
fix(core): fix results returned in wrong order from parallel filter query

### LINKED ISSUE #2513: Flaky testParallelStressMultipleThreadsMultipleWorkersPositiveLimitJitDisabled
### Describe the bug

Possible bug in async offload:

```
2022-09-09T13:13:31.9157982Z 2022-09-09T13:13:31.882773Z I i.q.t.t.TestUtils cleaned [worker=1]
2022-09-09T13:13:31.9829710Z java.lang.AssertionError: expected:<v
2022-09-09T13:13:31.9830600Z 3394168647660478011
2022-09-09T13:13:31.9831163Z 4086802474270249591
2022-09-09T13:13:31.9831645Z 3958193676455060057
2022-09-09T13:13:31.9832130Z 3619114107112892010
2022-09-09T13:13:31.9832691Z 3705833798044144433
2022-09-09T13:13:31.9833167Z 4238042693748641409
2022-09-09T13:13:31.9833705Z 3518554007419864093
2022-09-09T13:13:31.9834721Z 4014104627539596639
2022-09-09T13:13:31.9835293Z 3393210801760647293
2022-09-09T13:13:31.9835869Z 4099611147050818391
2022-09-09T13:13:31.9836421Z > but was:<v
2022-09-09T13:13:31.9836991Z 3394168647660478011
2022-09-09T13:13:31.9837565Z 4086802474270249591
2022-09-09T13:13:31.9838133Z 3958193676455060057
2022-09-09T13:13:31.9838715Z 3619114107112892010
2022-09-09T13:13:31.9839281Z 3705833798044144433
2022-09-09T13:13:31.9839854Z 4238042693748641409
2022-09-09T13:13:31.9840421Z 3518554007419864093
2022-09-09T13:13:31.9841433Z 4014104627539596639
2022-09-09T13:13:31.9842011Z 3393210801760647293
2022-09-09T13:13:31.9842577Z 3944678179613436885
2022-09-09T13:13:31.9843094Z >
2022-09-09T13:13:31.9843707Z 	at org.junit.Assert.fail(Assert.java:89)
2022-09-09T13:13:31.9844454Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2022-09-09T13:13:31.9845213Z 	at org.junit.Assert.assertEquals(Assert.java:120)
2022-09-09T13:13:31.9846023Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:331)
2022-09-09T13:13:31.9846875Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:309)
2022-09-09T13:13:31.9847764Z 	at io.questdb.griffin.AbstractGriffinTest.assertCursor(AbstractGriffinTest.java:145)
2022-09-09T13:13:31.9848667Z 	at io.questdb.griffin.AsyncOffloadTest.assertCursor(AsyncOffloadTest.java:266)
2022-09-09T13:13:31.9850071Z 	at io.questdb.griffin.AsyncOffloadTest.assertQuery(AsyncOffloadTest.java:233)
2022-09-09T13:13:31.9851035Z 	at io.questdb.griffin.AsyncOffloadTest.lambda$testParallelStress$1(AsyncOffloadTest.java:379)
```

```
2022-09-09T13:13:32.1135092Z 2022-09-09T13:13:32.086369Z E i.q.TestListener ***** Test Failed *****io.questdb.griffin.AsyncOffloadTest.testParallelStressMultipleThreadsMultipleWorkersPositiveLimitJitDisabled : 
2022-09-09T13:13:32.1136532Z java.lang.AssertionError: expected:<0> but was:<1>
2022-09-09T13:13:32.1137280Z 	at org.junit.Assert.fail(Assert.java:89)
2022-09-09T13:13:32.1138034Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2022-09-09T13:13:32.1138806Z 	at org.junit.Assert.assertEquals(Assert.java:647)
2022-09-09T13:13:32.1139590Z 	at org.junit.Assert.assertEquals(Assert.java:633)
2022-09-09T13:13:32.1140457Z 	at io.questdb.griffin.AsyncOffloadTest.lambda$testParallelStress$2(AsyncOffloadTest.java:394)
2022-09-09T13:13:32.1141312Z 	at io.questdb.test.tools.TestUtils.execute(TestUtils.java:851)
2022-09-09T13:13:32.1142120Z 	at io.questdb.test.tools.TestUtils.execute(TestUtils.java:867)
2022-09-09T13:13:32.1143022Z 	at io.questdb.griffin.AsyncOffloadTest.testParallelStress(AsyncOffloadTest.java:347)
2022-09-09T13:13:32.1144124Z 	at io.questdb.griffin.AsyncOffloadTest.testParallelStressMultipleThreadsMultipleWorkersPositiveLimitJitDisabled(AsyncOffloadTest.java:168)
2022-09-09T13:13:32.1145281Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-09-09T13:13:32.1146168Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-09-09T13:13:32.1147128Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-09T13:13:32.1147949Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-09-09T13:13:32.1148803Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-09-09T13:13:32.1149745Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-09-09T13:13:32.1150674Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-09-09T13:13:32.1151679Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-09-09T13:13:32.1152709Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-09-09T13:13:32.1153652Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-09-09T13:13:32.1154464Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-09-09T13:13:32.1155322Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2022-09-09T13:13:32.1156323Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2022-09-09T13:13:32.1157246Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-09-09T13:13:32.1158005Z 	at java.lang.Thread.run(Thread.java:829)
```

[86.txt.zip](https://github.com/questdb/questdb/files/9535895/86.txt.zip)

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.5.3-SNAPSHOT
- **OS**: ARM
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2513

The problem was three-fold:
* `AsyncFilteredRecordCursor` wasn't calling `frameSequence.done()` in `topTo()`.
* Dynamic sequence addition/removal in `PubSub` could lead to out-of-sync barriers. See `testConcurrentFanOutAsyncOffloadPattern` for the reproducer.
* Our sequences (at least, the MP/MC ones) aren't sequentially consistent, so our `await()` code that was relying on the reducer counter value and the `cursor == -1` check led to unconsumed page frame tasks left in the queue.

The problem showed in this particular test since we cancel the frame sequence when the limit is reached. When we do that, reducer jobs don't run the filter, but immediately call `seq.done(cursor)`. I was able to reproduce the bug reliable with `taskset -c 0,2` to use two non-HT sibling cores. 500 iterations were enough to reproduce it reliably on Linux x86-64.

As a follow-up, we could add [jcstress-based](https://github.com/openjdk/jcstress) tests for our sequences and fix them.

As another follow-up, we could get rid of the reducer counter and reduce up to the number of not yet collected tasks in [this loop](https://github.com/questdb/questdb/blob/8ea125b88d13f006f47976d3eb2f6e452712816c/core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java#L425-L433).

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 59 / 59 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|43|43|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 59 / 59 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|43|43|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 63 / 63 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|43|43|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 63 / 63 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|43|43|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 36 / 36 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 36 / 36 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 35 / 35 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 42 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|24|24|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 42 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|24|24|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 42 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|24|24|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

File: core/src/test/java/io/questdb/mp/ConcurrentTest.java [hunk 1]
```diff
@@ -77,6 +78,127 @@ public void testConcurrentFanOutAnd() {
...
+            int owner;
+        }
+
+        final int capacity = 2;
+        final int collectorThreads = 2;
+        final int reducerThreads = 2;
+        final int itemsToDispatch = 8;
+        final int iterations = 100;
+
+        final RingQueue<Item> queue = new RingQueue<Item>(() -> new Item(), capacity);
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/mp/ConcurrentTest.java:95]: nit: there is intellij warning on this line, lambda can be simplified

Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/mp/ConcurrentTest.java:95]: Yes, but this breaks JDK 8 build.

**Comment by bluestreak01** [comment]
other than the comment above - the PR looks great, thank you!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 42 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameSequence.java|24|24|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/mp/FanOut.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/AbstractSSequence.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|2|2|100.00%|

File: core/src/test/java/io/questdb/mp/ConcurrentTest.java (hunk 1 above)
Comment (bluestreak01) [reply core/src/test/java/io/questdb/mp/ConcurrentTest.java:95]: indeed, it was an issue with my IDE config
