### PR TITLE
fix(sql): fix segmentation fault in non-keyed max(int) vectorised implementation

### LINKED ISSUE #3905: SIGSEV maxInt_AVX2 with insert into <table> select max(id) + 1, ... from <table>
### Describe the bug

Hi there,

First of all, great work with QuestDB :+1:  I am really impressed with the performance.

Unfortunately, I encounter a (90%) reproducible SIGSEV when running the following algorithm in a tight loop with many entities. 
. I try to insert hierarchical entities with an emulation of an autoincrement id column. (Code abbreviated)

The crash happens repeatedly at entity counter 5120. When the crash does not happen, corrupted ids after 5120 are present in the table.

```python
import psycopg2

connection = psycopg2.connect(...)
cursor = connection.cursor()

def create_if_not_exists(cursor, entity):
    run = entity.parent
    while run and run.database_id is None:
        create_if_not_exists(run)    
        run = run.parent
    
    parent_id = entity.parent.database_id if run.parent else None

    while entity.database_id is None:
        cursor.execute("""select id from "table" where name = %s and parent_id = %s""", (entity.name, parent_id))
        exists = cursor.fetchone()
        if exists is None:
            cursor.execute("""insert into "table" (id, name, parent_id) select max(id) + 1, %s, %s  from "table" """, (entity.name, parent_id))
        else:
            entity.database_id = exists[0]
```

```
#  SIGSEGV (0xb) at pc=0x00007f8c787cdd80, pid=1, tid=45
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# C  [libquestdb4990927995383399878.so+0x75d80]  maxInt_AVX2(int*, long)+0x40
#
# Core dump will be written. Default location: /var/lib/questdb/core
#
# An error report file with more information is saved as:
# /var/lib/questdb/db/hs_err_pid+1.log
Compiled method (n/a)  174872 3842     n 0       io.questdb.std.Vect::maxInt (native)
 total in heap  [0x00007f8c9cc8e310,0x00007f8c9cc8e688] = 888
 relocation     [0x00007f8c9cc8e470,0x00007f8c9cc8e4a0] = 48
 main code      [0x00007f8c9cc8e4a0,0x00007f8c9cc8e680] = 480
 oops           [0x00007f8c9cc8e680,0x00007f8c9cc8e688] = 8
Compiled method (n/a)  174874 3842     n 0       io.questdb.std.Vect::maxInt (native)
 total in heap  [0x00007f8c9cc8e310,0x00007f8c9cc8e688] = 888
 relocation     [0x00007f8c9cc8e470,0x00007f8c9cc8e4a0] = 48
 main code      [0x00007f8c9cc8e4a0,0x00007f8c9cc8e680] = 480
 oops           [0x00007f8c9cc8e680,0x00007f8c9cc8e688] = 8
```

Let me know if you need anything else.

Best regards and keep up the good work,

Christian

### To reproduce

Run the above python code.

### Expected Behavior

Entites are written to the database with consecutive ids. No crash happens.

### Environment

```markdown
- **QuestDB version**:7.3.3
- **OS**: Ubuntu 22.04
- **Browser**: Firefox
- **Architecture**: linux/amd64 [AVX2,8, 64 bits, 12 processors]
```

### Additional context

[hs_err_pid+1.log](https://github.com/questdb/questdb/files/13226170/hs_err_pid%2B1.log)

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #3905

Segmentation fault was due to bad iteration bounds (end - 7)  on int data block vs AVX2 vector size (16 ints).

### CODE REVIEW

File: core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java [hunk 1]
```diff
@@ -1893,36 +1893,6 @@ public void testBindVariableDropLastPartitionListByWeekHigherPrecision() throws
 
     @Test
     public void testBindVariableDropLastPartitionListWithWeekPrecision() throws Exception {
-        final ConnectionAwareRunnable runnable = (connection, binary) -> {
```
Comment (jerrinot) [inline core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java:1896]: removed accidentally?

**Review by jerrinot — APPROVED** [review]
good catch! can be merge after updating all native libs. (let me know if you need help with that)

File: core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java (hunk 1 above)
Comment (jerrinot) [reply core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java:1896]: it would be good to create a GH issue rather than removing it entirely.

**Review by jerrinot — APPROVED** [review]
