### PR TITLE
fix(griffin): fix fd leak in tables() function

### LINKED ISSUE #2265: Version 6.4.1 failed to drop table on windows system
### Describe the bug

log : Table remove failed

### To reproduce

CREATE TABLE my_table(ts timestamp,col int) timestamp(ts);

DROP TABLE 'my_table';

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.4.1
- **OS**:Windows 10 21H2
- **Browser**: Chrome 103.0.5060.53 (64-bit)
```

### Additional context

2022-06-24T07:53:43.448957Z I i.q.c.h.p.JsonQueryProcessorState [1748] exec [q='select build']
2022-06-24T07:53:43.449013Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-3, sql=select build]
2022-06-24T07:53:43.449034Z I i.q.c.h.p.JsonQueryProcessorState [1748] execute-cached [skip: 0, stop: 1000]
2022-06-24T07:53:43.449257Z I i.q.c.h.p.JsonQueryProcessorState [1748] timings [compiler: 0, count: 0, execute: 337600, q=`select build`]
2022-06-24T07:53:43.449375Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=1748, lastRequestBytesSent=444, nCompletedRequests=11, totalBytesSent=338207]
2022-06-24T07:53:43.449514Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-3, sql=select build]
2022-06-24T07:53:43.450021Z I i.q.c.h.p.JsonQueryProcessorState [1636] exec [q='drop table 'my_table'']
2022-06-24T07:53:43.450046Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=drop table 'my_table']
2022-06-24T07:53:43.451466Z I i.q.c.CairoEngine locked [table=`my_table`, thread=14]
2022-06-24T07:53:43.451733Z E i.q.c.CairoEngine remove failed [tableName='my_table', error=5]
2022-06-24T07:53:43.452076Z I i.q.c.CairoEngine unlocked [table=`my_table`]
2022-06-24T07:53:43.452104Z E i.q.c.h.p.JsonQueryProcessorState [1636] internal error [q=`drop table 'my_table'`, ex=
io.questdb.cairo.CairoException: [5] Table remove failed
]
2022-06-24T07:53:43.452371Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=1636, lastRequestBytesSent=283, nCompletedRequests=13, totalBytesSent=4411639]

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2265 by closing/clearing last allocated table metadata when closing tables() cursor, so there should be no more open files in table directory preventing deletion (in Windows at least) .

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

File: core/src/main/java/io/questdb/cairo/TableReaderMetadata.java [hunk 1]
```diff
@@ -152,12 +152,15 @@ public void dumpTo(MemoryMA mem) {
 
     @Override
     public void close() {
-        // TableReaderMetadata is re-usable after close, don't assign nulls
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/TableReaderMetadata.java:155]: nit: I'd keep this comment since it's still relevant.

File: core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java [hunk 2]
```diff
@@ -126,6 +126,7 @@ private class TableListRecordCursor implements RecordCursor {
             @Override
             public void close() {
                 findPtr = ff.findClose(findPtr);
+                metaReader.clear();//release FD of last table on the list
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java:129]: nit: we could call `close()` here instead of introducing `clear()` method since it has more or less the same effect.

**Review by puzpuzpuz — APPROVED** [review]

File: core/src/main/java/io/questdb/cairo/TableReaderMetadata.java (hunk 1 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/cairo/TableReaderMetadata.java]: restored

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|
