### PR TITLE
fix(http): fix unhandled error when importing CSV to table with dropped and recreated columns

### LINKED ISSUE #3174: Unhandled error in CSV import on a table with recreated column
### Describe the bug

1. Use the following CSV:
```csv
col_i,col_l
42,42
```
2. Import it into a fresh QuestDB instance:
```bash
curl -F data=@test.csv 'http://localhost:9000/imp'
```
3. Re-create `col_i` column:
```sql
alter table 'test.csv' drop column col_i;
alter table 'test.csv' add column col_i long;
```
4. Run the import once again:
```bash
curl -F data=@test.csv 'http://localhost:9000/imp'
```

As a result, the import "hangs" with the following unhandled error:
```
2023-04-11T07:33:52.427154Z I i.q.c.p.WriterPool >> [table=`test.csv`, thread=22]
2023-04-11T07:33:52.427281Z I i.q.c.t.CairoTextWriter cannot update metadata attributes o3MaxLag and maxUncommittedRows when the table exists and parameter overwrite is false
2023-04-11T07:33:52.429286Z C server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@cecf639, ex=
io.questdb.cairo.CairoException: [-100] Duplicate column [name=col_i]
]
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 7.1
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #3174

### CODE REVIEW

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java [hunk 1]
```diff
@@ -31,7 +31,9 @@ public class GenericRecordMetadata extends AbstractRecordMetadata {
 
     public static void copyColumns(RecordMetadata from, GenericRecordMetadata to) {
         for (int i = 0, n = from.getColumnCount(); i < n; i++) {
-            to.add(from.getColumnMetadata(i));
+            if (from.hasColumn(i)) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:34]: I was curious why deleted columns be in the metadata in the first place. Even if delete columns are there, nothing tells the downstream code not to do this check. 

Sure enough, removing this condition does not fail any test on Windows. Running on Mac

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:34]: > Sure enough, removing this condition does not fail any test on Windows. Running on Mac

I'll add a test to `IODispatcherTest` to fix that.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java]: Added the test in 0d5022612cef60d9846ae5cb293cf0635e8b8c45

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java [hunk 2]
```diff
@@ -29,6 +29,20 @@
...
 
+    // Does not copy deleted columns.
+    public static GenericRecordMetadata cleanCopyOf(RecordMetadata that) {
+        if (that != null) {
+            if (that instanceof GenericRecordMetadata) {
+                return (GenericRecordMetadata) that;
+            }
+            GenericRecordMetadata metadata = new GenericRecordMetadata();
+            copyNonDeletedColumns(that, metadata);
+            metadata.setTimestampIndex(that.getTimestampIndex());
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:40]: Shouldn't timestamp index be shifted if there is a deleted column before it?

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:40]: All indexes are preserved as is, so no shift is necessary. `TextLoader` uses them to insert rows directly on the table writer, so the indexes must match.

Comment (ideoma) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:40]: it should use`getWriterIndex` to write.

Comment (ideoma) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:40]: We probably need a test that imports CSV in a table where a column before the designated timestamp is dropped.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 33 (93.94%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/GenericRecordMetadata.java|15|17|88.24%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextLoaderCompletedState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:40]: > it should use`getWriterIndex` to write.

This doesn't sound like a non-risky bugfix to me as it would touch quite a few classes, so I'd better do this refactoring in a separate PR.

File: core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java [hunk 3]
```diff
@@ -2677,6 +2680,64 @@ public void testUtf8Tab() throws Exception {
...
+                        csv,
+                        1024,
+                        expected,
+                        "{\"columnCount\":3,\"columns\":[{\"index\":0,\"name\":\"col_a\",\"type\":\"unknown\"},{\"index\":1,\"name\":\"col_b\",\"type\":\"LONG\"},{\"index\":2,\"name\":\"col_a\",\"type\":\"LONG\"}],\"timestampIndex\":-1}",
+                        2,
+                        2
+                );
+                Assert.fail();
+            } catch (CairoException e) {
+                TestUtils.assertContains(e.getFlyweightMessage(), "cannot match columns by their positions, please add headers or provide schema [index=0]");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java:2736]: This test should upload without error. After all, the alters the table has 2 columns of type long, int. Uploading CSV of

```
1,2
1,2
```
without header still matches the column

File: core/src/main/java/io/questdb/cutlass/http/processors/TextLoaderCompletedState.java [hunk 4]
```diff
@@ -39,7 +39,7 @@ public void copyState(TextLoader textLoader) {
         // in order to release TableWriter back to the Engine
         this.writtenLineCount = textLoader.getWrittenLineCount();
         this.metadata = textLoader.getMetadata() != null
-                ? GenericRecordMetadata.copyOf(textLoader.getMetadata())
+                ? GenericRecordMetadata.cleanCopyOf(textLoader.getMetadata())
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cutlass/http/processors/TextLoaderCompletedState.java:42]: I can change this to `GenericRecordMetadata.copyDense(textLoader.getMetadata())`
and all the tests still pass.

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java (hunk 2 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:40]: I changed to `copyDense` in `TextLoaderCompletedState` and tests still pass. `copyDense` shifts the timestamp. As far as I can see, this `metadata` copy is only used to print the output table in the upload response and is not involved in writing to the table.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java]: Moved to dense metadata in 8d9648b31595614da8344512d70fdbe984ec78f3

File: core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java (hunk 3 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java]: The behavior and the tests were updated in 8d9648b31595614da8344512d70fdbe984ec78f3

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 117 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|40|40|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextLoaderCompletedState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 119 / 119 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|40|40|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextLoaderCompletedState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/GenericRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctKeyRecordCursorFactory.java|1|1|100.00%|

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java [hunk 5]
```diff
@@ -29,7 +29,11 @@
 
 public class GenericRecordMetadata extends AbstractRecordMetadata {
 
-    public static void copyColumns(RecordMetadata from, GenericRecordMetadata to) {
+    /**
+     * This method will throw when called on table writer metadata in case of deleted and re-created columns.
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:33]: Outdated comment? I don't see any `throw` in here.

File: core/src/main/java/io/questdb/cutlass/http/processors/TextLoaderCompletedState.java [hunk 6]
```diff
@@ -38,11 +37,9 @@ public void copyState(TextLoader textLoader) {
         // Some values are come from TableWriter and has to be copied
         // in order to release TableWriter back to the Engine
         this.writtenLineCount = textLoader.getWrittenLineCount();
-        this.metadata = textLoader.getMetadata() != null
-                ? GenericRecordMetadata.copyOf(textLoader.getMetadata())
-                : null;
         // Some values are safe to get from TextLoader
         this.textLoader = textLoader;
+        this.metadata = textLoader.getMetadata();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cutlass/http/processors/TextLoaderCompletedState.java:42]: Why no copy? The copy is taken to release the writer in case of sending response is slow so that the writer is not blocked for long. When the writer is released it can go back to the pool and the metadata reference here can belong to a closed writer.

File: core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java [hunk 7]
```diff
@@ -701,6 +701,23 @@ public long read(int fd, long buf, long len, long offset) {
         });
     }
 
+    @Test
+    public void testImportFileFailsWhenImportingAfterColumnWasRecreatedNoHeader() throws Exception {
```
Comment (ideoma) [inline core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java:705]: Does this import fail? Looks like the test name is not in sync with the body.

File: core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java [hunk 8]
```diff
@@ -783,6 +792,91 @@ private int getTaskCount() {
...
+        }
+
+        // remap index is only needed to adjust names and types
+        // workers will import data into temp tables without remapping
+        final IntList remapIndex = new IntList();
+        remapIndex.ensureCapacity(types.size());
+        for (int i = 0, n = types.size(); i < n; i++) {
+            final int columnIndex = metadata.getColumnIndexQuiet(names.getQuick(i));
+            final int idx = columnIndex > -1 ? columnIndex : i; // check for strict match ?
+            remapIndex.set(i, idx);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java:819]: Why you don't use `witerIndex` for the column here?

File: core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java (hunk 7 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java]: It's leftover. Fixed in 1d392ba9985cad70c9e7dfc59ac035ddfcc8ec0c

File: core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java (hunk 8 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java:819]: That's because unlike in `TestLoader`, parallel importer uses remap index only to adjust names and types. It's not used to interact with `TableWriter`.

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java (hunk 5 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java:33]: This place uses this method to copy metadata with deleted columns. And it doesn't throw because `add` is overridden.

https://github.com/questdb/questdb/blob/62bb9a05340656f9c3e93847907c45b0bd2bed5c/core/src/test/java/io/questdb/test/griffin/wal/fuzz/FuzzTransactionGenerator.java#L211

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 117 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|40|40|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextLoaderCompletedState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|3|3|100.00%|

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java (hunk 5 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java]: The fact that `add` method is overridden in tests doesn't make `copyColumns` less error-prone. We have a bug around this method to be fixed by this PR and there is no guarantee that future code won't introduce something similar. I decided to leave a comment as a caution.

Improved the comment and the method name in e69608491f03597eeadca6df220be2f5a2ffd207

**Review by ideoma — APPROVED** [review]

File: core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java (hunk 1 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java]: outdated

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 117 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|40|40|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextLoaderCompletedState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|3|3|100.00%|

**Review by ideoma — APPROVED** [review]
