### PR TITLE
fix(griffin): rnd_str(iiii) ignores null rate setting

### LINKED ISSUE #1898: rnd_str returns null value even if null rate set to zero
### Describe the bug

I may misunderstood the [documentation](https://questdb.io/docs/reference/function/random-value-generator/#rnd_str), but `rnd_str` should return no null data if the null value position’s value is set to 0. So `SELECT rnd_str(16, 10, 10, 0) FROM long_sequence(8);` should return 8 items without any string missing.

If that’s the case, then it seems I found a bug 🐛.

406CCF25-29DD-4F65-BD80-2FB4C48D193E

### To reproduce

1. Run `SELECT rnd_str(16, 10, 10, 0) FROM long_sequence(8);`

### Expected Behavior

No null values returned.

### Environment

```markdown
- **QuestDB version**: 6.2 (latest)
- **OS**: macOS - Docker
- **Browser**: Firefox Developer Edition (latest)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by glasstiger**
Fix for rnd_str(iiii) ignoring null rate settings.
Also fixes a bug where the offset used for accessing the randomly generated strings in memory was off.
Added new config to set limit for mem used by random functions.

Closes #1898

### CODE REVIEW

**Review by bziobrowski — APPROVED** [review]
Looks good to me . 
Noticed that 'A' character doesn't appear in generated strings . 
Could it be due to this code in Rnd ?

    public void nextChars(CharSink sink, int len) {
        for (int i = 0; i < len; i++) {
            sink.put((char) (nextPositiveInt() % 25 + 66));  
        }
    }

I guess it should use the following to include 'A' :

            sink.put((char) (nextPositiveInt() % 26 + 65));

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 30 (76.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|21|25|84.00%|

**Comment by glasstiger** [comment]
> > Note: Please add a limit on max memory this function is able to use .
> 
> If we do so, we need to apply the same limit to `rnd_bin(lli)` and, probably, to `rnd_symbol(iiii)`.

will check

**Comment by glasstiger** [comment]
> 



> Looks good to me . Noticed that 'A' character doesn't appear in generated strings . Could it be due to this code in Rnd ?
> 
> ```
> public void nextChars(CharSink sink, int len) {
>     for (int i = 0; i < len; i++) {
>         sink.put((char) (nextPositiveInt() % 25 + 66));  
>     }
> }
> ```
> 
> I guess it should use the following to include 'A' :
> 
> ```
>         sink.put((char) (nextPositiveInt() % 26 + 65));  
> ```

That is a good catch but i am wondering if this is intentional.
I mean it seems to be in sync with other methods like nextByte(), nextBytes(), nextChar(), nextString().
```
    public char nextChar() {
        return (char) (nextPositiveInt() % 25 + 'B');
    }
```
Here it looks like the author knew that the range will start with 'B' instead of 'A'.
Moreover, if we change this I am not sure how many tests would need to be updated one by one.

I guess our options are to leave it as it is and accept that random bytes/chars/strings exclude 'A' for some mythical mysterious reason or rename these methods to something else like nextChars25() and add nextChar() which includes 'A' as well.

**Comment by bziobrowski** [comment]
@bluestreak01  Do you know something about this  'mythical mysterious reason_' ?

**Comment by bluestreak01** [comment]
I do, a tonne of tests depend on this function. Its a known issue, but if you change this to 'A' - it has to be done in absolute isolation. E.g. not a single other change to production code.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 30 (76.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|21|25|84.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java [hunk 1]
```diff
@@ -94,12 +85,18 @@ public void close() {
 
         @Override
         public CharSequence getStr(Record rec) {
+            if (nullRate > 0 && (rnd.nextInt() % nullRate) == 1) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java:88]: minor: why not `nextPositiveInt()`? Mod over negative will be negative and never 1, meaning effective `nullRate` will be halved.

Comment (glasstiger) [reply core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java]: > minor: why not `nextPositiveInt()`? Mod over negative will be negative and never 1, meaning effective `nullRate` will be halved.

found this too, fixed it. thank you.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 90 (84.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|16|22|72.73%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndSymbolFunctionFactory.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringMemory.java|41|44|93.18%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 90 (84.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|16|22|72.73%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndSymbolFunctionFactory.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringMemory.java|41|44|93.18%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 91 (86.81%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|18|22|81.82%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndSymbolFunctionFactory.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringMemory.java|42|45|93.33%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|

File: core/src/test/java/io/questdb/cairo/AbstractCairoTest.java [hunk 2]
```diff
@@ -69,6 +69,8 @@
     protected static int binaryEncodingMaxLength = -1;
     protected static CharSequence defaultMapType;
     protected static int pageFrameMaxSize = -1;
+    protected static int rndFunctionMemoryPageSize = -1;
```
Comment (bziobrowski) [inline core/src/test/java/io/questdb/cairo/AbstractCairoTest.java:72]: tiny case issue - should be rndFunctionMemory**M**axPages

File: core/src/test/resources/server.conf [hunk 3]
```diff
@@ -122,6 +122,9 @@ cairo.writer.alter.max.wait.timeout.micro=7770001
 cairo.writer.tick.rows.count=15
 cairo.writer.command.queue.capacity=16
```
Comment (bziobrowski) [inline core/src/test/resources/server.conf:124]: I think these two deserve a comment ! :)

File: core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+        if (lo == hi) {
+            initFixedLength(rnd);
+        } else {
+            initVariableLength(rnd);
+        }
+    }
+
+    private void initFixedLength(Rnd rnd) {
+        for (int i = 0; i < count; i++) {
+            final long o = strMem.putStr(rnd.nextChars(lo));
```
Comment (bziobrowski) [inline core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java:106]: Another tiny thing - Vm.getStorageLength(lo) can be moved outside loop and made final .

File: core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+    RndStringMemory(String signature, int count, int lo, int hi, int position, CairoConfiguration configuration) throws SqlException {
+        this.count = count;
+        this.lo = lo;
+        this.hi = hi;
+
+        final int pageSize = configuration.getRndFunctionMemoryPageSize();
+        final int maxPages = configuration.getRndFunctionMemoryMaxPages();
+        final long actualMem = (long) maxPages * pageSize;
+        // check against worst case, the highest possible mem usage
+        final long hiMem = count * (Vm.getStorageLength(hi) + Long.BYTES);
```
Comment (bziobrowski) [inline core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java:53]: Please consider adding reference to cairo.rnd.memory.* entries to error message to help user fix the problem if settings are too low .

File: core/src/test/java/io/questdb/cairo/AbstractCairoTest.java (hunk 2 above)
Comment (glasstiger) [reply core/src/test/java/io/questdb/cairo/AbstractCairoTest.java:72]: > tiny case issue - should be rndFunctionMemory**M**axPages

fixed

File: core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java (hunk 4 above)
Comment (glasstiger) [reply core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java:107]: > Another tiny thing - Vm.getStorageLength(lo) can be moved outside loop and made final .

good catch, changed it

File: core/src/test/resources/server.conf (hunk 3 above)
Comment (glasstiger) [reply core/src/test/resources/server.conf:124]: > I think these two deserve a comment ! :)

it is really just test config but added a comment, just in case

File: core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java (hunk 5 above)
Comment (glasstiger) [reply core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java:53]: > Please consider adding reference to cairo.rnd.memory.* entries to error message to help user fix the problem if settings are too low .

not a bad idea but i have not really seen examples of this.
it seems to me that we usually keep the error messages short and do not provide lengthy explanations or hints how to fix the issue.
might be something we want to do in the future.
anyone else has a firm opinion on this topic?

however, what i am sure about is that a description should make it into our doc.
the config part and the page talks about rnd functions should explain what these settings are.
will update the doc definitely.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 80 / 92 (86.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|18|22|81.82%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndSymbolFunctionFactory.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringMemory.java|43|46|93.48%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java (hunk 5 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringMemory.java:53]: Doc-wise I agree . 
As for error message - it would be more useful to the user if we either explained what to change OR added some kind of  
error code .

**Review by bziobrowski — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 80 / 92 (86.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringRndListFunctionFactory.java|18|22|81.82%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndSymbolFunctionFactory.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndStringMemory.java|43|46|93.48%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
