### PR TITLE
fix(sql): fix order-by priority in case of duplicate column names

### LINKED ISSUE #2295: Incorrect ORDER BY priority
### Describe the bug

_No response_

### To reproduce

1. On Demo run 
```
(select * from 'trades' limit 100)
order by timestamp, timestamp desc
```
2. Observe timestamp order is DESC

### Expected Behavior

Order by should first by first clause then second if the items within first are equal. The query should return data sorted in ASC order by timestamp

### Environment

```markdown
- **QuestDB version**:6.4.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
fixes #2295

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 1]
```diff
@@ -768,7 +768,12 @@ private void createOrderHash(QueryModel model) {
         if (n > 0) {
             final IntList orderByDirection = model.getOrderByDirection();
             for (int i = 0; i < n; i++) {
```
Comment (bziobrowski) [inline core/src/main/java/io/questdb/griffin/SqlOptimiser.java:770]: It doesn't apply to qdb (yet) because order by accepts literals only but if sorting by expressions/functions becomes available this check might produce bad results for queries like : 

select * from t order by rnd_int() asc, rnd_int() desc;

Comment (jerrinot) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java:770]: that's a good realization! 

I suspect once qdb supports expressions in the ORDER BY clause then the whole concept with a map `<column_name, direction>` will have to be re-evaluated. 

(fwiw: in this very example, it [wouldn't be easy](https://xkcd.com/221/) to prove it's broken :) but yes, there could be another example where it's more noticeable)

File: core/src/test/java/io/questdb/griffin/OrderByAdviceTest.java [hunk 2]
```diff
@@ -1186,4 +1186,18 @@ public void testDistinctWithOrderByAnotherColumn() throws Exception {
             TestUtils.assertContains(e.getFlyweightMessage(), "ORDER BY expressions must appear in select list.");
         }
     }
+
```
Comment (bziobrowski) [inline core/src/test/java/io/questdb/griffin/OrderByAdviceTest.java:1189]: It would be good to also  test it with :
- order by column_position
- column aliases 
- different column name case and/or quoted identifiers

**Review by bziobrowski — APPROVED** [review]

**Comment by jerrinot** [comment]
@bziobrowski thanks for the review, I will add the tests you suggested!

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
more tests please

File: core/src/test/java/io/questdb/griffin/OrderByAdviceTest.java [hunk 3]
```diff
@@ -1186,4 +1186,111 @@ public void testDistinctWithOrderByAnotherColumn() throws Exception {
...
+                        " x % 3 b" +
+                        " from long_sequence(9)" +
+                        ")",
+                null,
+                true, true, true);
+    }
+
+    @Test
+    public void testOrderByPriority_columnAliases() throws Exception {
+        assertQuery("aliased\n1\n2\n3\n4\n5\n6\n7\n8\n9\n",
```
Comment (bziobrowski) [inline core/src/test/java/io/questdb/griffin/OrderByAdviceTest.java:1234]: It's also possible to make several aliases for the same column and use them in order by,e.g. 
```sql
select a as a1, a as a2 from x order by a1 asc, a2 desc 
```
but I don't think it matters much here because different literals won't clashm only produce unnecessary comparisons .

**Review by bziobrowski — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]
