### PR TITLE
fix(sql): fix empty result on second run of query with group by and limit

### LINKED ISSUE #3750: Bug with GROUP BY
### Describe the bug

Queries with a GROUP BY statement do not behave as expected.

I have tested two cases with GROUP BY as describe in "To reproduce".

IMPORTANT!
This scenario works as expected in version 7.0.1, but started to fails from version 7.1 upwards.

### To reproduce

create table if not exists test(id uuid);
insert into test(id) select rnd_uuid4() from long_sequence(3);

-- the query returns the expected result on the first execution, but returns no records on subsequent executions
-- modifying the SQL string by adding a whitespace somewhere, returns the records again the first time and fails again
-- subsequent times
select  id
from    test
group by id
limit   10;

-----------------------

create table if not exists test(id int);
insert into test(id) select rnd_int() from long_sequence(3);

--- grouping on an integer field doesn't even return a result on the first execution
select  id
from    test
group by id;

### Expected Behavior

Receive the expected result every time

### Environment

```markdown
- **QuestDB version**: 7.3.2 (Docker)
- **OS**: Ubuntu 22.04.3 LTS in WSL2 on Windows 10 21H2
- **Browser**: Chrome Version 116.0.5845.188 (Official Build) (64-bit)
```

### Additional context

I suppose QuestDB computes a hash of the string representation of the SQL query and performs a cache lookup that returns an empty resultset while the data exists (at least in the table storage).

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #3750 

Fixes: 
- bug in group by cursor size re-caculation where cursor.size() method relied on element that wasn't cleared on close() method call 
- bug in handling of group by with empty aggregate list that caused it to skip processing data, e.g. `select id from users group by id`
-

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 1]
```diff
@@ -3364,6 +3364,20 @@ && isHourKeyword(columnExpr.token)
                         tempVaf.getQuick(i).pushValueTypes(arrayColumnTypes);
                     }
 
+                    if (tempVaf.size() == 0) {// select distinct case 
+                        ArrayColumnTypes columnTypes = new ArrayColumnTypes();
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:3368]: creating new list seems unnecessary, if i make this change:
image

tests pass also

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|7|100.00%|
