### PR TITLE
fix(sql): NPE in latest by with symbol filter

### LINKED ISSUE #1578: NPE on `LATEST BY` SQL query
### Describe the bug

```
021-11-16T15:14:40.367857Z E i.q.c.h.p.JsonQueryProcessorState [49] Uh-oh. Error!
java.lang.NullPointerException
	at io.questdb.griffin.engine.table.AbstractDeferredTreeSetRecordCursorFactory.getCursorInstance(AbstractDeferredTreeSetRecordCursorFactory.java:93)
	at io.questdb.griffin.engine.table.LatestByValuesIndexedFilteredRecordCursorFactory.getCursorInstance(LatestByValuesIndexedFilteredRecordCursorFactory.java:83)
	at io.questdb.griffin.engine.table.LatestByValuesIndexedFilteredRecordCursorFactory.getCursorInstance(LatestByValuesIndexedFilteredRecordCursorFactory.java:39)
	at io.questdb.griffin.engine.table.AbstractDataFrameRecordCursorFactory.getCursor(AbstractDataFrameRecordCursorFactory.java:47)
	at io.questdb.griffin.engine.table.AbstractDeferredTreeSetRecordCursorFactory.getCursor(AbstractDeferredTreeSetRecordCursorFactory.java:39)
	at io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory.getCursor(GroupByRecordCursorFactory.java:89)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:583)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:376)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeCachedSelect(JsonQueryProcessor.java:323)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:134)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:183)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:564)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:242)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:89)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:93)
	at io.questdb.mp.Worker.run(Worker.java:111)

2021-11-16T15:14:40.368140Z I i.q.c.h.HttpConnectionContext kicked out [fd=49]
2021-11-16T15:14:40.368162Z I http-server scheduling disconnect [fd=49, reason=5]
2021-11-16T15:14:40.368185Z I http-server disconnected [ip=127.0.0.1, fd=49, src=queue]
2021-11-16T15:14:40.368258Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-4, sql=SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member, metric WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap')]
```

### To reproduce

Run these SQL queries 1 by 1:
```
CREATE TABLE IF NOT EXISTS 'test_latest_by' (time TIMESTAMP, metric SYMBOL CAPACITY 1024 index, value LONG, unit SYMBOL, mc_member SYMBOL index) TIMESTAMP(time) PARTITION BY DAY;

INSERT INTO test_latest_by VALUES(now(), 'memory.committedHeap', 200, 'bytes', '1');
INSERT INTO test_latest_by VALUES(now(), 'memory.usedHeap', 100, 'bytes', '1');
INSERT INTO test_latest_by VALUES(now(), 'memory.maxHeap', 300, 'bytes', '1');

INSERT INTO test_latest_by VALUES(now(), 'memory.committedHeap', 200, 'bytes', '3');
INSERT INTO test_latest_by VALUES(now(), 'memory.usedHeap', 100, 'bytes', '3');
INSERT INTO test_latest_by VALUES(now(), 'memory.maxHeap', 300, 'bytes', '3');

INSERT INTO test_latest_by VALUES(now(), 'memory.committedHeap', 200, 'bytes', '2');
INSERT INTO test_latest_by VALUES(now(), 'memory.usedHeap', 100, 'bytes', '2');
INSERT INTO test_latest_by VALUES(now(), 'memory.maxHeap', 300, 'bytes', '2');

SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member, metric WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap');
```

### Expected Behavior

No NPE and some results like this returned:
-  memory.usedHeap=200
-  memory.committedHeap=400

### Environment

```markdown
- **QuestDB version**: 6.1.1-jdk8
- **OS**: Mac OS Monterey 12.0.1
- **Browser**: Safari
```

### Additional context

`SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap')` this query throws the following exception

```
2021-11-16T15:35:55.761063Z E i.q.c.h.p.JsonQueryProcessorState [49] internal error [q=`SELECT metric, sum(value) FROM test_latest_by LATEST BY mc_member WHERE mc_member IN('1', '2') AND metric IN('memory.usedHeap', 'memory.committedHeap')`, ex=
io.questdb.cairo.CairoException: [0] Not indexed: value
]
```

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #1578

Includes fixes for the following bugs:
* `LatestBy*` cursors were making `filter.getBool()` calls before the filter was initialized leading to NPEs.
* Some of the filtered `LatestBy*` cursors were using select column index instead of the table one when obtaining a `BitmapIndexReader`. This led to `Not indexed: n` errors on some queries.
* `LatestByValuesIndexedFilteredRecordCursor` had an `if (cursor.hasNext())` instead of `while (cursor.hasNext())` leading to filtering being applied only to the very first record returned from `indexReader.getCursor()`.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|2|2|100.00%|

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java [hunk 1]
```diff
@@ -4262,6 +4262,87 @@ public void testLatestByAllValueIndexedColumn() throws Exception {
...
+                "  value long) \n" +
+                "  timestamp(ts) partition by day");
+    }
+
+    private void testLatestByFilteredBySymbolIn(String ddl) throws Exception {
+        assertMemoryLeak(() -> {
+            compiler.compile(ddl, sqlExecutionContext);
+
+            executeInsert("insert into x values ('2021-11-17T17:35:01.000000Z', 'node1', 'cpu', 100)");
+            executeInsert("insert into x values ('2021-11-17T17:35:01.000000Z', 'node2', 'cpu', 75)");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4300]: Would be good to have here several lines with `node2, cpu` to check that latest is taken.

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java [hunk 2]
```diff
@@ -4262,6 +4262,87 @@ public void testLatestByAllValueIndexedColumn() throws Exception {
...
+                    "  ts timestamp,\n" +
+                    "  node symbol,\n" +
+                    "  metric symbol,\n" +
+                    "  value long) \n" +
+                    "  timestamp(ts) partition by day", sqlExecutionContext);
+
+            executeInsert("insert into x values ('2021-11-17T17:35:01.000000Z', 'node1', 'cpu', 100)");
+            executeInsert("insert into x values ('2021-11-17T17:35:01.000000Z', 'node2', 'cpu', 75)");
+            executeInsert("insert into x values ('2021-11-17T17:35:02.000000Z', 'node1', 'memory', 2000)");
+            executeInsert("insert into x values ('2021-11-17T17:35:02.000000Z', 'node2', 'memory', 3000)");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4331]: Would be good to have several lines of each combination with different timestamps to check that latest by chooses last line.

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java [hunk 3]
```diff
@@ -4262,6 +4262,87 @@ public void testLatestByAllValueIndexedColumn() throws Exception {
...
+            TestUtils.assertSql(
+                    compiler,
+                    sqlExecutionContext,
+                    "select * from x latest by node, metric \n" +
+                            "where node in ('node2') and metric in ('cpu', 'memory')",
+                    sink,
+                    "ts\tnode\tmetric\tvalue\n" +
+                            "2021-11-17T17:35:01.000000Z\tnode2\tcpu\t75\n" +
+                            "2021-11-17T17:35:02.000000Z\tnode2\tmemory\t3000\n"
+            );
```
Comment (ideoma) [inline core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4342]: can you add indexes on symbols one by one and repeat the assertion please?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|2|2|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java [hunk 4]
```diff
@@ -59,8 +60,9 @@ public void toTop() {
     }
 
     @Override
-    protected void buildTreeMap(SqlExecutionContext executionContext) {
+    protected void buildTreeMap(SqlExecutionContext executionContext) throws SqlException {
         prepare();
+        filter.init(this, executionContext);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:65]: Why 
```
int frameColumnIndex = columnIndexes.getQuick(columnIndex);
```
is not needed here?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|2|2|100.00%|

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4300]: Good idea. Done in 265fd52e4de65e3d66e076a791ea44c0452b272b

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4331]: Done in 265fd52e4de65e3d66e076a791ea44c0452b272b

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java (hunk 3 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4342]: Done in 265fd52e4de65e3d66e076a791ea44c0452b272b

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java]: This one should contain the link: 265fd52e4de65e3d66e076a791ea44c0452b272b

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java (hunk 4 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:65]: That's because we need to initialize the filter before accessing it (see the very first bug in the PR description).

If you comment out this line of code and revert the change in `LatestByValuesFilteredRecordCursorFactory`, you'd get such an NPE in `testLatestByFilteredBySymbolInNoIndexes`:
```
java.lang.NullPointerException
	at io.questdb/io.questdb.griffin.engine.functions.bool.InSymbolFunctionFactory$Func.getBool(InSymbolFunctionFactory.java:110)
	at io.questdb/io.questdb.griffin.engine.table.LatestByValuesFilteredRecordCursor.buildTreeMap(LatestByValuesFilteredRecordCursor.java:76)
	at io.questdb/io.questdb.griffin.engine.table.AbstractDescendingRecordListCursor.of(AbstractDescendingRecordListCursor.java:73)
	at io.questdb/io.questdb.griffin.engine.table.AbstractTreeSetRecordCursorFactory.getCursorInstance(AbstractTreeSetRecordCursorFactory.java:60)
	at io.questdb/io.questdb.griffin.engine.table.AbstractDeferredTreeSetRecordCursorFactory.getCursorInstance(AbstractDeferredTreeSetRecordCursorFactory.java:103)
	at io.questdb/io.questdb.griffin.engine.table.LatestByValuesFilteredRecordCursorFactory.getCursorInstance(LatestByValuesFilteredRecordCursorFactory.java:83)
	at io.questdb/io.questdb.griffin.engine.table.LatestByValuesFilteredRecordCursorFactory.getCursorInstance(LatestByValuesFilteredRecordCursorFactory.java:41)
	at io.questdb/io.questdb.griffin.engine.table.AbstractDataFrameRecordCursorFactory.getCursor(AbstractDataFrameRecordCursorFactory.java:47)
	at io.questdb/io.questdb.griffin.engine.table.AbstractDeferredTreeSetRecordCursorFactory.getCursor(AbstractDeferredTreeSetRecordCursorFactory.java:39)
	at io.questdb/io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory.getCursor(GroupByRecordCursorFactory.java:89)
	at io.questdb/io.questdb.test.tools.TestUtils.printSql(TestUtils.java:674)
	at io.questdb/io.questdb.test.tools.TestUtils.assertSql(TestUtils.java:436)
	at io.questdb/io.questdb.griffin.SqlCodeGeneratorTest.lambda$testLatestByFilteredBySymbolIn$48(SqlCodeGeneratorTest.java:4328)
```

What happens here is that `InSymbolFunction` tries to access its private test function which wasn't yet initialized. We didn't see this NPE before because there were no tests for this latest by + filter combination.

Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:65]: I don't disagree with filter init. My question is why column index is not remapped here.

File: core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java [hunk 5]
```diff
@@ -4262,6 +4262,157 @@ public void testLatestByAllValueIndexedColumn() throws Exception {
...
+                "  timestamp(ts) partition by day");
+    }
+
+    private void testLatestBySelectAllFilteredBySymbolIn(String ddl) throws Exception {
+        assertMemoryLeak(() -> {
+            compiler.compile(ddl, sqlExecutionContext);
+
+            executeInsert("insert into x values ('2021-11-17T17:35:01.000000Z', 'node1', 'cpu', 1)");
+            executeInsert("insert into x values ('2021-11-17T17:35:02.000000Z', 'node1', 'cpu', 10)");
+            executeInsert("insert into x values ('2021-11-17T17:35:03.000000Z', 'node1', 'cpu', 100)");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java:4386]: would be super if you mark lines taken by select with some sort of comments

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|2|2|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java (hunk 4 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:65]: Sorry, I misunderstood the question. Let me check that.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|2|2|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java (hunk 4 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java:65]: This method deals with `TableReaderSelectedColumnRecord` class which remaps select column indexes to table ones. So, in the `recordA.getInt(columnIndex)` call there is a `deferenceColumn()` method call which does the remapping. That's why we don't need to do extra index remapping here.

**Review by ideoma — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the review!
