### PR TITLE
fix(sql): fix left join with complex expressions

### LINKED ISSUE #2321: Join expressions are ignored for equality operator
### Describe the bug

When (inner or outer) joining tables using equality operator like 

```sql
select * 
from tabA
join tabB on expr1 = expr2 
```

expressions are ignored and raw columns are used .
Workaround : 

```sql
join on expr1 - expr2 = 0
```

### To reproduce

```sql
create table prices (
  tstmp timestamp,
  value double  
) timestamp(tstmp) partition by year;

insert into prices 
select cast(x*3600000000 as timestamp), x
from long_sequence(3) ;

selecT * from prices; 
--returns
--1970-01-01T01:00:00.000000Z 1
--1970-01-01T02:00:00.000000Z 2
--1970-01-01T03:00:00.000000Z 3

select *
from prices p1
left join prices p2 on p2.tstmp  = (p1.tstmp * -1);
--result result as if joining on p2.tstmp = p1.tstmp

select *
from prices p1
left join prices p2 on p2.tstmp  = dateadd('h', -1, p1.tstmp );
--same result

select *
from prices p1
left join prices p2 on p2.value  = p1.value * -1;
--result result as if joining on p2.value = p1.value

select *
from prices p1
join prices p2 on p2.value/p2.value = p1.value ; 
--same result


select *
from prices p1
left join prices p2 on p2.value  < -p1.value;
--returns no result

select *
from prices p1
left join prices p2 on p2.value/p1.value = 0;
--returns no result

select *
from prices p1
left join prices p2 on p2.tstmp  - dateadd('h', -1, p1.tstmp ) = 0;
--returns correct result
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.4.3/master
- **OS**: Windows 
- **Browser**: Chrome
```

### Additional context

_No response_

### LINKED ISSUE #2329: Column resolution fails in complex join conditions
### Describe the bug

If query contains a with clause qdb sometimes fails to resolve columns in complex expressions . 
Column is properly resolved if it's accessed directly , not through WITH 'view' .

### To reproduce

```sql
CREATE TABLE 'prices' (ts TIMESTAMP, price DOUBLE) timestamp (ts);

with qwe as (select * from prices),
  select p1.ts, p2.price
  from qwe p1
  left join qwe p2 on p2.ts - p1.ts = 0 or 
                        p2.ts - p1.ts + 3600000000 = 0 or 
                        p2.ts - p1.ts + 2*3600000000 = 0 or 
                        p2.ts - p1.ts + 3*3600000000 = 0 or 
                        p2.ts - p1.ts + 4*3600000000 = 0 or 
                        p2.ts - p1.ts + 5*3600000000 = 0 or 
                        p2.ts - p1.ts + 6*3600000000 = 0 or 
                        p2.ts - p1.ts + 7*3600000000 = 0 or 
                        p2.ts - p1.ts + 8*3600000000 = 0 or 
                        p2.ts - p1.ts + 9*3600000000 = 0 
  where p1.ts between '1970-01-01T01:00:00.000000Z' and '1971-01-01T01:00:00.000000Z' 
  and   p2.ts between '1970-01-01T01:00:00.000000Z' and '1971-01-01T01:00:00.000000Z' 
  limit 10000
```
### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.4.3
- **OS**: Windows
- **Browser**: Chrome
```

### Additional context

_No response_

### LINKED ISSUE #2684: Join fails with 'invalid column'
### Describe the bug

SQL query using joins with CTEs failing with 'invalid column' error 

### To reproduce

**1 run sql**
```
create table table_b (
  customerid string,
  runid int,
  actualstartts timestamp,
  actualendts timestamp 
) timestamp(actualstartts) partition by month
```

**2 run sql**
`insert into table_b values ( 'cust1',  100, '2022-10-25T00:15:00.000000Z', '2022-10-25T00:45:00.000000Z' )
`
**3 run sql**
`insert into table_b values ( 'cust1',  101, '2022-10-25T00:30:00.000000Z', '2022-10-25T01:00:00.000000Z' )
`
**4 run sql using cte (fails with the invalid column: T.actualendts)**
```
WITH cte_minutetimesamples AS
(
  -- get 1 sample for every 5 minute period in the day starting 2022-10-25
    ( 
      select 
      x
      , CAST ( CAST( to_timestamp('2022-10-25T00:00:00.000000', 'yyyy-MM-ddTHH:mm:ss.SSSUUU') AS LONG) + (x - 1) * 5 * 60 * 1000000L as timestamp ) fromts
      , CAST ( CAST( to_timestamp('2022-10-25T00:04:59.999999', 'yyyy-MM-ddTHH:mm:ss.SSSUUU') AS LONG) + (x - 1) * 5 * 60 * 1000000L as timestamp ) tots
        from long_sequence( 1 * 24 * 60 / 5 )
    ) timestamp(fromts) 
) 
,
cte_jobtimings AS 
(
  (
    SELECT 
    customerid, runid, actualstartts, actualendts
FROM table_b
ORDER BY actualstartts
  ) timestamp(actualstartts)
)
--select * from cte_jobtimings



   select S.x, S.fromts, T.customerid, count(*) cnt
   FROM cte_minutetimesamples S
    JOIN cte_jobtimings T
    ON
     (S.fromts between T.actualstartts and T.actualendts ) 
     OR
     (S.tots between T.actualstartts and T.actualendts )  

```
_Note: removing Z.customerid from the final select to use select S.x, S.fromts,count(*) cnt and the query will not fail. So it seems to be related to referencing columns from more than one table in the query_

**5 running the following sql using a direct table query (succeeds)**
```
WITH cte_minutetimesamples AS
(
    ( 
      select 
      x
      , CAST ( CAST( to_timestamp('2022-10-25T00:00:00.000000', 'yyyy-MM-ddTHH:mm:ss.SSSUUU') AS LONG) + (x - 1) * 5 * 60 * 1000000L as timestamp ) fromts
      , CAST ( CAST( to_timestamp('2022-10-25T00:04:59.999999', 'yyyy-MM-ddTHH:mm:ss.SSSUUU') AS LONG) + (x - 1) * 5 * 60 * 1000000L as timestamp ) tots
        from long_sequence( 1 * 24 * 60 / 5 )
    ) timestamp(fromts) 
) 


select S.x, S.fromts, T.customerid, count(*) cnt 
    FROM cte_minutetimesamples S
    JOIN table_b T
    ON
     (S.fromts between T.actualstartts and T.actualendts ) 
     OR
     (S.tots between T.actualstartts and T.actualendts )  
```

### Expected Behavior

The query should not error

### Environment

```markdown
- **QuestDB version**: 6.5.4
- **OS**: windows
- **Browser**: edge
```

### Additional context

In my use case i need to query an existing questdb table to generate additional calculated columns, before joining that data with other tables. Therefore a simple query from an existing table isnt a suitable workaround in our case..

### LINKED ISSUE #2686: LEFT Join not returning expected results with non trivial join expression
### Describe the bug

Left join works ok when the ON expression is of the form 
  ON a.value = b.value

However, it fails for other match expressions
such as 
  ON a.value >= b.value - 1 AND a.value <= b,value + 1

or
  ON a.value between b.value - 1 AND b,value + 1

### To reproduce

**1 Setup Test Data**

```
create table table_1 (
  ts timestamp,
  name string,
  age int,
  member boolean
) timestamp(ts) PARTITION by month

insert into table_1 values ( '2022-10-25T01:00:00.000000Z', 'alice',  60, True )
insert into table_1 values ( '2022-10-25T02:00:00.000000Z', 'peter',  58, False )
insert into table_1 values ( '2022-10-25T03:00:00.000000Z', 'david',  21, True )

create table table_2 (
  ts timestamp,
  name string,
  age int,
  address string
) timestamp(ts) PARTITION by month


insert into table_2 values ( '2022-10-25T01:00:00.000000Z', 'alice',  60,  '1 Glebe St' )
insert into table_2 values ( '2022-10-25T02:00:00.000000Z', 'peter',  58, '1 Broon St' )
```

**2 Run SQL using simple ON expr = expr**

```
select a.name, a.age, a.member, b.address, a.ts
from table_1 as a 
left join table_2 as b 
   on a.ts = b.ts 
```

_2 Result - Three rows returned as expected, including the row for david, 21, true, null (address)_

**3 Run SQL using more complex ON expr using between**

```
select a.name, a.age, b.address, a.ts, dateadd('m', -1, b.ts), dateadd('m', 1, b.ts) 
from table_1 as a 
left join table_2 as b 
   on a.ts between dateadd('m', -1, b.ts)  and dateadd('m', 1, b.ts) 
```

_3 Result - Only Two rows returned, Should be three, excludes the row for david, 21, true, null (address)_

**4 Run SQL using more complex ON expr mimicking between**

```
select a.name, a.age, b.address, a.ts, dateadd('m', -1, b.ts), dateadd('m', 1, b.ts) 
from table_1 as a 
left join table_2 as b 
   on a.ts >=  dateadd('m', -1, b.ts)  and a.ts <= dateadd('m', 1, b.ts) 
```

_4 Result - Only Two rows returned, Should be three, excludes the row for david, 21, true, null (address)_

### Expected Behavior

LEFT join should handle the match logic for fairly basic match expressions

### Environment

```markdown
- **QuestDB version**: 6.5.4
- **OS**: Windows
- **Browser**: Edge
```

### Additional context

For my use case i need to perform left joins on two tables and match timestamps using the timestamp between logic on the join expression.

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2329 
Fixes #2686 
Fixes #2321 
Fixes #2684 

Changes : 
- maintain integrity of outer join clauses (prevents pushing predicates in and out of them). Apart from left also lt, asof and splice are outer joins .
- prevent pushing predicates down to right table of left join (pushing to left table is fine)
- return error on RIGHT or FULL join (only left is implemented and it was misleading because right and full was interpreted as table alias )
- return error on OUTER JOIN . LEFT JOIN or LEFT OUTER JOIN should be used . 
- detect when function is used in equality join predicate and push it outside join context 
- fix column resolution in equality join predicates 
- implement nested loop and hash left joins with filter
- return error on complex join conditions in LT, ASOF and SPLICE joins . So far they've been either pushed outside  or interpreted badly (returning wrong results in both cases) so it's just about making issue more visible. 

Example : 
```sql
SELECT * 
FROM a 
ASOF JOIN b ON (a.x < b.x);
```
used to be executed as  
```sql
SELECT * 
FROM a 
ASOF JOIN b 
WHERE (a.x < b.x);
```
The former syntax is now rejected and join predicates utilizing functions or operators other than '='  should be moved to where clause - at least until LT, ASOF and SPLICE join implementations are reworked to handle arbitrary expressions .

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 353 / 411 (85.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|88|112|78.57%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|55|65|84.62%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|100|115|86.96%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|63|68|92.65%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|31|33|93.94%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 338 / 382 (88.48%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|81|97|83.51%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|55|65|84.62%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|92|101|91.09%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|63|68|92.65%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|31|33|93.94%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 363 / 379 (95.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|60|65|92.31%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|63|68|92.65%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|97|99|97.98%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|94|96|97.92%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|33|33|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlParser.java [hunk 1]
```diff
@@ -154,6 +154,13 @@ private void assertNotDot(GenericLexer lexer, CharSequence tok) throws SqlExcept
         }
     }
 
+    //prevent full/right from being used as table aliases
+    private void checkSupportedJoinType(GenericLexer lexer, CharSequence tok) throws SqlException {
+        if (tok != null && (Chars.equalsIgnoreCase(tok, "full") || Chars.equalsIgnoreCase(tok, "right"))) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlParser.java:159]: we should have `SqlKeywords` for these comparisons

File: core/src/test/java/io/questdb/griffin/AsOfJoinTest.java [hunk 2]
```diff
@@ -266,7 +266,7 @@ public void testAsOfJoinNoAliasDuplication() throws Exception {
                             "FROM (select b.bid b, b.ts timebid from bids b) b \n" +
                             "    ASOF JOIN\n" +
                             "(select a.ask a, a.ts timeask from asks a) a\n" +
-                            "    ON (b.timebid != a.timeask);";
+                            "WHERE (b.timebid != a.timeask);";
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: why do we need to change tests ? is `ON` no-longer valid syntax ?

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java [hunk 3]
```diff
@@ -257,7 +257,12 @@ public void testAsOfJoinSubQuery() throws Exception {
...
+                "select-choose c.customerId customerId, e.blah blah, e.lastName lastName, e.employeeId employeeId, e.timestamp timestamp, o.customerId customerId1 from " +
+                        "(select [customerId] from customers c " +
+                        "asof join select [blah, lastName, employeeId, timestamp] from " +
+                        "(select-virtual ['1' blah, lastName, employeeId, timestamp] '1' blah, lastName, employeeId, timestamp from " +
+                        "(select [lastName, employeeId, timestamp] from employees) " +
+                        "order by lastName) e on e.employeeId = c.customerId post-join-where e.lastName = 'x' and e.blah = 'y' join select [customerId] from orders o on o.customerId = c.customerId) c",
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/griffin/SqlParserTest.java:265]: this looks like a new bug to me `e.lastName = 'x' and e.blah = 'y'` should not be executed post-join, those are pre-join filters

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
there are side-effects that do not look right

File: core/src/test/java/io/questdb/griffin/AsOfJoinTest.java (hunk 2 above)
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: ON works but not for arbitrary expressions . 
Such conditions were treated as inner join and pushed elsewhere , e.g. post-join or parent where clause which wasn't correct because asof is a left join .
Implementing asof with arbitrary expressions would require many more changes (e.g. scanning slave cursors backwards or resetting it for each master item) so this piece only makes the limitations more visible .

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java [hunk 4]
```diff
@@ -193,7 +193,7 @@ public void testAsOfJoinOrder() throws Exception {
...
     public void testAsOfJoinOuterWhereClause() throws Exception {
         assertQuery(
-                "select-choose trade_time, quote_time, trade_price, trade_size, quote_price, quote_size from (select-choose [trade.ts trade_time, book.ts quote_time, trade.price trade_price, trade.size trade_size, book.price quote_price, book.size quote_size] trade.ts trade_time, book.ts quote_time, trade.price trade_price, trade.size trade_size, book.price quote_price, book.size quote_size from (select [ts, price, size, sym] from trade asof join select [ts, price, size, sym] from book on book.sym = trade.sym post-join-where book.price != NaN))",
+                "select-choose trade_time, quote_time, trade_price, trade_size, quote_price, quote_size from (select-choose [trade.ts trade_time, book.ts quote_time, trade.price trade_price, trade.size trade_size, book.price quote_price, book.size quote_size] trade.ts trade_time, book.ts quote_time, trade.price trade_price, trade.size trade_size, book.price quote_price, book.size quote_size from (select [ts, price, size, sym] from trade asof join select [ts, price, size, sym] from book post-join-where trade.sym = book.sym and book.price != NaN))",
```
[the remark this answers is not in the document]
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:196]: Yes, where predicates shouldn't be pushed to left join conditions . 
It would be a keyed join if trade.sym = book.sym appeared in ON clause .

File: core/src/test/java/io/questdb/griffin/AsOfJoinTest.java (hunk 2 above)
Comment (bluestreak01) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: is expression "arbitrary" because it is `!=` rather than `=` ?

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:196]: right, while formally `asof` is a `left join` how exactly this new model is supposed to be executed ? what the post-join filter will be applied to and how to filter result will be treated ?

File: core/src/test/java/io/questdb/griffin/AsOfJoinTest.java (hunk 2 above)
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: In this context - yes but join conditions could be anything .

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:196]: post-join-where is normally translated into a filter step after the join and will filter out records that do not pass the predicate .
`trade.sym = book.sym`  in ASOF ON clause would keep the left side even if no matching record is found .

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 3 above)
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:265]: These single table conditions are pushed to post join phase of ASOF join . 
While changing left join condition and pushing down to right table is generally unsafe .
Let me double check my notes .

File: core/src/main/java/io/questdb/griffin/SqlParser.java (hunk 1 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/SqlParser.java]: Fixed

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:196]: In theory trade.sym = book.sym can be copied into join condition and also left as post join condition but I didn't want to start duplicating condtions (at least before explain arrvies and allows for better plan testing) .

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 3 above)
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:265]: Right, pushing down predicates into right table of left join can easily distort join output .
Same as above - it would only work if we both copied it right model and kept as post join condition .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 378 / 394 (95.94%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|60|65|92.31%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|63|68|92.65%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|97|99|97.98%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|94|96|97.92%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|33|33|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|15|15|100.00%|

File: core/src/test/java/io/questdb/griffin/AsOfJoinTest.java (hunk 2 above)
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: To make it more clear - this change actually preserves query outcome  because in master branch most join conditions except equality are pushed to post-join or parent where clause (regardless of join type) .

Comment (ideoma) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: This test passes with and without WHERE. The condition simply does not filer anything so even with the semantics changed the result is the same.

Having it in WHERE makes sense since we error that don't support having not equals in ON.

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java [hunk 5]
```diff
@@ -0,0 +1,237 @@
...
+        @Override
+        public boolean hasNext() {
+            if (slaveChainCursor != null && slaveChainCursor.hasNext()) {
+                record.hasSlave(true);
+                while (slaveChainCursor.hasNext()) {
+                    slaveCursor.recordAt(slaveRecord, slaveChainCursor.next());
+                    if (filter.getBool(record)) {
+                        return true;
+                    } else {
+                        slaveChainCursor.next();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java:161]: This condition not covered by tests.

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java [hunk 6]
```diff
@@ -0,0 +1,237 @@
...
+        } catch (Throwable e) {
+            Misc.free(slaveCursor);
+            Misc.free(masterCursor);
+            throw e;
+        }
+    }
+
+    @Override
+    public boolean hasDescendingOrder() {
+        return masterFactory.hasDescendingOrder();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java:97]: Not covered by tests

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java [hunk 7]
```diff
@@ -0,0 +1,238 @@
...
+        } catch (Throwable e) {
+            Misc.free(slaveCursor);
+            Misc.free(cursor);
+            throw e;
+        }
+    }
+
+    @Override
+    public boolean hasDescendingOrder() {
+        return masterFactory.hasDescendingOrder();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java:94]: Not covered by tests

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java [hunk 8]
```diff
@@ -0,0 +1,238 @@
...
+        }
+
+        @Override
+        public boolean hasNext() {
+            if (useSlaveCursor && slaveChain.hasNext()) {
+                record.hasSlave(true);//necessary for filter 
+                do {
+                    if (filter.getBool(record)) {
+                        return true;
+                    }
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java:174]: filter returning false not covered by tests

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java [hunk 9]
```diff
@@ -0,0 +1,238 @@
...
+        }
+
+        @Override
+        public long size() {
+            return -1;
+        }
+
+        @Override
+        public void toTop() {
+            masterCursor.toTop();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java:207]: `fitler.toTop();`

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java [hunk 10]
```diff
@@ -0,0 +1,237 @@
...
+
+        @Override
+        public long size() {
+            return -1L;
+        }
+
+        @Override
+        public void toTop() {
+            masterCursor.toTop();
+            slaveChainCursor = null;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java:197]: flter.topTop();

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java [hunk 11]
```diff
@@ -0,0 +1,237 @@
...
+                    if (value.isNew()) {
+                        final long offset = slaveChain.put(record.getRowId(), -1);
+                        value.putLong(0, offset);
+                        value.putLong(1, offset);
+                    } else {
+                        value.putLong(1, slaveChain.put(record.getRowId(), value.getLong(1)));
+                    }
+                }
+            } catch (Throwable t) {
+                close();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java:217]: I'd move this close() to the `public RecordCursor getCursor(SqlExecutionContext executionContext)`, this is how it's done in `HashOuterJoinFilteredRecordCursorFactory`

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java [hunk 12]
```diff
@@ -0,0 +1,173 @@
...
+        @Override
+        public void toTop() {
+            masterCursor.toTop();
+            masterCursor.hasNext();
+            slaveCursor.toTop();
+            filter.toTop();
+            isMatch = false;
+            hasMore = true;
+            record.hasSlave(true);
+        }
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:163]: `fiter.toTop();`

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (ideoma) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:196]: I agree with @bziobrowski here, this looks like a correct fix

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java [hunk 13]
```diff
@@ -0,0 +1,173 @@
...
+        try {
+            slaveCursor = slaveFactory.getCursor(executionContext);
+            if (masterCursor.hasNext()) {
+                cursor.of(masterCursor, slaveCursor, executionContext);
+                return cursor;
+            }
+            slaveCursor = Misc.free(slaveCursor);
+            Misc.free(masterCursor);
+        } catch (Throwable ex) {
+            Misc.free(masterCursor);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:75]: Not tested

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java [hunk 14]
```diff
@@ -0,0 +1,173 @@
...
+    }
+
+    @Override
+    public boolean recordCursorSupportsRandomAccess() {
+        return false;
+    }
+
+    @Override
+    public boolean supportsUpdateRowId(CharSequence tableName) {
+        return masterFactory.supportsUpdateRowId(tableName);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:90]: Not tested. Please test it in `UPDATE` statement.

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 12 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:163]: Do you mean toTop() method ? 
It's there already: ```java
            slaveCursor.toTop();
            filter.toTop();
            isMatch = false;
```

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 14 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:90]: Is there a realistic way to test it ? 
Explicit joins, subqueries and with alias update are not allowed in UPDATE statement. 
This method follows CrossJoin factory . Should I remove it so it returns the default [false] ?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 376 / 384 (97.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|63|68|92.65%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|64|65|98.46%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|95|95|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|33|33|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|90|90|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|15|15|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 14 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:90]: You can have joins in updates. This should have a cross join from a to b

```sql
UPDATE a SET r = 1
FROM b
WHERE b.id = 123
```

This will have a left join

```
UPDATE a SET r = 1
FROM b
LEFT JOIN c on b.id = c.id
WHERE a.id = b.id
```

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 12 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:163]: yes, there is `filter.toTop()` already

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 14 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:90]: That doesn't seem to be the case and only implicit joins via where clause conditions are accepted . 
The update sql you mentioned produces "JOIN is not supported on UPDATE statement" error message .
Please have a look at UpdateTest.testUpdateWithJoinUnsupported .

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/test/java/io/questdb/griffin/SqlParserTest.java:196]: 👍

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 14 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:90]: @ideoma anything to add ?

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java (hunk 10 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java:194]: @bziobrowski any comments here ?

File: core/src/test/java/io/questdb/griffin/AsOfJoinTest.java (hunk 2 above)
Comment (bluestreak01) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: @bziobrowski any comments ?

Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/AsOfJoinTest.java:269]: Not really . Condition doesn't affect test output but if we change it then output is consistent with current master . 
I discussed the thing with Alex on slack .

File: core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java (hunk 10 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java:194]: it's resolved

File: core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java (hunk 14 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java:90]: @bziobrowski is right, UPDATE with JOINs are prohibited, I created separate issue to update docs or code #2900

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 376 / 384 (97.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|63|68|92.65%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|64|65|98.46%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|95|95|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|33|33|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|90|90|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|15|15|100.00%|
