### PR TITLE
fix(core): fix edge case error when importing a large CSV file

### LINKED ISSUE #4100: CSV import: io_uring bug
### To reproduce

1. in EC2 start `al2023-ami-2023.3.20231218.0-kernel-6.1-x86_64` on `m5.8xlarge`
2. Clone Clickbench: https://github.com/ClickHouse/ClickBench/tree/4231d567963b5dbe65a7e1091e61020a4f9afeec
3. Start `benchmark.sh` in Clickbench `questdb-partitioned` directory

After a few minutes the import process fails with: 
```
could not attach [partition='2013-07-30', msg=[0] invalid timestamp column data in detached partition, data does not match partition directory name [path=/home/ec2-user/.questdb/db/hits~6/2013-07-30.attachable/EventTime.d, minTimestamp=2013-07-30T00:00:00.000Z, maxTimestamp=1970-01-01T00:00:00.000Z]]
```

Env:
```
$ cat /etc/amazon-linux-release
Amazon Linux release 2023 (Amazon Linux)

$ uname -a
Linux ip-172-31-47-91.eu-west-1.compute.internal 6.1.66-91.160.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 04:50:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
I tested this on latest QuestDB, 7.3.5 and even 7.3.2 (the last version before the UTF8 split)

**Important**: The file imports fine when you disable io_uring!

Investigation:
QuestDB log file contains this:
```
2024-01-03T13:56:51.580977Z I i.q.c.TableWriter switched partition [path='/home/ec2-user/.questdb/tmp/hits~6/hits_3/2013-07-28']
2024-01-03T13:56:51.583645Z E i.q.c.t.AbstractTextLexer extra fields [table=hits_18, fieldIndex=105, fieldMax=104]
        20161 -> 5349222886455379406,1,6708535508038068784,1,, Украины. Автопоиск работа, 30 летнему",1,2013-07-30 05:15:55,2013-07-30,2151,1928873128,229,2098617149801017098,1,44,5,http://gotovim-doma.ru,http://wildberrina264975,0,10282,31432,15014,22796,1638,1658,37,15,13,800,0,0,31,D�,1,1,0,0,,,2910293,-1,0,,0,0,1150,633,135,2013-07-30 08:37:03,0,0,0,0,windows,1,0,0,0,0,,229032913,0,0,0,0,0,5,2013-07-30 04:42:20,0,0,0,0,0,1539342176,-1,-1,-1,S0,�^L,,,0,0,0,0,0,0,0,0,,0,,NH^\,0,,,,,,,,,,,0,-8885576463113265542 ...
2024-01-03T13:56:51.583808Z E i.q.c.t.AbstractTextLexer extra fields [table=hits_18, fieldIndex=106, fieldMax=104]
        20161 -> 5349222886455379406,1,6708535508038068784,1,, Украины. Автопоиск работа, 30 летнему",1,2013-07-30 05:15:55,2013-07-30,2151,1928873128,229,2098617149801017098,1,44,5,http://gotovim-doma.ru,http://wildberrina264975,0,10282,31432,15014,22796,1638,1658,37,15,13,800,0,0,31,D�,1,1,0,0,,,2910293,-1,0,,0,0,1150,633,135,2013-07-30 08:37:03,0,0,0,0,windows,1,0,0,0,0,,229032913,0,0,0,0,0,5,2013-07-30 04:42:20,0,0,0,0,0,1539342176,-1,-1,-1,S0,�^L,,,0,0,0,0,0,0,0,0,,0,,NH^\,0,,,,,,,,,,,0,-8885576463113265542 ...

2024-01-03T13:56:51.583945Z E i.q.c.t.CopyTask type syntax [type=TIMESTAMP, offset=56248367326, column=4, value=' 30 летнему"']
```
Notice how it tried to cast the string `30 летнему"` as a timestamp. A designated timestamp even. This fails, the line is skipped and due to another bug, it's not reported (and recorded!) as an error! So the import process thinks it imported more lines than it actually did and later when it tries to attach this partition it will read max-timestamp from an empty area, it will read it `0` = epoch start and fails with the error:
```
could not attach [partition='2013-07-30', msg=[0] invalid timestamp column data in detached partition, data does not match partition directory name [path=/home/ec2-user/.questdb/db/hits~6/2013-07-30.attachable/EventTime.d, minTimestamp=2013-07-30T00:00:00.000Z, maxTimestamp=1970-01-01T00:00:00.000Z]]
```

The row discussed above belongs to this line in the input CSV: 
```
6708535508038068784,1,"Новости Redmond. Цвет бензии, Украины. Автопоиск работа, 30 летнему",1,"2013-07-30 05:15:55","2013-07-30",2151,1928873128,229,2098617149801017098,1,44,5,"http://gotovim-doma.ru","http://wildberrina264975",0,10282,31432,15014,22796,1638,1658,37,15,13,"800",0,0,31,"D�",1,1,0,0,"","",2910293,-1,0,"",0,0,1150,633,135,"2013-07-30 08:37:03",0,0,0,0,"windows",1,0,0,0,0,"",229032913,0,0,0,0,0,"5","2013-07-30 04:42:20",0,0,0,0,0,1539342176,-1,-1,-1,"S0","�^L","","",0,0,0,0,0,0,0,0,"",0,"","NH^\",0,"","","","","","","","","","",0,-8885576463113265542,-6365367157406405336,0
```

Except the line/field in logs is a bit mangled: The first 2 columns should not be there. Also, the first string is mangled: 
CSV: "Новости Redmond. Цвет бензии, Украины. Автопоиск работа, 30 летнему"
QuestDB Log: Украины. Автопоиск работа

The extra 2 fields belong to an entirely different line in the input CSV. At first, I thought there was a bug in the line boundary analyzer. but this would not go away when io_uring is disabled.

Current hypothesis:
1. A kernel bug. This is the first kernel version where this manifests. 
2. A bug in QuestDB which is triggered by a newer kernel.

### QuestDB version:

7.3.5

### OS, in case of Docker specify Docker and the Host OS:

Amazon Linux 2023

### File System, in case of Docker specify Host File System:

not sure

### Full Name:

Jaromir Hamala

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #4100

Reasoning:
This is the buggy line: `int diff = ((int) (nextOffset - offset)) - bytesToRead;` 
`nextOffset` and `offset` are 48 bits numbers stored inside 64 bits long.

When subtracted from each other the result can produce more than 32 bits. When narrow-casting the result to `int` the higher bits are truncated.

If you are especially unlucky then the truncated `diff` value is 0 or 1 and the coalescing algo will coalesce lines which should not be coalesced.

This means #4100 is not io_uring specific.

### CODE REVIEW

File: core/src/main/java/io/questdb/cutlass/text/CopyTask.java [hunk 1]
```diff
@@ -1183,10 +1184,10 @@ private void importPartitionDataVanilla(
                         long nextOffset = nextLengthAndOffset & MASK;
 
                         // line indexing stops on first EOL char, e.g. \r, but it could be followed by \n
-                        int diff = ((int) (nextOffset - offset)) - bytesToRead;
-                        int nextBytesToRead = diff + nextLineLength;
+                        long diff = nextOffset - offset - bytesToRead;
+                        int nextBytesToRead = (int) (diff + nextLineLength);
                         if (diff > -1 && diff < 2 && bytesToRead + nextBytesToRead <= fileBufSize) {
-                            bytesToRead += diff + nextLineLength;
+                            bytesToRead += ((int) diff) + nextLineLength;
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cutlass/text/CopyTask.java:1190]: Can be simplified to the following?
```java
bytesToRead += nextBytesToRead;
```

**Review by puzpuzpuz — APPROVED** [review]

File: core/src/main/java/io/questdb/cutlass/text/CopyTask.java (hunk 1 above)
Comment (jerrinot) [reply core/src/main/java/io/questdb/cutlass/text/CopyTask.java:1190]: it can! I had a slightly different version before, then tweaked it a bit and ended-up with duplicated things without noticing. thanks!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|5|5|100.00%|
