### PR TITLE
fix(sql): missing from in select wildcard

### LINKED ISSUE #2294: SQL: `select * trades` should be parse error
### Describe the bug

_No response_

### To reproduce

1. go to (demo)[https://demo.questdb.io/]
2. query `select * trades`. Note of missing `FROM` keyword

One row with 1 returned

### Expected Behavior

SQL error

### Environment

```markdown
- **QuestDB version**: 6.4.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lookharm**
fixes #2294

### CODE REVIEW

**Comment by marregui** [comment]
Hola @lookharm ,

Try the queries in the webconsole by firing up QuestDB. 

To build QuestDB it so that you have the webconsole:

```shell
mvn clean package -Pbuild-web-console -DskipTests
```
When the build is complete, you will find file `./core/src/main/resources/io/questdb/site/public.zip`. This file needs to be copied to QuestDB's root folder and decompressed in there. QuestDB's root folder is defined by you, let's suppose you have it in  **/Users/lookharm/QUEST**. Within this folder you need to have a folder `conf` which needs to contain files:

- server.conf
- mime.types
- log.conf

You can harvest default files from the project, search for them, copy, paste, edit.

Have fun!

**Comment by lookharm** [comment]
Yes @marregui , I tried according to the README, though do you have any other suggestions for this fix?

**Comment by marregui** [comment]
Yup. I would approach this from a different angle. You know that these two queries have a prefix in common:
- `select *`
- `select * tab`
so this will result in the same `SqlParser.parseSelectClause` call. At some point in that call the `*` is found and parsed as an expression. At this point you could pretend you expect a 'from' and if you don't get it you can throw a SqlException, otherwise you need to unparse the last token (the from) so that the usual parsing tree carries on being generated.

If you do this you will reach two conclusions:
- `select *` has to go as well, and breaking tests need to replace such statement by its equivalent using `from long_sequence(1)`.
- `select *, tab1.y....`, i.e. a "select `*,`" is a perfectly valid statement, so it is an exception to the "must be followed by from" rule.

Armed with all this knowledge and these tests you should ace it:

```java
@Test
    public void testSelectWildcardOnly() throws Exception {
        assertFailure(
                "select *",
                "create table tab (seq long)",
                8,
                "'from' expected"
        );
    }

    @Test
    public void testSelectWildcardTabNoFrom() throws Exception {
        assertFailure(
                "select * tab",
                "create table tab (seq long)",
                8,
                "'from' expected"
        );
    }
```

**Comment by lookharm** [comment]
Hi @marregui , it would be great if you can review this change.

**Review by marregui — APPROVED** [review]

File: core/src/test/java/io/questdb/griffin/SqlParserTest.java [hunk 1]
```diff
@@ -4766,7 +4766,7 @@ public void testNullChecks() throws SqlException {
                 "SELECT \n" +
                         "a\n" +
                         "FROM x WHERE b = 'H' AND time in('2020-08-01T17:00:00.305314Z' , '2020-09-20T17:00:00.312334Z')\n" +
-                        "select *", // <-- dangling 'select *'
+                        "select * from long_sequence(1)", // <-- dangling 'select * from long_sequence(1)'
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/griffin/SqlParserTest.java:4769]: nit: comment does not make sense anymore, nothing dangling anymore. Perhaps remove comment to avoid future confusion.
