### PR TITLE
fix(sql): error on group by with many aggregate functions

### LINKED ISSUE #3326: Too Much Input Exception When SELECTing Many AVG Columns
### Describe the bug

When SELECTing 6000 columns AVG on the same SELECT there is an error.
ServerSide:
```
023-05-12T09:12:00.131416Z E i.q.s.BytecodeAssembler Too much input to generate io.questdb.griffin.engine.groupby.GroupByFunctionsUpdater. Bytecode is too long
2023-05-12T09:12:00.131435Z C i.q.c.p.PGWireServer internal error [ex=
io.questdb.std.ex.BytecodeException: Error in bytecode
	at io.questdb.std.ex.BytecodeException.<clinit>(BytecodeException.java:28)
	at io.questdb.std.BytecodeAssembler.endMethodCode(BytecodeAssembler.java:199)
	at io.questdb.griffin.engine.groupby.GroupByFunctionsUpdaterFactory.generateUpdateNew(GroupByFunctionsUpdaterFactory.java:220)
	at io.questdb.griffin.engine.groupby.GroupByFunctionsUpdaterFactory.getInstance(GroupByFunctionsUpdaterFactory.java:110)
	at io.questdb.griffin.engine.groupby.GroupByNotKeyedRecordCursorFactory.<init>(GroupByNotKeyedRecordCursorFactory.java:64)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectGroupBy(SqlCodeGenerator.java:3336)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2665)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2272)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2259)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:186)
	at io.questdb.griffin.SqlCompiler.generate(SqlCompiler.java:2731)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1322)
	at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1271)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:268)
	at io.questdb.cutlass.pgwire.PGConnectionContext.compileQuery(PGConnectionContext.java:1192)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parseQueryText(PGConnectionContext.java:1699)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processParse(PGConnectionContext.java:2358)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1631)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:418)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:91)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:128)
	at io.questdb.mp.Worker.run(Worker.java:118)
]
```

ClientSide (.NET):
```
    Npgsql.NpgsqlException: Exception while reading from stream ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.

  Stack Trace: 
    NpgsqlReadBuffer.<Ensure>g__EnsureLong|42_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
    --- End of inner exception stack trace ---
    NpgsqlReadBuffer.<Ensure>g__EnsureLong|42_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
    NpgsqlConnector.<ReadMessage>g__ReadMessageLong|232_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
    NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
    NpgsqlDataReader.NextResult()
    NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
    NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
    NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
```

### To reproduce

Create a table with a lot of columns.
SELECT AVG of each of them:
`SELECT AVG(col1), AVG(col2), .... , AVG(colX) from tbl`

### Expected Behavior

the results of the query should be returned.

### Environment

```markdown
- **QuestDB version**:711
- **OS**:windows
- **Browser**:chrome
```

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #3326

This PR fixes bug where GROUP BY queries with many aggregate functions fail with "Bytecode is too long" error, and includes significant performance optimizations for the SQL optimizer to speed up query compilation. We had a number of places with O(n²) complexity.

For instance, the following query:
```sql
SELECT avg(value), avg(value + 1), avg(value + 2), ... -- 6K functions in total
FROM my_table;
```
was taking 4 seconds to compile. With this patch, the compilation takes around 300ms.

#### 1. GroupByFunctionsUpdaterFactory Fallback (core fix)
- Added `SimpleGroupByFunctionUpdater` - a loop-based fallback implementation that avoids JVM bytecode limits
- When aggregate function count exceeds 32, uses the simple loop-based updater instead of generating bytecode
- Threshold determined via JMH benchmarking: bytecode is faster below 32 functions, loop is faster above

#### 2. O(1) Amortized Alias Generation (performance)
- **Before**: Alias generation was O(n²) - for each new alias, it scanned through sequence numbers 1, 2, 3... until finding an unused one
- **After**: Added `LowerCaseCharSequenceIntHashMap` to track the next sequence number for each base alias
- Added `aliasSequenceMap` to `QueryModel` (per-model state) and separate maps for pivot/cursor aliases in `SqlOptimiser` and `SqlParser`

#### 3. O(n) Duplicate Aggregate Detection (performance)
- **Before**: O(n²) pairwise `compareNodesExact()` comparison to detect duplicate aggregates
- **After**: Hash-based detection using `ExpressionNode.deepHashCode()` - only compares nodes when hashes collide
- Added `detectDuplicateAggregates()` method in `SqlOptimiser`

#### 4. Optimized findColumnByAst (performance)
- Moved `findColumnByAst()` call inside the `if (useOuterModel)` check
- Avoids unnecessary O(n) searches when the result won't be used

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
@coderabbitai review

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 159 / 163 (97.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByFunctionsUpdaterFactory.java|23|26|88.46%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|92|93|98.92%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsyncWindowJoinAtom.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByAtom.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByNotKeyedAtom.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|23|23|100.00%|

File: core/src/test/java/io/questdb/test/griffin/GroupByTest.java [hunk 1]
```diff
@@ -2807,6 +2806,86 @@ public void testLimitedOrderByLongConstant() throws Exception {
         });
     }
 
+    @Test
+    public void testManyAggregatesFallbackUpdater() throws Exception {
+        // This test verifies that GROUP BY queries with many aggregate functions
+        // don't fail with "Bytecode is too long" error. See issue #3326.
+        assertMemoryLeak(() -> {
+            // change to 6k to reproduce the OG issue
+            final int functionCount = 1000;
```
Comment (nwoolmer) [inline core/src/test/java/io/questdb/test/griffin/GroupByTest.java:2815]: nit: why 1k and not 6k? to speed up test?

Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/griffin/GroupByTest.java:2815]: Yes, with 6K the test takes 300-400ms on my box and on CI that would be even longer.
