### PR TITLE
fix(core): improve database stability after power loss

### LINKED ISSUE #2420: Data cannot be recovered after the server is powered off
### Describe the bug

Data cannot be recovered after the server is powered off

image
image

### To reproduce

the server is powered off

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:6.4.3
- **OS**:windows server 2019 datacenter
- **Browser**:Google Chrome
```

### Additional context

_No response_

### LINKED ISSUE #3050: Unable to restart after abnormal power failure under windows
### Describe the bug

Metadata version dos not  match runtime version

### To reproduce

Directly disconnect the power supply, the service cannot be started
image

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:7.0.1
- **OS**:windows 10
- **Browser**:chrome
```

### Additional context

_No response_

### LINKED ISSUE #3276: After power off and restart, the data table cannot be accessed
### Describe the bug

OS: Windows 10
QuestDB: 6.7

After a sudden power outage and restart of the computer, a data table is no longer accessible

Error Message: 
Npgsql.PostgresException (0x80004005): 00000: [-100]: Invalid metadata at fd=1184. Metadata version does not match runtime version [expected=426, actual=417]
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
...

At the same time, I found that other tables are accessed normally, and the table with errors generates a .lock file. I suspect it is locked?
#1448  At the same time, I found that many people have already had this problem, and I hope someone can tell me the solution, thank you

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
Fixes #3276
Fixes #3050
Fixes #2420

Reviewed using msync/fsync and refactored codebase to ensure database recovers data after abrupt power loss.

Method of testing is as follows:

- find a good USB stick or memory card, with decent thruput
- run QuestDB against database on memory card
- I used TSBS benchmark to upload data
- pull the card/UBS stick out of the computer mid data upload
- tested with customised `loadTest` from LineTCPFuzzTest to evaluate durability of metadata changes
- tested with `LineTCPSender03MultiTableMain` to evaluate durability of partition squashing

When drive disappears database may become unstable, SEGFAULT or fail to stop. This matters very little because we're simulating power loss. We don't expect DB instance to keep running.

On startup database starts with no significant rows. It shows uploaded-so-far data correctly and continues WAL apply process. There were no corrupt data structures observed over multiple "power loss" events.

### CODE REVIEW

File: core/src/main/java/io/questdb/cairo/TableWriter.java [hunk 1]
```diff
@@ -5580,6 +5349,230 @@ private void processPartitionRemoveCandidates0(int n) {
         }
     }
 
+    private long processWalBlock(
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/cairo/TableWriter.java:5352]: this method is unchanged, it was needlessly "public". I made it "private" hence IDE refactoring.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 258 / 308 (83.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|4|12|33.33%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|185|208|88.94%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
once this PR is merged we need to update this paragraph:

image

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 258 / 308 (83.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|4|12|33.33%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|185|208|88.94%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 272 / 324 (83.95%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|4|12|33.33%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|186|209|89.00%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 272 / 325 (83.69%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|4|12|33.33%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|8|12|66.67%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|186|209|89.00%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 247 / 294 (84.01%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|2|6|33.33%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|6|10|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|22|34|64.71%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|7|10|70.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|11|15|73.33%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|86|96|89.58%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrameFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrame.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CsvFileIndexer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/FrameAlgebra.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileColumnPool.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|

File: core/src/main/java/io/questdb/cairo/wal/WalWriterEvents.java [hunk 2]
```diff
@@ -266,6 +266,11 @@ void rollback() {
         // Not truncating the files saves from reading complexity.
     }
 
+    void sync(boolean async) {
+        eventMem.sync(async);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/wal/WalWriterEvents.java:270]: nit: we should always sync metadata files, so the argument is redundant.

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java [hunk 3]
```diff
@@ -1333,20 +1366,35 @@ private void switchColumnsToNewSegment(LongList newColumnFiles) {
                 long currentOffset = newColumnFiles.get(i * NEW_COL_RECORD_SIZE + 1);
                 long newOffset = newColumnFiles.get(i * NEW_COL_RECORD_SIZE + 2);
                 primaryColumnFile.jumpTo(currentOffset);
+                primaryColumnFile.sync(false);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/wal/WalWriter.java:1369]: This call should use commit mode from config just like the below `secondaryColumnFile.sync(false)` call.

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java [hunk 4]
```diff
@@ -720,11 +729,17 @@ private void cleanupSymbolMapFiles(Path path, int rootLen, CharSequence columnNa
...
     private void closeSegmentSwitchFiles(LongList newColumnFiles) {
+        int commitMode = configuration.getCommitMode();
+
         // Each record is about primary and secondary file. File descriptor is set every half a record.
         int halfRecord = NEW_COL_RECORD_SIZE / 2;
         for (int fdIndex = 0; fdIndex < newColumnFiles.size(); fdIndex += halfRecord) {
             final int fd = (int) newColumnFiles.get(fdIndex);
-            ff.close(fd);
+            if (commitMode != CommitMode.NOSYNC) {
+                ff.fsyncAndClose(fd);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/wal/WalWriter.java:739]: We should consider commit mode from config here.

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java [hunk 5]
```diff
@@ -1308,6 +1339,7 @@ private void setVarColumnFixedFileNull(int columnType, int columnIndex, long row
             } finally {
                 ff.munmap(addressFixed, fixedSizeColSize, MEM_TAG);
             }
+            ff.fsync(fixedSizeColumn.getFd());
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/wal/WalWriter.java:1342]: We should consider commit mode from config here and in similar calls below.

File: core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java [hunk 6]
```diff
@@ -210,10 +210,9 @@ public void switchTo(int fd, long offset, byte truncateMode) {
     }
 
     public void sync(boolean async) {
-        if (pageAddress != 0 && ff.msync(pageAddress, size, async) == 0) {
-            return;
+        if (fd != -1) {
+            ff.fsync(fd);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java:214]: nit: A heads-up. Mixing mmap-based writes with fsync may be prone to bugs on certain file systems. OSes other than Linux may also have a hard time with this usage pattern.

The same consideration applies to other similar changes from this PR.

File: core/src/main/java/io/questdb/cairo/TxWriter.java [hunk 7]
```diff
@@ -164,9 +164,13 @@ public void commit(int commitMode, ObjList<? extends SymbolCountProvider> symbol
 
             prevRecordBaseOffset = lastRecordBaseOffset;
             lastRecordBaseOffset = writeBaseOffset;
+            int commitMode = configuration.getCommitMode();
+            if (commitMode != CommitMode.NOSYNC) {
+                txMemBase.sync(commitMode == CommitMode.ASYNC);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/TxWriter.java:169]: We should always sync metadata files if we want better stability on power loss.

File: core/src/main/java/io/questdb/cairo/TableWriter.java [hunk 8]
```diff
@@ -2291,6 +2286,11 @@ private int addColumnToMeta(
                 nameOffset += Vm.getStorageLength(columnName);
             }
             ddlMem.putStr(name);
+
+            final int commitMode = configuration.getCommitMode();
+            if (commitMode != CommitMode.NOSYNC) {
+                ddlMem.sync(commitMode == CommitMode.ASYNC);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/TableWriter.java:2292]: We should always sync metadata files if we want better stability on power loss.

File: core/src/main/java/io/questdb/cairo/O3CopyJob.java [hunk 9]
```diff
@@ -496,6 +496,12 @@ private static void copyTail(
                 );
             }
 
+            final int commitMode = tableWriter.getConfiguration().getCommitMode();
+            O3Utils.fsync(ff, srcDataFixFd, commitMode);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/O3CopyJob.java:500]: nit: it's worth adding a comment that would clarify why we sync not only the destination but also the source files.

Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/O3CopyJob.java:500]: nit: the same concern on mixed mmap + fsync.

File: core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java [hunk 10]
```diff
@@ -275,6 +278,11 @@ private void doCommit() {
 
         Unsafe.getUnsafe().storeFence();
         storeNewVersion();
+
+        final int commitMode = configuration.getCommitMode();
+        if (commitMode != CommitMode.NOSYNC) {
+            mem.sync(commitMode == CommitMode.ASYNC);
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java:284]: We should always sync metadata files if we want better stability on power loss.

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java [hunk 11]
```diff
@@ -1333,20 +1366,35 @@ private void switchColumnsToNewSegment(LongList newColumnFiles) {
...
                 primaryColumnFile.switchTo(newPrimaryFd, newOffset, Vm.TRUNCATE_TO_POINTER);
+                primaryColumnFile.sync(false);
 
                 int newSecondaryFd = (int) newColumnFiles.get(i * NEW_COL_RECORD_SIZE + 3);
                 if (newSecondaryFd > -1) {
                     MemoryMA secondaryColumnFile = getSecondaryColumn(i);
                     currentOffset = newColumnFiles.get(i * NEW_COL_RECORD_SIZE + 4);
                     newOffset = newColumnFiles.get(i * NEW_COL_RECORD_SIZE + 5);
                     secondaryColumnFile.jumpTo(currentOffset);
+                    secondaryColumnFile.sync(false);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/wal/WalWriter.java:1379]: It should be fine not to sync old column files, they should already be sync-ed in the main commit method.

File: core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java [hunk 12]
```diff
@@ -59,20 +57,22 @@ public void append(long offset, FrameColumn sourceColumn, long sourceLo, long so
                     indexWriter.add(TableUtils.toIndexKey(Unsafe.getUnsafe().getInt(mappedAddress + (i << shl))), offset + i);
                 }
                 indexWriter.setMaxValue(offset + size - 1);
+                indexWriter.commit();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java:60]: nit: commit mode is ignored

File: core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java [hunk 13]
```diff
@@ -59,20 +57,22 @@ public void append(long offset, FrameColumn sourceColumn, long sourceLo, long so
...
-    public void appendNulls(long offset, long count) {
-        super.appendNulls(offset, count);
+    public void appendNulls(long offset, long count, int commitMode) {
+        super.appendNulls(offset, count, commitMode);
         indexWriter.rollbackConditionally(offset);
         for (long i = 0; i < count; i++) {
             indexWriter.add(0, offset + i);
         }
         indexWriter.setMaxValue(offset + count - 1);
+        indexWriter.commit();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java:75]: nit: commit mode is ignored

File: core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java (hunk 12 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java:60]: `BitmapIndexWriter` fetches the commit mode from `CairoConfiguration`, so it respects the configured commit mode.

File: core/src/main/java/io/questdb/cairo/RecoverVarIndex.java [hunk 14]
```diff
@@ -31,20 +31,27 @@
...
+        super(configuration);
+    }
+
     @Override
     protected void doReindex(
+            FilesFacade ff,
             ColumnVersionReader columnVersionReader,
             int columnWriterIndex,
             CharSequence columnName,
+
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/RecoverVarIndex.java:50]: fixed here https://github.com/questdb/questdb/pull/3304/commits/82e8eac6da0f25693d8bd701a86efd752ed80d1d

File: core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java [hunk 15]
```diff
@@ -103,7 +103,7 @@ public void closeWriter() {
 
     public void commit() {
         if (writer != null) {
-            writer.commit(durable ? CommitMode.SYNC : CommitMode.NOSYNC);
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:106]: good spot, ic() sig:

image

durability call:

image

File: core/src/main/java/io/questdb/cairo/vm/MemoryPMARImpl.java [hunk 16]
```diff
@@ -122,11 +124,8 @@ public void switchTo(int fd, long offset, byte truncateMode) {
     }
 
     public void sync(boolean async) {
-        if (pageAddress != 0) {
-            if (ff.msync(pageAddress, getExtendSegmentSize(), async) == 0) {
-                return;
-            }
-            LOG.error().$("could not msync [fd=").$(fd).$(", errno=").$(ff.errno()).$(']').$();
+        if (fd != -1) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/vm/MemoryPMARImpl.java:127]: We should also msync when a page gets released and a new one is being mmapped.

File: core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java:106]: removed durability arg here https://github.com/questdb/questdb/pull/3304/commits/32255a783fed5a293691187dbfbb914632492404

File: core/src/test/java/io/questdb/test/cairo/O3BasketTest.java [hunk 17]
```diff
@@ -25,30 +25,34 @@
...
 
-public class O3BasketTest {
+public class O3BasketTest extends AbstractTest {
     @Test
     public void testSimple() {
         O3Basket basket = new O3Basket();
+        final CairoConfiguration configuration = new DefaultCairoConfiguration(root);
 
-        basket.ensureCapacity(5, 2);
+        basket.ensureCapacity(configuration,5, 2);
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/test/java/io/questdb/test/cairo/O3BasketTest.java]: fixed here https://github.com/questdb/questdb/pull/3304/commits/32255a783fed5a293691187dbfbb914632492404

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java (hunk 3 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/wal/WalWriter.java]: fixed here https://github.com/questdb/questdb/pull/3304/commits/35152031def614e94ef1d37c6cb20f56749660c9

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java (hunk 4 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/wal/WalWriter.java:739]: I don't quite follow, we do act here according to the config.

File: core/src/main/java/io/questdb/cairo/TxWriter.java (hunk 7 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/TxWriter.java:169]: unfortunately when we have NOSYNC committing txn only is like doing a CPR to a dead person

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java (hunk 5 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/wal/WalWriter.java]: fixed here https://github.com/questdb/questdb/pull/3304/commits/63cf4210b42daeb8118233d89abbe70b18fe41a4

also replaced `fsync` with `msync`

File: core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java (hunk 6 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java]: fixed just this for now here: https://github.com/questdb/questdb/pull/3304/commits/83f45037735546bc7e05a22925e75d89e408483b

File: core/src/main/java/io/questdb/cairo/wal/WalWriterEvents.java (hunk 2 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/wal/WalWriterEvents.java]: fixed here https://github.com/questdb/questdb/pull/3304/commits/e2a1fce67513ec949fd420febeaa102c8391d169

File: core/src/main/java/io/questdb/cairo/TableWriter.java (hunk 8 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/TableWriter.java:2292]: same comment as above, with NOSYNC we lose column data quite easily

File: core/src/main/java/io/questdb/cairo/O3CopyJob.java (hunk 9 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/O3CopyJob.java]: this is a good spot, we don't need to sync read-only things, fixed here https://github.com/questdb/questdb/pull/3304/commits/8b45780d47d24e64fdaa790540513f6360a6e30b along with replacing fsync with msync

Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/O3CopyJob.java]: fixed here https://github.com/questdb/questdb/pull/3304/commits/8b45780d47d24e64fdaa790540513f6360a6e30b

File: core/src/main/java/io/questdb/cairo/TableWriter.java (hunk 8 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/TableWriter.java]: on a second thought, this is column add, may as well sync always: https://github.com/questdb/questdb/pull/3304/commits/f9de70ee205e8d2de8b792cfb10fc8db4b9c1110

File: core/src/main/java/io/questdb/cairo/TxWriter.java (hunk 7 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/TxWriter.java:169]: i guess I need to clarify. If someone chose not to SYNC at all, my assumption would be they did that for performance reasons understanding and accepting the risks. Syncing TXN could increase commit latency making small commits significantly slower

File: core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java (hunk 10 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java:284]: this is called from `commit()` and affects commit() latency. Same reasoning applies as here https://github.com/questdb/questdb/pull/3304#discussion_r1192785305

File: core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java (hunk 12 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java:60]: Andrei is right

File: core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java (hunk 13 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java:75]: same comment as this: https://github.com/questdb/questdb/pull/3304#discussion_r1192575225

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 262 / 324 (80.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|10|30.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|6|10|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|32|51|62.75%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|7|10|70.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|85|94|90.43%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrameFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrame.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CsvFileIndexer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/FrameAlgebra.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileColumnPool.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|2|2|100.00%|

File: core/src/main/java/io/questdb/cairo/wal/WalWriter.java (hunk 11 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/wal/WalWriter.java]: Refactored this place to not sync anything. We have to msync all mmap stuff and fsync file stuff. I moved the logic to where we copy columns. Tested for destruction, all works :)

Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/wal/WalWriter.java]: here: https://github.com/questdb/questdb/pull/3304/commits/7193f2eeba3eb1383f26852069b1678d4580d3b0

File: core/src/main/java/io/questdb/cairo/vm/MemoryPMARImpl.java (hunk 16 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/vm/MemoryPMARImpl.java]: done here, it is a little involved change because this memory uses sliding page. It maps/unmaps autonomously. Here: [MemoryPMARImpl.java](https://github.com/questdb/questdb/pull/3304/files/82e8eac6da0f25693d8bd701a86efd752ed80d1d#diff-46c653c0c19aad5d3db44df9a5cc68a2e78af47d1e0e3d1cf9b3d6636c569f8d)

**Comment by bluestreak01** [comment]
@puzpuzpuz @ideoma I think I covered all the comments. Let me know otherwise of if you find anything else

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 289 / 356 (81.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|12|25.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|6|10|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|36|51|70.59%|
|:large_blue_circle:|io/questdb/cairo/wal/CopyWalSegmentUtils.java|10|14|71.43%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|10|14|71.43%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|88|97|90.72%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/Vm.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrameFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrame.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CsvFileIndexer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/FrameAlgebra.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileColumnPool.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|2|2|100.00%|

File: core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java (hunk 10 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java:284]: How big is the latency increase? It shouldn't be very big considering that this method is called only when there are pending column version changes and, even when there are pending changes, the file itself is small.

Using msync/fsync for all metadata files and allowing the user to configure sync for data files seems to be a good tradeoff between power loss stability and an attempt to be fully durable. This will also make the logic easier to follow and document. WDYT?

File: core/src/main/java/io/questdb/cairo/RecoverVarIndex.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/RecoverVarIndex.java:50]: nit: a redundant new line between "columnName" and "partitionNameTxn" arguments is still there. Would be nice to remove it.

File: core/src/main/java/io/questdb/cairo/TxWriter.java (hunk 7 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/TxWriter.java:169]: If we aim for stability in the face of a power loss even with nosync, we should msync/fsync all metadata files. This PR adds a bunch of non-conditional msync/fsync calls for various metadata files, but not this one, so the overall logic seems inconsistent.

Also, it's not uncommon to expose a setting for syncing data files, but having always-on, non-configurable synchronization for metadata files - CH is an example of such an approach.

Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/TxWriter.java:169]: we actually have a benchmark for this, i will post results here

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 290 / 357 (81.23%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|12|25.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|6|10|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|36|51|70.59%|
|:large_blue_circle:|io/questdb/cairo/wal/CopyWalSegmentUtils.java|10|14|71.43%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|10|14|71.43%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|88|97|90.72%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/Vm.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrameFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrame.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CsvFileIndexer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/FrameAlgebra.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileColumnPool.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|2|2|100.00%|

File: core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java (hunk 10 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java:284]: > But as you can see impact on frequent commit is very dramatic.

I wouldn't call 0.3ms dramatic considering that transactions typically include more than a single row. As for stability, as long as we extend column files in a durable way, the DB should recover on startup. Of course, the data might be corrupted which in the case of var-sized columns would mean potential crashes on data access.

Anyway, let's consider this comment to be a nit.

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 290 / 357 (81.23%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|12|25.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|2|5|40.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|6|10|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|36|51|70.59%|
|:large_blue_circle:|io/questdb/cairo/wal/CopyWalSegmentUtils.java|10|14|71.43%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|10|14|71.43%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cairo/ColumnVersionWriter.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/cairo/TxWriter.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|88|97|90.72%|
|:large_blue_circle:|io/questdb/cairo/IndexBuilder.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/Vm.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrameFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/PartitionFrame.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Basket.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CsvFileIndexer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/FrameAlgebra.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LinuxMMLineUdpReceiver.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/AbstractLineProtoUdpReceiver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/MapWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileColumnPool.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|2|2|100.00%|
