### PR TITLE
fix(sql): improve null-handling of `INSERT INTO SELECT` queries that rely on implicit casting

### LINKED ISSUE #5291: Incorrect double null value returned in the select query.
### To reproduce

```
qdb=> create table tab2 (ts timestamp, d double) timestamp(ts);

qdb=>  insert into tab2 select x::timestamp, case when x % 3 = 0 THEN NULL ELSE x%5 END from long_sequence(7);

qdb=> select * from tab2;
             ts             |           d
----------------------------+-----------------------
 1970-01-01 00:00:00.000001 |                   1.0
 1970-01-01 00:00:00.000002 |                   2.0
 1970-01-01 00:00:00.000003 | -9.223372036854776E18
 1970-01-01 00:00:00.000004 |                   4.0
 1970-01-01 00:00:00.000005 |                   0.0
 1970-01-01 00:00:00.000006 | -9.223372036854776E18
 1970-01-01 00:00:00.000007 |                   2.0
```
In which `NULL` value of `d` returned as `-9.223372036854776E18`

### QuestDB version:

Master branch

### OS, in case of Docker specify Docker and the Host OS:

Mac

### File System, in case of Docker specify Host File System:

APFS

### Full Name:

Victor

### Affiliation:

None

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nwoolmer**
`RecordToRowCopier` utils had some copy functions that were not null aware. In one example, a null `LONG` column would be converted to `DOUBLE`. But instead of the `LONG` null value becoming a `Double.NaN`, it stays as min long.

Fixes https://community.questdb.com/t/null-2147483648-or-what-am-i-doing-wrong/807/6

Fixes #5291

### CODE REVIEW

**Comment by jerrinot** [comment]
@coderabbitai review

File: core/src/main/java/io/questdb/griffin/SqlUtil.java [hunk 1]
```diff
@@ -66,6 +66,7 @@
 import static io.questdb.std.datetime.millitime.DateFormatUtils.PG_DATE_MILLI_TIME_Z_FORMAT;
 import static io.questdb.std.datetime.millitime.DateFormatUtils.PG_DATE_Z_FORMAT;
 
+@SuppressWarnings("unused")
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlUtil.java]: lets suppress method by method instead, which would include comments as to why method is suppressed

File: core/src/main/java/io/questdb/cairo/ColumnType.java [hunk 2]
```diff
@@ -650,8 +655,10 @@ private static boolean isImplicitParsingCast(int fromType, int toType) {
 
     private static boolean isNarrowingCast(int fromType, int toType) {
         return (fromType == DOUBLE && (toType == FLOAT || (toType >= BYTE && toType <= LONG)))
-                || (fromType == FLOAT && toType >= BYTE && toType <= LONG)
+                || (fromType == FLOAT && ((toType >= BYTE && toType <= LONG) || toType == DATE || toType == TIMESTAMP))
```
Comment (jerrinot) [inline core/src/main/java/io/questdb/cairo/ColumnType.java]: This should include also `TIMESTAMP_NANO`. or - better(?) - `ColType.isTimestamp()`

File: core/src/main/java/io/questdb/cairo/ColumnType.java [hunk 3]
```diff
@@ -650,8 +655,10 @@ private static boolean isImplicitParsingCast(int fromType, int toType) {
...
                 || (fromType == LONG && toType >= BYTE && toType <= INT)
+                || (fromType == DATE && toType >= BYTE && toType <= INT)
+                || (fromType == TIMESTAMP && ((toType >= BYTE && toType <= INT) || toType == DATE))
```
Comment (jerrinot) [inline core/src/main/java/io/questdb/cairo/ColumnType.java]: the same issue - this won't work for nano timestamps

File: core/src/test/java/io/questdb/test/griffin/UnionTest.java [hunk 4]
```diff
@@ -271,6 +271,126 @@ public void testNestedSetOperationWithOrderExpressionByAndLimit2() throws Except
...
+                    "foo;",
+                    "ts###ASC",
+                    true,
+                    true
+            );
+        });
+    }
+
+    @Test
+    public void testNullConversionsFromTimestamp() throws Exception {
```
Comment (jerrinot) [inline core/src/test/java/io/questdb/test/griffin/UnionTest.java:375]: all these tests should use nanos too. 

```java
    @Test
    public void testNullConversionsFromNanoTimestamp() throws Exception {
        assertMemoryLeak(() -> {
            execute("CREATE TABLE foo (ts TIMESTAMP, colA DOUBLE, colB FLOAT, colC DATE, colD LONG, colE INT) timestamp(ts) PARTITION BY DAY WAL;");
            execute("INSERT INTO foo (ts, colA, colB, colC, colD, colE) " +
                    "SELECT '2025-04-09 17:20:00.000' AS ts, " +
                    "null::timestamp_ns as colA, " +
                    "null::timestamp_ns as colB, " +
                    "null::timestamp_ns as colC, " +
                    "null::timestamp_ns as colD, " +
                    "null::timestamp_ns as colE;");
            drainWalQueue();

            assertQueryNoLeakCheck(
                    "ts\tcolA\tcolB\tcolC\tcolD\tcolE\n" +
                            "2025-04-09T17:20:00.000000Z\tnull\tnull\t\tnull\tnull\n",
                    "foo;",
                    "ts###ASC",
                    true,
                    true
            );
        });
    }
```
fails with
```
	at io.questdb.griffin.SqlException.position(SqlException.java:132)
	at io.questdb.griffin.SqlException.$(SqlException.java:51)
	at io.questdb.griffin.SqlException.inconvertibleTypes(SqlException.java:85)
	at io.questdb.griffin.SqlCompilerImpl.compileInsertAsSelect(SqlCompilerImpl.java:2659)
	at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:3174)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:2496)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:356)
```

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 40 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|18|18|100.00%|

**Review by jerrinot — APPROVED** [review]

**Comment by nwoolmer** [comment]
Thanks @jerrinot!

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 40 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|18|18|100.00%|
