### PR TITLE
fix(sql): fix spurious "unsupported operation" errors

### LINKED ISSUE #4627: Unexpected Filter error
### To reproduce

Go to the demo box and run this:

select * from trades WHERE
timestamp = (select max(timestamp) from trades)
It produces this error:

2024-05-27T16:58:42.779066Z E i.q.c.s.a.PageFrameReduceJob reduce error [ex=
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.functions.CursorFunction.getLong(CursorFunction.java:123)
	at io.questdb.griffin.engine.functions.eq.EqLongFunctionFactory$Func.getBool(EqLongFunctionFactory.java:58)
	at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.filter(AsyncFilteredRecordCursorFactory.java:230)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:243)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:190)
	at io.questdb.cairo.sql.async.PageFrameReduceJob.run(PageFrameReduceJob.java:152)
	at io.questdb.mp.Worker.run(Worker.java:151)
]

### QuestDB version:

7.3.4-snapshot (demo box)

### OS, in case of Docker specify Docker and the Host OS:

windows

### File System, in case of Docker specify Host File System:

dunno

### Full Name:

Sibsankar Maity

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #4628: Implicit JOIN involving CTE returns wrong results
### To reproduce

Run this on demo:
```sql
WITH max_ts AS (SELECT max(timestamp) ts FROM trades)
SELECT *
FROM trades, max_ts
WHERE trades.timestamp = max_ts.ts;
```
and observe the full trades table in the result set.

EXPLAIN returns this:
```
DataFrame
      Row forward scan
          Frame forward scan on: trades
```

### QuestDB version:

8.0

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #4772: SQL with `count(constant)` are unreasonably slow
### To reproduce

on demo:

```sql
select count(2) from trips;
-- vs
select count() from trips;
```

compare the execution plans

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

any

### File System, in case of Docker specify Host File System:

any

### Full Name:

V

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #4775: Slow performance of non-exact matching on Symbol columns
### To reproduce

Attempting to filter a Symbol column with non-exact filters like regex, like, or ilike currently does not use the column index and executes very slowly.

Running the below on the public demo instance:
```sql
SELECT timestamp, symbol FROM trades WHERE symbol ~ '^BTC-.+$' AND timestamp in '2024';
```
The execution time is about 2s. This scales pretty much linearly if we looked at more records.

Running the equivalent with an exact match:
```sql
SELECT timestamp, symbol FROM trades WHERE symbol IN ('BTC-USD', 'BTC-USDT') AND timestamp in '2024';
```
returns the results in ~250ms

However, even if we try to guide the calculation by first finding the unique symbols that satisfy the regex, the optimizer appears to re-write the query to scan the full table.

```sql
SELECT timestamp, symbol FROM trades WHERE symbol IN (
    SELECT symbol FROM (
        SELECT symbol FROM trades GROUP BY symbol
        )
    WHERE symbol ~ '^BTC-.+$'
) AND timestamp IN '2024';
```
This runs even slower than the original query and actually times out on the demo instance.

Looking at the query plan, it appears that the statement has been optimized to remove the first unique symbol selection and is instead running the regex filter across the full table.
image

### QuestDB version:

8.0.1

### OS, in case of Docker specify Docker and the Host OS:

Public demo instance

### File System, in case of Docker specify Host File System:

Public demo instance

### Full Name:

Oliver Zhu

### Affiliation:

BRG

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #4776: `count_distinct(null)` breaks
### To reproduce

```sql
select count_distinct(null) from trips;
```

```
2024-07-15T16:13:27.615848Z C i.q.c.h.p.JsonQueryProcessorState [3480] internal error [ex=
java.lang.IllegalArgumentException: Unexpected function type: unknown
	at io.questdb.cairo.RecordSinkFactory.getInstance(RecordSinkFactory.java:627)
	at io.questdb.cairo.RecordSinkFactory.getInstance(RecordSinkFactory.java:70)
	at io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory.<init>(GroupByRecordCursorFactory.java:73)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectGroupBy(SqlCodeGenerator.java:3840)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:3181)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2755)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2743)
	at io.questdb.griffin.SqlCodeGenerator.generateSubQuery(SqlCodeGenerator.java:4595)
	at io.questdb.griffin.SqlCodeGenerator.generateSelectGroupBy(SqlCodeGenerator.java:3475)
	at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:3181)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2755)
	at io.questdb.griffin.SqlCodeGenerator.generateQuery(SqlCodeGenerator.java:2743)
	at io.questdb.griffin.SqlCodeGenerator.generate(SqlCodeGenerator.java:270)
	at io.questdb.griffin.SqlCompilerImpl.generateFactory(SqlCompilerImpl.java:3018)
	at io.questdb.griffin.SqlCompilerImpl.generateWithRetries(SqlCompilerImpl.java:3031)
	at io.questdb.griffin.SqlCompilerImpl.compileUsingModel(SqlCompilerImpl.java:1578)
	at io.questdb.griffin.SqlCompilerImpl.compileInner(SqlCompilerImpl.java:1541)
	at io.questdb.griffin.SqlCompilerImpl.compile(SqlCompilerImpl.java:235)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compile(SqlCompilerPool.java:128)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:479)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:191)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:272)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:915)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:256)
	at io.questdb.cutlass.http.HttpServer.handleClientOperation(HttpServer.java:307)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:114)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:118)
	at io.questdb.mp.Worker.run(Worker.java:151)
, q=`select count_distinct(null) from trips`]
```

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

any

### File System, in case of Docker specify Host File System:

any

### Full Name:

Vlad Ilyushchenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #4777: `select count(null)` produces error
### To reproduce

```sql
select count(null) from trips
```

The behaviour is for all types `null` can be cast to, e.g. 

```sql
select count(null::double) from trips
```

it should produce 0 value.

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

any

### File System, in case of Docker specify Host File System:

any

### Full Name:

Vlad Ilyushchenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### LINKED ISSUE #4778: SQL is non-reentrant
### To reproduce

```sql
create table zyzy as (
  select 
  timestamp_sequence(1,1000) ts,
  rnd_int(0,5,0) a,
  rnd_int(0,5,0) b,
  rnd_int(0,5,0) c,
  rnd_int(0,5,0) x,
  rnd_int(0,5,0) y,
  rnd_int(0,5,0) z,
  from long_sequence(100)
) timestamp(ts);

select a+b*c x, sum(z)+25 ohoh from zyzy where a in (x,y) and b = 3 latest on ts partition by x;
```

Run the `select` SQL twice in a row. Non-cached SQL executes fine, cached SQL breaks.

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

any

### File System, in case of Docker specify Host File System:

any

### Full Name:

Vlad Ilyushchenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
fixes #4627
fixes #4628
fixes #4772
fixes #4777
fixes #4776
fixes #4778
fixes #4775

### Improve ergonomics of error responses around expression compilation:

```sql
query_activity where not 'blah';
```

demo (the expected type is quite random and is unhelpful on functions with large overload list):
```
unexpected argument for function: not. expected args: (BOOLEAN). actual args: (STRING constant)
```

branch:
```
there is no matching operator `not` with the argument type: STRING constant
```

```sql
query_activity where  'blah'::varchar + true;
```

demo:
```
unexpected argument for function: +. expected args: (INT,INT). actual args: (VARCHAR constant,BOOLEAN constant)
```

branch:
```
there is no matching operator`+` with the argument types: VARCHAR constant + BOOLEAN constant
```

### Changes NULL behaviour

- `NULL` and `NaN` are the same thing, `NaN` should not be used.
- creating table with `NULL` type is disallowed, e.g. this SQL will produce an error:

```sql
create table bb as (select null x);
-- cannot create NULL-type column, please use type cast, e.g. b::type
```

The workaround is to type cast null to a desired type:

```sql
create table bb as (select null::varchar x);
```

Unfortunately in tests, we relied on creating tables with "undefined" type to test the `UNION`. I have to rework these tests.

To-do's:

- [x] remove most manual type overloads in favour of `ColumnType.OVERLOAD_PRIORITY`
- [x] make `ColumnType.OVERLOAD_PRIORITY` the source of truth
- [x] make `timestamp = symbol` work consistently
- [x] make `symbol = long` work consistently (jit was ok with this, java wasn't)
- [x] work out why we default to string,string when timestamp,cursor is not found
- [x] test for new `symbol=long` function
- [ ] test `timestamp = symbol` runtime behaviour (when row in the middle fails to parse timestamp)

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 81 / 109 (74.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 151 / 186 (81.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 346 / 445 (77.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|62|68|91.18%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 381 / 481 (79.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|62|68|91.18%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 433 / 537 (80.63%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|62|68|91.18%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|48|52|92.31%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 433 / 537 (80.63%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|62|68|91.18%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|48|52|92.31%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|4|4|100.00%|

File: core/src/main/java/io/questdb/cairo/sql/PageFrame.java [hunk 1]
```diff
@@ -30,6 +30,14 @@ public interface PageFrame {
 
     BitmapIndexReader getBitmapIndexReader(int columnIndex, int dirForward);
 
+    /**
+     * The count of columns in the page frame. In some cases it is possible to have
+     * page fame with no columns.
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/sql/PageFrame.java:35]: nit:
```suggestion
     * page frame with no columns.
```

File: core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceTask.java [hunk 2]
```diff
@@ -184,6 +184,7 @@ public void resetCapacities() {
     }
 
     public void setErrorMsg(Throwable th) {
+        th.printStackTrace();
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceTask.java:187]: This looks like debug leftover.

File: core/src/main/java/io/questdb/griffin/FunctionParser.java [hunk 3]
```diff
@@ -619,9 +710,9 @@ private Function createFunction(
                 return checkAndCreateFunction(factory, args, argPositions, node, configuration);
             }
 
-            if (candidateDescriptor == null) {
-                candidateDescriptor = descriptor;
-            }
+//            if (candidateDescriptor == null) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/FunctionParser.java:713]: Looks like a leftover.

**Review by puzpuzpuz — COMMENTED** [review]
Leaving intermediate feedback.

File: core/src/main/java/io/questdb/griffin/FunctionParser.java (hunk 3 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/FunctionParser.java:713]: removed in https://github.com/questdb/questdb/pull/4632/commits/a27f01594461930d022aac04163dce85937301b9

File: core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceTask.java (hunk 2 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceTask.java]: removed in https://github.com/questdb/questdb/pull/4632/commits/a27f01594461930d022aac04163dce85937301b9

File: core/src/main/java/io/questdb/griffin/FunctionParser.java [hunk 4]
```diff
@@ -691,49 +777,7 @@ private Function createFunction(
                         }
 
                         sigArgTypeScore += overloadDistance;
-                        // Overload with cast to higher precision
                         overloadPossible = overloadDistance != ColumnType.OVERLOAD_NONE;
-
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/FunctionParser.java:696]: these are cast hacks we had, they are ad-hoc. I moved them all into a single table, controlled by `ColumnType.OVERLOAD_PRIORITY` - this is the name of the PR originally

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java [hunk 5]
```diff
@@ -53,15 +52,6 @@ public Function newInstance(
             CairoConfiguration configuration,
             SqlExecutionContext sqlExecutionContext
     ) throws SqlException {
-        final Function arg = args.getQuick(0);
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java:56]: `count(constant)` is erased in the optimiser, it is unnecessary to handle constant in "count" functions anymore

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java [hunk 6]
```diff
@@ -59,22 +60,22 @@ public Function newInstance(
         CharSequence regex = args.getQuick(1).getStrA(null);
 
         if (regex == null) {
-            throw SqlException.$(argPositions.getQuick(1), "NULL regex");
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java:62]: duckdb allows `null` in regex and doesn't error out unlike us. I aligned our behaviour with duck.

File: core/src/main/java/io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java [hunk 7]
```diff
@@ -74,11 +74,11 @@ public void aggregate(long address, long addressSize, int columnSizeHint, int wo
     }
 
     @Override
-    public boolean aggregate(long pRosti, long keyAddress, long valueAddress, long valueAddressSize, int columnSizeShr, int workerId) {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java:77]: API clean up, we really used to pass two parameters just to get to the "row count"

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java [hunk 8]
```diff
@@ -52,6 +54,7 @@ public LatestByAllFilteredRecordCursorFactory(
     ) {
         super(metadata, dataFrameCursorFactory, configuration);
         try {
+            this.filter = filter;
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java:57]: this was the bugfix. Filter must never be closed by the cursor, otherwise cursor is not reusable

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 477 / 582 (81.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|11|16|68.75%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|49|53|92.45%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|68|68|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexUtils.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java [hunk 9]
```diff
@@ -0,0 +1,176 @@
...
+import io.questdb.griffin.SqlExecutionContext;
+import io.questdb.griffin.engine.functions.BooleanFunction;
+import io.questdb.griffin.engine.functions.SymbolFunction;
+import io.questdb.griffin.engine.functions.UnaryFunction;
+import io.questdb.std.IntList;
+import io.questdb.std.ObjList;
+
+import java.util.regex.Matcher;
+
+public class MatchSymbolFunctionFactory implements FunctionFactory {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java:44]: We should introduce a similar factory for LIKE/ILIKE over symbols.

File: core/src/main/java/io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java [hunk 10]
```diff
@@ -60,9 +60,9 @@ public AvgDoubleVectorAggregateFunction(int keyKind, int columnIndex, int worker
     }
 
     @Override
-    public void aggregate(long address, long addressSize, int columnSizeHint, int workerId) {
+    public void aggregate(long address, long frameRowCount, int workerId) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java:63]: Nice change here! That frame row count calculation based on the size in bytes was silly.

File: core/src/main/java/io/questdb/griffin/SqlExecutionContext.java [hunk 11]
```diff
@@ -204,5 +204,9 @@ default void storeTelemetry(short event, short origin) {
 
     void setCacheHit(boolean value);
 
+    void setJitUsed(boolean value);
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlExecutionContext.java:207]: it is used from QueryProgress where factory is not always readily available and it is a convenience thing (see QueryProgress - prod code)

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 12]
```diff
@@ -3798,6 +3798,41 @@ private ExpressionNode rewriteAggregate(ExpressionNode agg, QueryModel model) {
         return agg;
     }
 
+    // This rewrite should be invoked before the select rewrite!
+    // Rewrites the following:
+    // select count(constant) ... -> select count() ...
+    // select count(column) ... -> select count(), ... from ... where column is not null
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java:3804]: nope, good spot!

File: core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java [hunk 13]
```diff
@@ -0,0 +1,205 @@
...
+        if (ColumnType.isNull(fn0.getType())) {
+            if (longFn.isConstant()) {
+                return longFn.getLong(null) == Numbers.LONG_NULL ? BooleanConstant.TRUE : BooleanConstant.FALSE;
+            }
+            return new EqLongNullFunction(longFn);
+        }
+
+        final SymbolFunction symFn = (SymbolFunction) fn0;
+        if (longFn.isConstant()) {
+            final String constValue = Long.toString(longFn.getLong(null));
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java:82]: good spot, gap in tests too

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 480 / 585 (82.05%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|43|63|68.25%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|11|16|68.75%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|49|53|92.45%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|68|68|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastVarcharToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexUtils.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlOptimiser.java]: fixed in https://github.com/questdb/questdb/pull/4632/commits/64d0f368bd186fd8eb50a9857da3f1d27fef12d9

File: core/src/main/java/io/questdb/griffin/engine/QueryProgress.java [hunk 14]
```diff
@@ -67,6 +67,7 @@ public static void logEnd(long sqlId, CharSequence sqlText, SqlExecutionContext
                 .$(", sql=`").utf8(sqlText).$('`')
                 .$(", principal=").$(executionContext.getSecurityContext().getPrincipal())
                 .$(", cache=").$(executionContext.isCacheHit())
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/QueryProgress.java:69]: fixed in https://github.com/questdb/questdb/pull/4632/commits/c59412f20a8c77b256546fead77394d2bf963429

File: core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java]: fixed in https://github.com/questdb/questdb/pull/4632/commits/c59412f20a8c77b256546fead77394d2bf963429 and added tests

File: core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java [hunk 15]
```diff
@@ -0,0 +1,205 @@
...
+        }
+
+        @Override
+        public Function getArg() {
+            return arg;
+        }
+
+        @Override
+        public boolean getBool(Record rec) {
+            return negated != Chars.equalsNc(arg.getSymbol(rec), constant);
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java]: fixed in https://github.com/questdb/questdb/pull/4632/commits/c59412f20a8c77b256546fead77394d2bf963429

File: core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java [hunk 16]
```diff
@@ -0,0 +1,205 @@
...
+            super(symFn, longFn);
+        }
+
+        @Override
+        public boolean getBool(Record rec) {
+            long value = right.getLong(rec);
+            if (value != Numbers.LONG_NULL) {
+                sink.clear();
+                sink.put(value);
+                return negated != Chars.equalsNc(left.getSymbol(rec), sink);
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java]: fixed in https://github.com/questdb/questdb/pull/4632/commits/691e172c653339dd4975ce2bd45bf58a9c1d11a0

File: core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java [hunk 17]
```diff
@@ -0,0 +1,102 @@
...
+        Function timestampFn = args.getQuick(1);
+
+        if (timestampFn.isConstant()) {
+            return symbolTimestampEpoch == timestampFn.getLong(null) ? BooleanConstant.TRUE : BooleanConstant.FALSE;
+        }
+
+        return new variableTimestampFunction(fn0, timestampFn, symbolTimestampEpoch);
+    }
+
+    private static class variableTimestampFunction extends AbstractEqBinaryFunction {
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java]: renamed here https://github.com/questdb/questdb/pull/4632/commits/7e8ff8fb120f5f6bac0428fb0e6dc343d81705bb

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java [hunk 18]
```diff
@@ -80,42 +81,53 @@ public Function getArg() {
 
         @Override
         public boolean getBool(Record rec) {
-            CharSequence cs = getArg().getStrA(rec);
-            return cs != null && matcher.reset(cs).find();
+            if (matcher != null) {
+                CharSequence cs = getArg().getStrA(rec);
+                return cs != null && matcher.reset(cs).find();
+            }
+            return false;
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java]: done here https://github.com/questdb/questdb/pull/4632/commits/812f6a52b91bd15dbe6ed42ea01344f9468d6cfa

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java [hunk 19]
```diff
@@ -0,0 +1,176 @@
...
+        }
+
+        @Override
+        public Function getArg() {
+            return symbolFun;
+        }
+
+        @Override
+        public boolean getBool(Record rec) {
+            return symbolKeys.binarySearchUniqueList(getArg().getInt(rec)) > -1;
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java]: done in https://github.com/questdb/questdb/pull/4632/commits/96b09fae3a97c2f3456d769cad4207615b26a312

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 487 / 593 (82.12%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|44|64|68.75%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|11|16|68.75%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|58|63|92.06%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|14|15|93.33%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|68|68|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastVarcharToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexUtils.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java [hunk 20]
```diff
@@ -288,6 +294,11 @@ public void setJitMode(int jitMode) {
         this.jitMode = jitMode;
     }
 
+    @Override
+    public void setJitUsed(boolean value) {
+        jitUsed = true;
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java:299]:
```suggestion
        jitUsed = value;
```

File: core/src/main/java/io/questdb/griffin/SqlExecutionContext.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/SqlExecutionContext.java:207]: Yes, I've noticed the use case. Yet, nothing in the prod code ever sets `jitUsed` to `true`, so this flag seems to be not working as intended.

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 21]
```diff
@@ -4698,8 +4699,6 @@ private RecordCursorFactory generateTableQuery0(
                     columnIndexes.add(readerTimestampIndex);
                     columnSizes.add((Numbers.msb(ColumnType.TIMESTAMP)));
                 }
-            } else {
-                framingSupported = false;
```
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4702]: i have no idea why. Framing will disable parallel execution unnecessarily when columns are not required. For example function that act on constants are not executed in parallel either. This is how i found it.

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java (hunk 9 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java:43]: lets do it when someone asked, this PR also missed NoMatchSymbol etc. PR is already massive (and useful)

File: core/src/main/java/io/questdb/griffin/SqlExecutionContext.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlExecutionContext.java:207]: ok, i got it, this is a bug. I will fix. We're not reporting JIT status from query progress.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 521 / 632 (82.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|44|64|68.75%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|11|16|68.75%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/TouchTableFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|58|63|92.06%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|14|15|93.33%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|68|68|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastVarcharToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastFloatToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexUtils.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java (hunk 20 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java]: not needed, fixed here https://github.com/questdb/questdb/pull/4632/commits/f6400def4728be8e8270a8a2f8d0b1171942ff2a

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java (hunk 5 above)
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java:56]: i think i did put comment into one, there are a lot of factories!

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java (hunk 21 above)
[the remark this answers is not in the document]
Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:4702]: removed in https://github.com/questdb/questdb/pull/4632/commits/e044e51cfacdb0469bca4cec6226284193ae9981

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java (hunk 9 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java:43]: We already have a request from the user who wanted to store complex patterns in a single symbol column. I'll create a GH issue to track this.

Comment (bluestreak01) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java:43]: sure, thanks! In the mean time the workaround is to use regexp

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java:43]: Here it is: #4790

**Review by puzpuzpuz — APPROVED** [review]
Epic PR!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 530 / 639 (82.94%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|45|88|51.14%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinShortVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymLongFunctionFactory.java|44|64|68.75%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|11|16|68.75%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqSymTimestampFunctionFactory.java|16|20|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/TouchTableFunctionFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchSymbolFunctionFactory.java|58|63|92.06%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|73|79|92.41%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/MatchStrFunctionFactory.java|14|15|93.33%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqTimestampCursorFunctionFactory.java|68|68|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountFloatGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/QueryProgress.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDoubleGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountVarcharGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/NotMatchStrFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIPv4GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastVarcharToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStrGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastFloatToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexUtils.java|1|1|100.00%|
