### PR TITLE
fix(sql): fix duplicate column error for implicit timestamp

### LINKED ISSUE #3893: SQL syntax error reported as a critical error
### Describe the bug

2023-10-26T15:02:27.722568Z C i.q.c.h.p.JsonQueryProcessorState [224] error [msg=`Duplicate column [name=timestamp]`, errno=-100, q=`SELECT avg(column0), column1 timestamp FROM table 
  WHERE timestamp >= '2023-08-22T09:40:00.000000Z' AND timestamp <= '2023-08-22T09:45:00.000000Z' 
  AND column1 IN ('CODE')
  SAMPLE BY 15s FILL(PREV) ALIGN TO CALENDAR
`]

### To reproduce

```sql 
create table test as (select 'sym', 'str', x, 'a', timestamp_sequence('2023-07-20', 1000000) timestamp from long_sequence(200)) timestamp(timestamp);
select min(x), sym timestamp from test sample by 15s;
```
_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixed #3893

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|15|15|100.00%|

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 1]
```diff
@@ -2895,7 +2896,31 @@ private RecordCursorFactory generateSelectChoose(QueryModel model, SqlExecutionC
...
+                    // avoid clashing with other columns using timestamp column name as alias
+                    StringSink sink = Misc.getThreadLocalSink();
+                    sink.put(colMetadata.getName());
+                    int len = sink.length();
+                    int sequence = 0;
+
+                    do {
+                        sink.trimTo(len);
+                        sink.put(sequence++);
+                    } while (selectMetadata.getColumnIndexQuiet(colMetadata.getName()) < 0);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:2911]: Should it be instead?
```suggestion
                    } while (selectMetadata.getColumnIndexQuiet(sink) > -1);
```

I don't understand how this code is covered by tests...

Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java]: You're right. I forgot to change this expression and test worked because there was no column to clash with 'timestamp0' .
Thanks for catching this !
Fixed in latest commit.

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|15|15|100.00%|
