### PR TITLE
fix(sql): add single quotes escaping within string literals

### LINKED ISSUE #2309: Inserting a escaped single quote via Postgres wire protocol breaks
### Describe the bug

A user found this issue and [reported on stackoverflow](https://stackoverflow.com/questions/72936321/escaping-single-quote-in-questdb-using-python3) when using psycopg2, but you can also try this on the QuestDB console directly

```
CREATE TABLE IF NOT EXISTS mytable (mystring STRING)
INSERT INTO 'mytable' (mystring) VALUES ('o''brian');
```

According to the [postgres docs](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE), the correct way of escaping the single quote is duplicating it

### To reproduce

Go to your local QuestDB console and run

```
CREATE TABLE IF NOT EXISTS mytable (mystring STRING)
INSERT INTO 'mytable' (mystring) VALUES ('o''brian');
```

### Expected Behavior

Row should be inserted without any issues

### Environment

```markdown
- **QuestDB version**: 6.4.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2309

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|6|6|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|6|6|100.00%|

File: core/src/main/java/io/questdb/std/GenericLexer.java [hunk 1]
```diff
@@ -257,15 +257,23 @@ public CharSequence next() {
                 case '\'':
                     if (c == '\'') {
                         _hi += 2;
-                        return last = flyweightSequence;
+                        if (hasNext() && content.charAt(_pos) == '\'') {
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/std/GenericLexer.java:260]: `hasNext()` call is quite heavy in this context, it can be replaced with `_pos < _len`. In fact `while(hasNext())` is also too heavy

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|7|7|100.00%|
