### PR TITLE
test(http): fix flaky testPeerIsSlowToReadPar()

### LINKED ISSUE #3952: flaky test: MetricsIODispatcherTest.testPeerIsSlowToReadPar()
### Describe the bug

build: windows-other
logs: https://gist.github.com/jerrinot/03dbb7ae2d35312abc291ea9bf97f989

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
The test is aggressively parallel + intentionally use small buffers. It fails on CI hiccup. I can reproduce the failure locally with a decreased timeout. Hence increasing the timeout should make the test more stable.

fixes #3952

### CODE REVIEW

**Comment by jerrinot** [comment]
@coderabbitai review please, be careful, it's super long!

File: core/src/test/java/io/questdb/test/cutlass/http/MetricsIODispatcherTest.java [hunk 1]
```diff
@@ -281,7 +281,7 @@ private void testPrometheusScenario(int metricCount, int tcpSndBufSize, int send
 
                         utf16Sink.clear();
                         Fragment fragment;
-                        while ((fragment = chunkedResponse.recv(5_000)) != null) {
+                        while ((fragment = chunkedResponse.recv(15_000)) != null) {
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/test/cutlass/http/MetricsIODispatcherTest.java]: why is there timeout at all?
