### PR TITLE
fix(sql): fix NPE when distinct query contains columns with dependencies.

### LINKED ISSUE #6078: Column alias references fails when DISTINCT is used
### To reproduce

This query works (can be tested on demo.questdb.io)

```
select  distinct market_data.bids[1,-1] as b, market_data.bids[1,-1] - 1 from market_data;
```

This query also works, where I am removing distinct and accessing one pre-existing column by its alias
```
select    market_data.bids[1,-1] as b, b - 1 from market_data;
```

But it breaks with `distinct`. I get `invalid column b`
```
select  distinct  market_data.bids[1,-1] as b, b - 1 from market_data;
```

### QuestDB version:

9.0.2

### OS, in case of Docker specify Docker and the Host OS:

both linux and osx

### File System, in case of Docker specify Host File System:

ext4 and zfs

### Full Name:

javier

### Affiliation:

questdb

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kafka1991**
Try to close #6078 
```
select distinct x1 as a, a from tab1;
ERROR:  Cannot invoke "io.questdb.griffin.model.QueryColumn.getAst()" because "thatColumn" is null
LINE 1: select distinct x1 as a, a from tab1;
```

### CODE REVIEW

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by kafka1991** [comment]
@coderabbitai review

File: core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java [hunk 1]
```diff
@@ -3913,8 +3915,8 @@ private RecordCursorFactory generateSampleBy(
                         false,
                         groupByFunctions,
                         groupByFunctionPositions,
-                        outerProjectionFunctions,
-                        innerProjectionFunctions,
+                        tempOuterProjectionFunctions,
```
Comment (bluestreak01) [inline core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:3918]: nit: it would be good to clear these collections on exit from `generateSampleBy()` method

Comment (kafka1991) [reply core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java:3918]: fixed.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|

**Review by bluestreak01 — APPROVED** [review]
