### PR TITLE
fix(sql): non-deterministic function not rejected when creating materialized view

### LINKED ISSUE #5645: Non-deterministic SQL functions are not banned in materialized views
### To reproduce

Filters like `WHERE timestamp in today()` are accepted in mat view queries while they should lead to `Non-deterministic column` SQL error.

### QuestDB version:

8.3.1

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #5645

**Important note**: if a materialized view with non-deterministic SQL function, e.g. `now()` or `today()`, was created on 8.3.1 or older version, with this change it'll be marked as invalid on the first refresh. This is expected since non-deterministic functions were never supported by incrementally refreshed materialized views.

Also, changes `FunctionParser` to keep parallel filters enabled when compiling cursor functions, e.g. IN operator for symbol. Disabling parallel filters is no longer need since #5445 changed the functions to execute the sub-query in `Function#init()`.

### CODE REVIEW

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 16 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/mv/MatViewRefreshExecutionContext.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|0|2|00.00%|

File: core/src/main/java/io/questdb/cairo/mv/MatViewRefreshExecutionContext.java [hunk 1]
```diff
@@ -104,6 +104,11 @@ public TableReader getReader(TableToken tableToken) {
         return getCairoEngine().getReader(tableToken);
     }
 
+    @Override
+    public boolean isDeterministic() {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/mv/MatViewRefreshExecutionContext.java:108]: nit: I'd make it the same naming as functions with non-deterministic wording, e.g. `allowNonDeterministic`. The default value of `true` is also more obvious for `allow` property.

File: core/src/main/java/io/questdb/griffin/FunctionParser.java [hunk 2]
```diff
@@ -579,6 +579,9 @@ private Function checkAndCreateFunction(
                     .I$();
             Misc.freeObjList(args);
             throw SqlException.position(position).put("bad function factory (NULL), check log");
+        } else if (sqlExecutionContext.isDeterministic() && function.isNonDeterministic()) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/FunctionParser.java:582]: nit: this doesn't look very clear with the current naming pattern.

**Review by ideoma — APPROVED** [review]

File: core/src/main/java/io/questdb/cairo/mv/MatViewRefreshExecutionContext.java (hunk 1 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cairo/mv/MatViewRefreshExecutionContext.java]: Renamed in 245eb3b35c7cc5589c94c1384105ea28d71b7061

File: core/src/main/java/io/questdb/griffin/FunctionParser.java (hunk 2 above)
Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/FunctionParser.java]: Improved in 245eb3b35c7cc5589c94c1384105ea28d71b7061

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 18 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/mv/MatViewRefreshExecutionContext.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|3|3|100.00%|

**Comment by puzpuzpuz** [comment]
@ideoma could you take one more looks at this one?

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 22 / 24 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/mv/MatViewRefreshExecutionContext.java|7|8|87.50%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|3|3|100.00%|
