### PR TITLE
fix(core): fix hour parsing and formatting in the 1-12 and 1-24 conventions

### LINKED ISSUE #4502: Error while parsing timestamps with times between midnight and 1am formatted in the 12-hour clock convention
### To reproduce

This test fails:
```java
@Test
public void test12HourClockAfterMidnight() throws Exception {
  DateFormat fmt = compiler.compile("MM/dd/yyyy HH:mm:ss a", false);
  long millis = fmt.parse("04/07/2018 12:30:00 AM", defaultLocale);
}
```

QuestDB expects hours in timestamps in the 12-hour clock system [to be between 00 - 11](https://github.com/questdb/questdb/blob/5040317b68094c5a1c40aa64d102e02805fe1530/core/src/main/java/io/questdb/std/datetime/millitime/DateFormatUtils.java#L211)
. 
It interprets 00:01 AM as one minute after midnight. However, the usual way to format 1 minute after midnight is 12:01 AM and not 00:01 AM. The 12-hour clock transitions from 12:59 AM to 01:00 AM. 🤯 

It sounds counter-intuitive, the transition 1 hour after midnight looks abrupt. but it makes sense if you think about good ol' analog clock. See: https://en.wikipedia.org/wiki/12-hour_clock

A fix should change:
1. both the generic DateFormat parser and the specialized compiler
2. also the reverse part: timestamp printing

### QuestDB version:

7.4.2

### OS, in case of Docker specify Docker and the Host OS:

irrelevant

### File System, in case of Docker specify Host File System:

irrelevant

### Full Name:

Jaromir  Hamala

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
The `hh` pattern stands for 'Hour in am/pm (1-12)'. The original parser implementation was subtracting 1 and a formatter was adding 1. 

As a result, it parsed e.g. 05:00 as if it was 04:00, which is wrong. But when converted back to a string (with the same pattern) it was formatted correctly - displaying `05:00` again. Thus the bug was not immediately visible. I assume it was an attempt to convert a 1-based indexing into a 0-based indexing. But clocks are not that simple. The 12-hour system with the 1-12 convention goes like this: 12am (midnight), 1am, 2am, 3am, ..... 11am, 12pm (noon), 1pm, 2pm, ... 11pm and then wraps over to 12am (midnight) of the new day. 

The same problem was with the `kk` - `Hour in day (1-24)` pattern. It was also subtracting 1 during parsing and adding one when formatting. 

Implementation notes: 
There is little difference between 0-11 and 1-12 schemes. The only difference is that the 1-12 scheme uses `12` for noon and midnight whereas the 0-11 scheme uses `0` for noon and midnight. All other hour values are the same. We use this property to simplify the code parsing: We parse both 0-11 and 1-12 by using the same code. Later, when constructing a `long` timestamp, we treat 12 as if it was 0. Regardless of the 0-11 vs 1-12 scheme. One side effect is that the parser is somewhat more relaxed: Even when a parser is configured with the 0-11 it will still accept `12` as an hour value. I don't think it can cause issues in practice, except for possible compatibility issues if we ever decide to make it stricter again. 

This change also adds tests comparing both `hh` and `kk` patterns with a reference `SimpleDateFormat` from JDK.

Fixes #4502

### CODE REVIEW

**Comment by jerrinot** [comment]
there seems to be the same problem with the `k` pattern: Hour in day (1-24).

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 35 / 37 (94.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatUtils.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/GenericDateFormat.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/GenericTimestampFormat.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 29 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/datetime/millitime/GenericDateFormat.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/GenericTimestampFormat.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatUtils.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 57 / 57 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/datetime/millitime/GenericDateFormat.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatCompiler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/GenericTimestampFormat.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatUtils.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatCompiler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|21|21|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 57 / 57 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/datetime/millitime/GenericDateFormat.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatCompiler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/GenericTimestampFormat.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatUtils.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/TimestampFormatCompiler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|21|21|100.00%|

File: core/src/test/java/io/questdb/test/std/datetime/millitime/DateFormatCompilerTest.java [hunk 1]
```diff
@@ -155,6 +184,21 @@ public void testFormatEra() throws Exception {
         assertFormat("BC", "G", "-1024-04-09T00:00:00.000Z");
     }
 
+    @Test
+    public void testFormatFirstHourIn12HourClock() throws Exception {
+        assertFormat("04/09/2017 00:01:00 am", "MM/dd/yyyy KK:mm:ss a", "2017-04-09T00:01:00.000Z");
+        assertFormat("04/09/2017 00:59:59 am", "MM/dd/yyyy KK:mm:ss a", "2017-04-09T00:59:59.000Z");
+
+        assertFormat("04/09/2017 00:01:00 pm", "MM/dd/yyyy KK:mm:ss a", "2017-04-09T12:01:00.000Z");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/test/std/datetime/millitime/DateFormatCompilerTest.java:192]: 00 pm looks invalid to me, can only be 12pm or 12am

File: core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampFormatCompilerTest.java [hunk 2]
```diff
@@ -184,54 +219,54 @@ public void testFormatHour23OneDigit() throws Exception {
...
+        assertFormat("am, 11", "a, h", "2017-03-31T11:59:59.999Z");
 
-        assertFormat("3", "h", "2017-03-31T14:00:00.000Z");
-        assertFormat("1", "h", "2017-03-31T12:00:00.000Z");
-        assertFormat("4", "h", "2017-03-31T03:00:00.000Z");
-        assertFormat("12", "h", "2017-03-31T11:59:59.999Z");
+        assertFormat("2", "h", "2017-03-31T14:00:00.000Z");
+        assertFormat("12", "h", "2017-03-31T12:00:00.000Z");
+        assertFormat("3", "h", "2017-03-31T03:00:00.000Z");
+        assertFormat("11", "h", "2017-03-31T11:59:59.999Z");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampFormatCompilerTest.java:269]: Would be good to see how `00:00:00.000Z` is converted to am/pm

File: core/src/test/java/io/questdb/test/std/datetime/millitime/DateFormatCompilerTest.java [hunk 3]
```diff
@@ -155,6 +184,21 @@ public void testFormatEra() throws Exception {
         assertFormat("BC", "G", "-1024-04-09T00:00:00.000Z");
     }
 
+    @Test
+    public void testFormatFirstHourIn12HourClock() throws Exception {
+        assertFormat("04/09/2017 00:01:00 am", "MM/dd/yyyy KK:mm:ss a", "2017-04-09T00:01:00.000Z");
+        assertFormat("04/09/2017 00:59:59 am", "MM/dd/yyyy KK:mm:ss a", "2017-04-09T00:59:59.000Z");
```
Comment (ideoma) [inline core/src/test/java/io/questdb/test/std/datetime/millitime/DateFormatCompilerTest.java:190]: 00 am looks invalid to me

Comment (jerrinot) [reply core/src/test/java/io/questdb/test/std/datetime/millitime/DateFormatCompilerTest.java:190]: @ideoma: thanks for reviewing it! 

The pattern in this test is `KK:mm:ss a`
`KK` stands for `Hour in am/pm (0-11)`.
`a` stands for `am/pm`
=> It is correct, even uncommon. 

Normally the 12-hour clock uses the 1-12 convention. So that would change the placeholders from `KK:mm:ss a` to `hh:mm:ss a`. I can add this test too. wdyt?

File: core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampFormatCompilerTest.java (hunk 2 above)
Comment (jerrinot) [reply core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampFormatCompilerTest.java:278]: @ideoma done

**Review by ideoma — APPROVED** [review]
