### PR TITLE
fix(sql): fix handling of keyed string aggregation of first(), first_not_null(), last(), last_not_null() functions

### LINKED ISSUE #4067: last and last_not_null misbehaving for string types
### Describe the bug

Two different users have reported problems with last and last_not_null when the type is a String. It works as expected apparently for double, but it seems for String every column other than the timestamp is ignored for aggregation purposes.

### To reproduce

```
create table test (ts timestamp, device symbol, valueStr String, valueDb Double) timestamp(ts) partition by day;
insert into test (ts, device, valueStr, valueDb) VALUES 
('2023-12-18T18:00:00', 'A', 'hot', 150),
('2023-12-18T18:00:00', 'B', 'cold', 3);

select * from test;
```

We have two rows, each with a different device, as in:

image

Now if we do implicit aggregation or explicit sample by, you can see the string column is ignoring the `device` column

```
select ts, device, last(valueStr), last(valueDb), last_not_null(valueStr), last_not_null(valueDb) from test;
```
image

```
select ts, device, last(valueStr), last(valueDb), last_not_null(valueStr), last_not_null(valueDb) from test sample by 1h;
```

image

### Expected Behavior

It should properly find the last value within the aggregation scope

### Environment

```markdown
- **QuestDB version**: 7.3.5 / 7.3.8 (from main)
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #4067

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 51 / 53 (96.23%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java|31|33|93.94%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastNotNullStrGroupByFunction.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastStrGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstNotNullStrGroupByFunction.java|6|6|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java [hunk 1]
```diff
@@ -32,33 +32,70 @@
...
 
     public FirstStrGroupByFunction(@NotNull Function arg) {
         this.arg = arg;
     }
 
     @Override
     public void clear() {
-        sink.clear();
+        // Free extra sinks.
+        if (sinks.size() > LIST_CLEAR_THRESHOLD) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java:58]: nit: I think this would be slightly better

```Java
        for (int i = LIST_CLEAR_THRESHOLD, n = sinks.size(); i < n; i++) {
            sinks.getAndSetQuick(i, null).close();
        }
        sinks.setPos(LIST_CLEAR_THRESHOLD);
```

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java [hunk 2]
```diff
@@ -100,12 +140,18 @@ public boolean isScalar() {
     @Override
     public void pushValueTypes(ArrayColumnTypes columnTypes) {
         this.valueIndex = columnTypes.getColumnCount();
-        columnTypes.add(ColumnType.BOOLEAN);
+        columnTypes.add(ColumnType.INT); // sink index
+        columnTypes.add(ColumnType.BOOLEAN); // null flag
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java:144]: nit: a bit of overhead to store not null flag if we only compute first record. I would understand the need in first not null but here it looks redundant, simply storing null `DirectCharSink` would be good enough.

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java [hunk 3]
```diff
@@ -100,12 +140,18 @@ public boolean isScalar() {
...
     }
 
     @Override
     public void setNull(MapValue mapValue) {
-        mapValue.putBool(valueIndex, false);
-        sink.clear();
+        mapValue.putBool(valueIndex + 1, true);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java:149]: Could you explain what does this do? I couldn't hit this with the tests from `FirstAndLastStrGroupByFunctionFactoryTest`

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java [hunk 4]
```diff
@@ -32,33 +32,70 @@
...
+        }
+
+        if (str != null) {
             sink.put(str);
+            mapValue.putBool(valueIndex + 1, false);
         } else {
-            mapValue.putBool(this.valueIndex, false);
+            mapValue.putBool(valueIndex + 1, true);
         }
+        mapValue.putInt(valueIndex, sinkIndex++);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java:98]: nit: could be:
```
mapValue.putInt(valueIndex, str == null ? -sinkIndex : sinkIndex);
sinkIndex++
```

**Review by ideoma — COMMENTED** [review]
Will `SAMPLE BY` have the same problem? Could you add tests for SAMPLE BY and SAMPLE BY with FILL please?

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java (hunk 1 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java:58]: applied in latest commit

**Comment by bziobrowski** [comment]
> Will SAMPLE BY have the same problem? Could you add tests for SAMPLE BY and SAMPLE BY with FILL please?

FirstAndLastStrGroupByFunctionFactoryTest already tests  sample by .  In latest commit I added fill(prev) .

File: core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java (hunk 3 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java:149]: It gets hit in latest commit, once I added fill(prev) to sample by tests.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 53 / 53 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastNotNullStrGroupByFunction.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastStrGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java|33|33|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstNotNullStrGroupByFunction.java|6|6|100.00%|

**Review by ideoma — APPROVED** [review]
