### PR TITLE
fix(core): improve native memory management of factories, cursors and caches

### LINKED ISSUE #2405: QDB crashes when self-joining multiple times
### Describe the bug

I am currently self.joining the same table withe ach other multiple times as described as follows. On occasion, this seemingly simple query will yield an exit 137 in my docker container. Is there any way I can quickly provide a dump of the database contents for easy reproducability?

### To reproduce

```
  create table weather_data_historical (
      sensor_time timestamp not null,
      sensor_day symbol,
      min_temperature_out float,
      max_temperature_out float,
      avg_temperature_out float,
      snow_height float,
      rain_acc_24h float,
      max_wind_gust_speed float
  )
  TIMESTAMP(sensor_time)

    select sensor_day, 
    warmest_day, first(cast(warmest_day_year as int)) as warmest_day_year,
    coldest_day, first(cast(coldest_day_year as int)) as coldest_day_year,
    warmest_night, first(cast(warmest_night_year as int)) as warmest_night_year,
    coldest_night, first(cast(coldest_night_year as int)) as coldest_night_year,
    max_snow_height, first(cast(max_snow_height_year as int)) as max_snow_height_year,
    max_wind_gust_overall, first(cast(max_wind_gust_year as int)) as max_wind_gust_year,
    first(avg_temperature) as avg_temperature
    from
    (
        select a1.sensor_day, 
        warmest_day, to_str(a2.sensor_time, 'yyyy') as warmest_day_year, 
        coldest_day, to_str(a3.sensor_time, 'yyyy') as coldest_day_year,
        warmest_night, to_str(a4.sensor_time, 'yyyy') as warmest_night_year,
        coldest_night, to_str(a5.sensor_time, 'yyyy') as coldest_night_year,
        max_snow_height, to_str(a6.sensor_time, 'yyyy') as max_snow_height_year,
        max_wind_gust_overall, to_str(a7.sensor_time, 'yyyy') as max_wind_gust_year,
        avg_temperature
        from
        (
            select sensor_day, 
            max(max_temperature_out) as warmest_day, min(max_temperature_out) as coldest_day, 
            max(min_temperature_out) as warmest_night, min(min_temperature_out) as coldest_night, 
            max(rain_acc_24h) as max_rain, max(snow_height) as max_snow_height, 
            max(max_wind_gust_speed) as max_wind_gust_overall, 
            avg(avg_temperature_out) as avg_temperature
            from weather_data_historical 
             where sensor_day ~ '08-07'
            group by sensor_day
        ) a1
        left join weather_data_historical a2 on (a1.sensor_day = a2.sensor_day and warmest_day = a2.max_temperature_out)
        left join weather_data_historical a3 on (a1.sensor_day = a3.sensor_day and coldest_day = a3.max_temperature_out)
        left join weather_data_historical a4 on (a1.sensor_day = a4.sensor_day and warmest_night = a4.min_temperature_out)
        left join weather_data_historical a5 on (a1.sensor_day = a5.sensor_day and coldest_night = a5.min_temperature_out)
        left join weather_data_historical a6 on (a1.sensor_day = a6.sensor_day and max_snow_height = a6.snow_height and a6.snow_height > 0)
        left join weather_data_historical a7 on (a1.sensor_day = a7.sensor_day and max_wind_gust_overall = a7.max_wind_gust_speed)
    )
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.5 Docker
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
This PR reduces factory and cursor memory usage by : 
- moving allocations from factory to cursor 
- releasing native memory on cursor.close()
- re-allocating memory on getCursor()

With this setup it should be possible to cache hundreds of statements without wasting memory on unused buffers, maps, etc.  

Fixes #2405

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `build`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ac12f3785b2833681677b60601ab68761a60e60
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 344 / 348 (98.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|7|57.14%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|36|36|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectCastRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptCastRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LongChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|41|41|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|10|10|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java [hunk 1]
```diff
@@ -109,7 +108,8 @@ public boolean supportsUpdateRowId(CharSequence tableName) {
     }
 
     private void buildMapOfSlaveRecords(RecordCursor slaveCursor, SqlExecutionCircuitBreaker circuitBreaker) {
-        HashOuterJoinRecordCursorFactory.buildMap(slaveCursor, slaveCursor.getRecord(), joinKeyMap, slaveKeySink, slaveChain, circuitBreaker);
+        cursor.joinKeyMap.inflate();
+        HashOuterJoinRecordCursorFactory.buildMap(slaveCursor, slaveCursor.getRecord(), cursor.joinKeyMap, slaveKeySink, slaveChain, circuitBreaker);
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java:112]: If exception is thrown here cursor.joinKeyMap will not be closed because `HashJoinRecordCursor.of` method not yet called.

File: core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java [hunk 2]
```diff
@@ -109,7 +108,8 @@ public boolean supportsUpdateRowId(CharSequence tableName) {
     }
 
     private void buildMapOfSlaveRecords(RecordCursor slaveCursor, SqlExecutionCircuitBreaker circuitBreaker) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java:110]: It will be cleaner to move thid method inside the cursor, same as you did in `HashJoinLightRecordCursorFactory`

File: core/src/main/java/io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java [hunk 3]
```diff
@@ -187,13 +156,51 @@ public boolean hasNext() {
...
-        void of(RecordCursor masterCursor, RecordCursor slaveCursor) {
-            this.masterCursor = masterCursor;
-            this.slaveCursor = slaveCursor;
-            this.masterRecord = masterCursor.getRecord();
-            this.slaveRecord = slaveCursor.getRecordB();
-            record.of(masterRecord, slaveRecord);
-            slaveChainCursor = null;
+        void of(RecordCursor masterCursor, RecordCursor slaveCursor, SqlExecutionCircuitBreaker circuitBreaker) {
+            try {
+                this.isOpen = true;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java:161]: First time when you create Factory and then Cursor, maps are already inflated and `isOpen` is already true here. It's better to not re-inflate when `isOpen == true` here and all other similar places.

File: core/src/main/java/io/questdb/cairo/map/CompactMap.java [hunk 4]
```diff
@@ -193,6 +194,11 @@ public MapRecord getRecord() {
         return record;
     }
 
+    @Override
+    public void inflate() {
```
[the remark this answers is not in the document]
Comment (ideoma) [reply core/src/main/java/io/questdb/cairo/map/CompactMap.java:198]: After reading the usage of `inflate()` I think the better name will be `realloc()`

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByAllRecordCursor.java [hunk 5]
```diff
@@ -24,6 +24,7 @@
 
 package io.questdb.griffin.engine.table;
 
+import io.questdb.cairo.Inflatable;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByAllRecordCursor.java:27]: minor: redundant import

File: core/src/main/java/io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java [hunk 6]
```diff
@@ -36,6 +36,7 @@ abstract class AbstractDescendingRecordListCursor extends AbstractDataFrameRecor
 
     protected final DirectLongList rows;
     private long index;
+    protected boolean isOpen;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java:39]: I'd make it private with read-only get access.
`close()` on this class should set it to false. At the moment it's not obvious what can change `isOpen` and in what order

File: core/src/main/java/io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java [hunk 7]
```diff
@@ -53,17 +53,22 @@ public LatestByAllFilteredRecordCursor(
...
+            filter.close();
+            map.close();
+            super.close();
+        }
     }
 
     @Override
     protected void buildTreeMap(SqlExecutionContext executionContext) throws SqlException {
-        map.clear();
+        map.inflate();
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java:71]: Here as well, please do not inflate something which was just created in the constructor

**Review by ideoma — COMMENTED** [review]
Looks good but some minor inefficiencies like double re-allocation on first run would be better to get fixed.
Also you may want to make Order By factories resource free.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 344 / 348 (98.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|7|57.14%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|36|36|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectCastRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptCastRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LongChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|41|41|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|10|10|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java (hunk 3 above)
Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java:161]: I'll make the change but keep in mind that before memory is used it remains virtual, with no physical memory backing it up and as such reallocating to the same size should be a no-op.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 390 / 400 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|7|57.14%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|37|37|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LongChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|42|42|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|11|11|100.00%|

**Comment by bziobrowski** [comment]
I didn't manage to finish changing order by and other factories . I'll do it when I'm back .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 390 / 400 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|7|57.14%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|37|37|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LongChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|42|42|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 390 / 400 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|7|57.14%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|37|37|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LongChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|42|42|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|11|11|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java (hunk 6 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java:39]: Should be private

File: core/src/main/java/io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java [hunk 8]
```diff
@@ -71,6 +73,17 @@ void of(DataFrameCursor dataFrameCursor, SqlExecutionContext executionContext) t
         this.recordB.of(dataFrameCursor.getTableReader());
         rows.clear();
         buildTreeMap(executionContext);
+        this.isOpen = true;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java:76]: `LatestByValuesFilteredRecordCursor` and `LatestByValuesRecordCursor` do not use reallocation parttern

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 390 / 400 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|7|57.14%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|24|27|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|37|37|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptCastRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LongChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|42|42|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|11|11|100.00%|

**Review by ideoma — APPROVED** [review]
