### PR TITLE
fix(o3): file remove fix, also fixed regression of maxTimestamp

### LINKED ISSUE #937: On repeated O3 ingest might reset table's maxTimestamp in the wrong direction
I can be reproduced by repeatedly ingesting dataset, which moves in opposite direction to regular timeline

### PR DESCRIPTION
**Pull request by bluestreak01**
Fixed #937

### CODE REVIEW

**Review by ideoma — APPROVED** [review]

File: core/src/main/java/io/questdb/cairo/TxnScoreboard.java [hunk 1]
```diff
@@ -89,8 +89,8 @@ public long getMin() {
         return getMin(mem);
     }
 
-    public boolean isTxnUnused(long nameTxn, long readerTxn) {
-        return isTxnUnused(nameTxn, readerTxn, mem);
+    public boolean isTxnUnused(long nameTxn) {
```
Comment (ideoma) [inline core/src/main/java/io/questdb/cairo/TxnScoreboard.java:92]: Perhaps rename to isTxnAvailable too

Comment (bluestreak01) [reply core/src/main/java/io/questdb/cairo/TxnScoreboard.java:92]: 👍
