### PR TITLE
fix(sql): fix case insensivity for ILIKE

### LINKED ISSUE #2585: ILIKE SQL operator is not case-insensitive
### Describe the bug

In [Postgres](https://www.postgresql.org/docs/current/functions-matching.html), ILIKE can be used instead of LIKE to make the match case-insensitive according to the active locale. Yet, our implementation uses the same code for both LIKE and ILIKE (see `LikeStrFunctionFactory` and `ILikeStrFunctionFactory` classes). We should fix it.

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.5.3
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ln11211**
Fixes #2585

Added code for AbstractILikeStrFunctionFactory.java and support for ILIKE sql functionality

### CODE REVIEW

**Comment by Ln11211** [comment]
hey @puzpuzpuz, thanks for the oracle link - it's been a nice resource, I just have one more doubt :) . We will require a `AbstractILikeStrFunctionFactory` class for ILIKE functionality and the `ILikeStrFunctionFactory` class is extending the `AbstractLikeStrFunctionFactory` coz it is missing it's own version, that is why we get the same output for both the types right? SO I went ahead and made a `AbstractILikeStrFunctionFactory` class for it and then added the `Pattern.CASE_INSENSITIVE` fields.


I hope this fixes the issue but do let me know about it, I totally loved reading the documentation( obviously you provided them :) thanks!! ) to implement this.

**Comment by Ln11211** [comment]
BTW @puzpuzpuz , I have raised a PR first and I am worried if this will be marked as spam coz I was not assigned this issue but I went ahead with it because it was interesting. Though the other person commented faster than me, I commented just a minute after them so I hope this won't be marked as spam ✌️..

**Comment by Ln11211** [comment]
recheck

**Comment by Ln11211** [comment]
Also the `DOTALL` flag is already present so I added the `OR |` operator to compound two flags but the ideal practice is to use a embedded flag expression, so I was thinking if using the flag expression( in this case `(?si)` would be better, but will it confuse other people?

**Comment by Ln11211** [comment]
Added Test cases for ilike operator and it's working.

### Successful test using `ilike` in sql query for a case insensitive query
image


### Failed test using `like` in sql query for the same query
image

**Comment by Ln11211** [comment]
However one last test - **testNonConstantExpression** is failing..

image

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+import io.questdb.std.Chars;
+import io.questdb.std.IntList;
+import io.questdb.std.Misc;
+import io.questdb.std.ObjList;
+import io.questdb.std.str.StringSink;
+
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public abstract class AbstractILikeStrFunctionFactory implements FunctionFactory {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java:48]: A single flag doesn't require a duplicate abstract class. Better to introduce an abstract method in the original `AbstractLikeStrFunctionFactory` class and have both of its child classes implement it.

Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java:48]: OK,I'll do that

**Comment by Ln11211** [comment]
Hey, I made one method abstract ([here](https://github.com/Ln11211/questdb/blob/610034b239e49b1882c37665ad71936c7c76e8ec/core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java#L74)) and I couldn't make the other method abstract as it was in a non abstract class([here](https://github.com/Ln11211/questdb/blob/610034b239e49b1882c37665ad71936c7c76e8ec/core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java#L128)) (I tried  doing it and I messed up the implementation) so for the second method, I just implemented the flag specially in the `ILikeStrFunctionFactory.java`([check here](https://github.com/Ln11211/questdb/blob/610034b239e49b1882c37665ad71936c7c76e8ec/core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java#L96)) ..

**In simple words-**
It's not the perfect implementation but it works (It swims like a duck, it quacks like a duck so it must be a ...) :)

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java (hunk 1 above)
Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java]: > However one last test - **testNonConstantExpression** is failing..
> 
> image

This one still fails, how do we fix this?

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java [hunk 2]
```diff
@@ -24,7 +24,98 @@
...
+import io.questdb.griffin.engine.functions.UnaryFunction;
+import io.questdb.griffin.engine.functions.bind.IndexedParameterLinkFunction;
+import io.questdb.griffin.engine.functions.constants.BooleanConstant;
+import io.questdb.std.IntList;
+import io.questdb.std.ObjList;
+
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
 public class ILikeStrFunctionFactory extends AbstractLikeStrFunctionFactory {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: There is still a lot of unnecessary code duplication. Please introduce
```
protected abstract boolean isCaseInsensitive();
```
and use this method in the `AbstractLikeStrFunctionFactory`.

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java (hunk 1 above)
Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractILikeStrFunctionFactory.java]: ok

File: core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java (hunk 2 above)
Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: alright

Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: > There is still a lot of unnecessary code duplication. Please introduce
> 
> ```
> protected abstract boolean isCaseInsensitive();
> ```
> 
> and use this method in the `AbstractLikeStrFunctionFactory`.

wait, should this abstract method be declared in `ILikeStrFunctionFactory` class and used in `AbstractLikeStrFunctionFactory` ? but the former extends the later not the other way, so it won't be possible right?

And why does it have a boolean return type? what exactly does it do?

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: This method should belong to `AbstractLikeStrFunctionFactory` and implemented in the child classes. It basically tells whether the factory (and the functions) perform case-insensitive matching or not. Alternatively, you could add an abstract method that would return flags to be provided to `Pattern#compile()`.

Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: Tried them both, but the problem is with the `init` ([init](https://github.com/Ln11211/questdb/blob/610034b239e49b1882c37665ad71936c7c76e8ec/core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java#L128)) method which is in a static class `BindLikeStrFunction` and since the declaration of the methods is **abstract**, there is a conflict - **cannot reference non static variable in static context**. Since we are using an abstract method definition they can't be static and cannot be referenced in static context (in this case the bitmask for the flags) etc

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: I'll illustrate what I mean a bit later today.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: This patch shows what I mean: https://github.com/puzpuzpuz/questdb/commit/c036393fb9f2a96257705154f407892a4d49945c

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: > Did you test it?

You should try running it. Tests should pass.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: Any option that works for you. You could add my fork as a remote, fetch it and cherrypick the commit; or create a patch from it and apply to your branch; or something else.

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java:43]: Sure, that's your PR. Feel free to do any modifications.

Comment (Ln11211) [reply core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeStrFunctionFactory.java]: All done...

**Review by puzpuzpuz — APPROVED** [review]
Thanks for your contribution!
