### PR TITLE
fix(sql): fix order by removal in nested queries inside set operations

### LINKED ISSUE #2904: UNION ALL doesn't work correctly in combination with LIMIT
### Describe the bug

See the below reproducer.

### To reproduce

```sql
create table x as (
  select x,
         rnd_symbol(4, 10, 10, 0) sym,
         cast(172800000000 as timestamp) ts
  from long_sequence(100)
) timestamp(ts) partition by day;

select *
from (
  (select sym, max(x) from x order by sym limit 0,2)
  union all
  (select sym, max(x) from x order by sym limit 2,4)
);
```

The above select returns the following record set:
```
"sym","max"
"FHUDMNJRJP",97
"KFXSBQIYCH",96
"RCMGUPZLXU",100
"KFXSBQIYCH",96
```

Notice duplicated `KFXSBQIYCH` records. The bug is that this record is returned only by the first sub-query.

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: latest `master`
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2904

PR Fixes bad order by ignore/removal in second and later subqueries of set operations (EXCEPT , UNION, UNION ALL, INTERSECT ).
Also fixes bad column name resolution in explain plan for  DeferredSingleSymbolFilterDataFrame.

### CODE REVIEW

File: core/src/main/java/io/questdb/griffin/SqlOptimiser.java [hunk 1]
```diff
@@ -2924,6 +2919,15 @@ private QueryModel rewriteOrderBy(QueryModel model) throws SqlException {
 
         while (base.getBottomUpColumns().size() > 0 && !base.isNestedModelIsSubQuery()) {
             baseParent = base;
+
+            final QueryModel union = base.getUnionModel();
+            if (union != null) {
+                final QueryModel rewritten = rewriteOrderBy(union);
+                if (rewritten != union) {
```
Comment (bziobrowski) [inline core/src/main/java/io/questdb/griffin/SqlOptimiser.java:2926]: Line 2927, like existing line 3064,  is not covered by tests. 
I couldn't figure out SQL to trigger it but would rather keep it for consistency .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SymbolIndexRowCursorFactory.java|2|2|100.00%|

**Review by puzpuzpuz — APPROVED** [review]
