### PR TITLE
fix(sql): fix order by desc with async filter

### LINKED ISSUE #2435: QuestDB wrongly sorts default timestamp column when using WHERE
### Describe the bug

Hey guys,

I encoutered a very strange problem. I am currently setting up QuestDB for some kind of semi-chat-backend. The reason is that it perfectly fits my use case (99,9% of messages requested will be only 1 or two days old and there are no plans for any investigated searching, updating or similar). So what I have is the following:

A table "chatmessages" with the following auto created columns through ILP (TCP):
useridfor (SYMBOL) | messageid (STRING) | message (STRING) | useridfrom (STRING) | useridto (STRING) | creationtime (DOUBLE) | files (STRING) | timestamp (TIMESTAMP)

I then stress test QuestDB and insert about 20k messages/s until I reach 1million messages in total. All of these messages are the same except of "creationtime" (which is a timestamp I create in some C/C++ code through using time(null)) and except of "timestamp" (because this is auto-generated from QuestDB because I omit the timestamp from ILP packets).

After these 1mio inserts, I add a few messages which are different to the inserted ones before, to check if everything is working as expected. The next step is to get the last X messages for given userid, I use this query for this:

`SELECT * from 'chatmessages' where useridfor='1824a629-803f-ffff-017b-f45e3202115a' AND useridto='1123' ORDER by timestamp DESC`

Now when I ODER BY timestamp and combine it with a WHERE, it gives me this result (which is wrong).

image

However if I do the same query but order by my manually inserted creationtime column, it gives me this (correct) result:

image

If I remove the "WHERE"-Clause from the first query, it also returns the expected result. 

QuestDB-Version: Docker latest (6.5)

Command I used for starting this docker:
`docker run -p 19009:9009 -p 19003:9003 -p 19000:9000 -e QDB_HTTP_QUERY_CACHE_ENABLED=false -e QDB_CAIRO_COMMIT_LAG=1000 -e QDB_CAIRO_MAX_UNCOMMITTED_ROWS=8192 -e QDB_CAIRO_DEFAULT_SYMBOL_CAPACITY=524288 -e QDB_CAIRO_INDEX_VALUE_BLOCK_SIZE=16384 --rm --net app-network --name questdb_communication -d questdb/questdb`

The queries are done through web-interface (UI) and using REST-API, both give the same result. 

What especially strikes my mind is the fact, that the timestamp values are correct, but they are still filtered incorrecty....

### To reproduce

1. Start latest Docker Questdb with given config
2. Send X messages to QuestDB (make sure you reach about 20k/s)
3. Insert a few "custom" values
4. Query
5. See the wrong results

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: Latest Docker 6.5
- **OS**: Windows 10
- **Browser**: Firefox (and C/C++ REST API for Query)
```

### Additional context

_No response_

Edit:
This query also yields the right results:
`SELECT * from 'chatmessages' where useridfor='1824a629-803f-ffff-017b-f45e3202115a' AND useridto='1123' ORDER by cast(timestamp AS TIMESTAMP) DESC`

Edit2:
Version 6.3.1 works as expected, there I did not see the described behaviour.

Edit3:
I just retested with 6.3.1, it also does not work always. Sometimes it works, sometimes not...

### LINKED ISSUE #2447: Query with systimestamp() filter  returns incorrect results
### Describe the bug

Query with "sensor_time <= systimestamp()" on designated timestamp doesn't include latest results . 

### To reproduce
```sql
create table weather_data 
(
  sensor_time timestamp,
  temperature_out double, 
  humidity_out double,
  pressure_sea double
) timestamp (sensor_time) partition by year;


insert into weather_data 
select  dateadd( 's' , cast(x-10000000 as int),  systimestamp() ), rnd_double(), rnd_double(), rnd_double()
from long_sequence(10000000);

select min(sensor_time), max(sensor_time) from weather_data ; 
2022-04-28T13:37:44.038657Z 2022-08-22T07:24:23.875931Z

selecT sensor_time 
from weather_data 
order by sensor_time desc 
limit 2; 

2022-08-22T07:24:23.875931Z 
2022-08-22T07:24:22.875931Z

selecT sensor_time, temperature_out, humidity_out, pressure_sea
from weather_data 
where sensor_time <= systimestamp() 
order by sensor_time  desc 
limit 100; 

2022-05-06T20:02:28.123099Z 0.0804346991144 0.00393228002016 0.180614050154
2022-05-06T20:02:27.123099Z 0.547236537507 0.30394162489 0.946387106737
```

### Expected Behavior

Query above should return records with 2022-08-22 timestamp first . 

### Environment

```markdown
- **QuestDB version**: 6.5.1-SNAPSHOT
- **OS**: Windows
- **Browser**: Chrome
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes order by desc clause getting ignored when async filter is used .

Order by ts asc and no clause worked fine because : 
- if order was missing then limit got pushed down and reached async factory, otherwise
- limit didn't reach it but order by advice was recognised and async filter assumed this order by default . 

Fixes #2447 
Fixes #2435

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/DataFrameRecordCursorFactory.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursorFactory.java [hunk 1]
```diff
@@ -92,7 +91,7 @@ public boolean followedOrderByAdvice() {
     public PageFrameCursor getPageFrameCursor(SqlExecutionContext executionContext, int order) throws SqlException {
         DataFrameCursor dataFrameCursor = dataFrameCursorFactory.getCursor(executionContext, order);
         if (framingSupported) {
-            if (order == ORDER_ASC || order == ORDER_ANY) {
+            if (order == ORDER_ASC || (order == ORDER_ANY && dataFrameCursorFactory.getOrder() != ORDER_DESC)) {
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursorFactory.java:94]: I'd better keep this method as is and apply the fix to `AsyncFilteredRecordCursorFactory/AsyncJitFilteredRecordCursorFactory#getCursor()`. It should consider `base.hasDescendingOrder()` and also split the direction record traversal (ORDER BY) and limit accumulation (LIMIT). Currently they're mixed which leads to bugs and confusion.

Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursorFactory.java]: Fixed.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 14 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/DataFrameCursorFactory.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|5|5|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java [hunk 2]
```diff
@@ -98,24 +98,25 @@ public boolean followedLimitAdvice() {
...
+                order = baseOrder;
             } else {
-                order = ORDER_DESC;
+                order = reverse(baseOrder);
                 rowsRemaining = -rowsRemaining;
             }
         } else {
             rowsRemaining = Long.MAX_VALUE;
-            order = ORDER_ANY;
+            order = baseOrder;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java:116]: It used to be ANY when no limit specified, now it's ASC.
Why ANY is incorrect?

Comment (bziobrowski) [reply core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java:116]: Passing ANY to data frame factory 'below' made it ASC and caused the issue . 
It's either ASC or DESC now, and former should cover 'previous' ANY .   
I'm not a fan of deciding directions at this stage really.

File: core/src/test/java/io/questdb/griffin/OrderByWithAsyncFilterTest.java [hunk 3]
```diff
@@ -0,0 +1,260 @@
...
+ *
+ ******************************************************************************/
+
+package io.questdb.griffin;
+
+import org.junit.Before;
+import org.junit.BeforeClass;
+import org.junit.Test;
+
+public class OrderByWithAsyncFilterTest extends AbstractGriffinTest {
```
Comment (puzpuzpuz) [inline core/src/test/java/io/questdb/griffin/OrderByWithAsyncFilterTest.java:31]: nit: would be nice to add some tests with ORDER BY, but without LIMIT for the sake of completeness.

**Review by puzpuzpuz — APPROVED** [review]
LGTM. Left a few minor comments.

A note for future improvements: would be nice to get rid of `LimitRecordCursorFactory` wrappers for both async factories; the used set of factories should be the same regardless of the presence of ORDER BY.

File: core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java [hunk 4]
```diff
@@ -122,6 +119,14 @@ public static void setUpStatic() {
         AbstractGriffinTest.setUpStatic();
     }
 
+    @Before
+    public void setUp() {
```
[the remark this answers is not in the document]
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java:123]: Even though they're set once in setUpStatic they get reverted back to defaults in tearDown() so this method is needed, otherwise running single or several methods test   yields different result to running whole test class.

File: core/src/test/java/io/questdb/griffin/OrderByWithAsyncFilterTest.java [hunk 5]
```diff
@@ -0,0 +1,260 @@
...
+        pageFrameMaxRows = PAGE_FRAME_MAX_ROWS;
+        // We intentionally use small values for shard count and reduce
+        // queue capacity to exhibit various edge cases.
+        pageFrameReduceShardCount = 2;
+        pageFrameReduceQueueCapacity = PAGE_FRAME_COUNT;
+
+        AbstractGriffinTest.setUpStatic();
+    }
+
+    //tearDown() overrides settings set in setUpStatic()
```
[the remark this answers is not in the document]
Comment (bziobrowski) [reply core/src/test/java/io/questdb/griffin/OrderByWithAsyncFilterTest.java:52]: Comment in the line above explains it .

File: core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java:123]: I was under an impression that we only read them once, but indeed some of the classes like `DataFrameRecordCursorFactory` read them when being constructed. Thanks for the clarification.

**Review by puzpuzpuz — APPROVED** [review]
Thanks for going the extra mile with the test improvements!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 14 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/DataFrameCursorFactory.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|5|5|100.00%|
