### PR TITLE
fix(bitmapindex): check value block offset for sparse keys

### LINKED ISSUE #1763: SIGSEV in find_latest_for_key()
### Describe the bug

Occasionally, questdb crashes with a SIGSEV, but what causes it is still unclear. The corresponding error log is attached, which includes details of the environment quest was running in.

table schema:
```
height - long
hash - string
timestamp - timestamp
pa - symbol
ta - string
oa - string
oamt - long
ra - string
ramt - long
exc - string
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 6.1.3
- **OS**: Ubuntu 20.04
- **Browser**: Not Applicable
```

### Additional context
Quest log (11/01/2022): [questdb-debug-info-error_private.log](https://github.com/questdb/questdb/files/7843090/questdb-debug-info-error_private.log)

Error log (11/01/2022): [hs_err_pid31077_private.log](https://github.com/questdb/questdb/files/7843089/hs_err_pid31077_private.log)

Error log: [hs_err_pid1059.log](https://github.com/questdb/questdb/files/7822432/hs_err_pid1059.log)

### PR DESCRIPTION
**Pull request by eugenels**
Fixes #1763

It is possible that the first value block for a "sparse" key was added after the valueMem memory mapping was created.

This PR adds a check for the block's memory offset validity before processing it.

### CODE REVIEW

File: core/src/test/java/io/questdb/cairo/BitmapIndexTest.java [hunk 1]
```diff
@@ -660,6 +660,82 @@ public void testCppLatestByIndexReaderIndexedWithTruncate() throws Exception {
...
+        try (BitmapIndexWriter writer = new BitmapIndexWriter(configuration, path, "x")) {
+            for (int i = 0; i < keyCount; i++) {
+                // add even keys
+                if(i % 2 == 0) {
+                    writer.add(i, i);
+                }
+            }
+        }
+
+        DirectLongList rows = new DirectLongList(keyCount, MemoryTag.NATIVE_LONG_LIST);
```
Comment (bluestreak01) [inline core/src/test/java/io/questdb/cairo/BitmapIndexTest.java:679]: this and the reader should be closed in try() ... finally block to avoid leakage on test failure

File: core/src/main/c/share/bitmap_index_utils.cpp [hunk 2]
```diff
@@ -53,6 +53,11 @@ int64_t find_latest_for_key(int64_t k,
         bool is_offset_in_mapped_area = tail.offset() + tail.memory_size() <= value_memory_size;
         bool is_inconsistent = !key.is_block_consistent || !is_offset_in_mapped_area;
         if (is_inconsistent) {
+            // first value block can be outside of file mapping as well
+            bool inside_mapped_area = inconsistent_tail.offset() + inconsistent_tail.memory_size() <= value_memory_size;
```
Comment (bluestreak01) [inline core/src/main/c/share/bitmap_index_utils.cpp:57]: does this affect Java version of index reader as well ?

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

File: core/src/main/c/share/bitmap_index_utils.cpp (hunk 2 above)
Comment (eugenels) [reply core/src/main/c/share/bitmap_index_utils.cpp:57]: no, java is able to extend and remap memory.
this is c++ implementation specific problem

File: core/src/test/java/io/questdb/cairo/BitmapIndexTest.java (hunk 1 above)
Comment (eugenels) [reply core/src/test/java/io/questdb/cairo/BitmapIndexTest.java]: fixed

**Review by bluestreak01 — APPROVED** [review]
