### PR TITLE
fix(http): unhandled NullPointerException on SQL query error

### LINKED ISSUE #5545: Exception with critical error on query with LAG function
### To reproduce

```
2025-04-02T16:04:41.306111Z C i.q.c.h.p.JsonQueryProcessorState [833223819793] internal error [ex=
java.lang.NullPointerException: Cannot invoke "io.questdb.cairo.sql.RecordCursor.hasNext()" because "this.base" is null
	at io.questdb.griffin.engine.QueryProgress$RegisteredRecordCursor.hasNext(QueryProgress.java:421)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.setupFirstRecord(JsonQueryProcessorState.java:917)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.onSetupFirstRecord(JsonQueryProcessorState.java:867)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.resume(JsonQueryProcessorState.java:1055)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.doResumeSend(JsonQueryProcessor.java:381)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect0(JsonQueryProcessor.java:695)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:669)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeNewSelect(JsonQueryProcessor.java:647)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:551)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:224)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:296)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:991)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:307)
	at io.questdb.cutlass.http.HttpServer.handleClientOperation(HttpServer.java:345)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:129)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:216)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:133)
	at io.questdb.mp.Worker.run(Worker.java:152)
, q=`SELECT
    timestamp,
    price,
    lag('timestamp') OVER (
        ORDER BY timestamp
    ) AS previous_price
FROM trades limit 10`]
```

### QuestDB version:

8.2.3

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #5545

### CODE REVIEW

File: core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java [hunk 1]
```diff
@@ -567,6 +533,40 @@ private void compileAndExecuteQuery(
...
+        LOG.debug().$("resume [fd=").$(context.getFd()).I$();
+
+        final HttpChunkedResponse response = context.getChunkedResponse();
+        while (true) {
+            try {
+                state.resume(response);
+                break;
+            } catch (SqlException | ImplicitCastException e) {
+                sqlError(context.getChunkedResponse(), state, e, configuration.getKeepAliveHeader());
+                break;
```
Comment (puzpuzpuz) [inline core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java:549]: The actual fix is here. The old code kept looping after a `SqlException`/`ImplicitCastException` which led to NPE.

Other non-test changes in this PR are due to auto-reformatting.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 104 / 106 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/LagDoubleFunctionFactory.java|60|62|96.77%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/AbstractWindowFunctionFactory.java|22|22|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 22 / 22 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|22|22|100.00%|

File: core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java (hunk 1 above)
Comment (ideoma) [reply core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java:549]: Should `state.clearFactory()` be called here? 

It's not closed in `testQueryImplicitCastExceptionInWindowFunctionFirstRecord`

image

Comment (puzpuzpuz) [reply core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java:553]: I tried to keep the same flow as what we had before #5445. This means that the factory is returned back to the query cache. But I agree that in case of a SQL or cast exception this is probably silly.

Marked the query as non-cacheable, so that it gets closed instead of returned back to the cache in e614e1f84e1c6fb97c755481c4ec2ca23817ba36

Also, I've spotted that we cache EXPLAIN queries which seems wrong. Fixed that in the same commit.

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|25|25|100.00%|

File: core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java [hunk 2]
```diff
@@ -6139,6 +6139,40 @@ public void testQueryEventuallySucceedsOnDataUnavailableEventTriggeredImmediatel
...
+                                "INSERT INTO trades VALUES ('ETH-USD', 'sell', 2615.54, 0.00044, '2022-03-08T18:03:57.609765Z');",
+                                executionContext
+                        );
+
+                        testHttpClient.assertGet(
+                                "{\"query\":\"SELECT timestamp, price, lag('timestamp') OVER (ORDER BY timestamp) AS previous_price FROM trades LIMIT 10;\",\"error\":\"inconvertible value: `timestamp` [STRING -> DOUBLE]\",\"position\":0}",
+                                "SELECT timestamp, price, lag('timestamp') OVER (ORDER BY timestamp) AS previous_price FROM trades LIMIT 10;"
+                        );
+
+                        // verify that HTTP server is healthy
```
Comment (ideoma) [inline core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java:6167]: Can you change the test so that the same HTTP connection is reused after the failure?

I see now HTTP connection is disconnected, and the following query comes through a different connection:

```
2025-04-04T09:32:01.734872Z I IODispatcher connected [ip=127.0.0.1, fd=184683593773]
2025-04-04T09:32:01.754002Z I i.q.g.e.QueryProgress exe [id=2, sql=`SELECT timestamp, price, lag('timestamp') OVER (ORDER BY timestamp) AS previous_price FROM trades LIMIT 10;`, principal=admin, cache=false, jit=false]
2025-04-04T09:32:01.756154Z E i.q.g.e.QueryProgress err [id=2, sql=`SELECT timestamp, price, lag('timestamp') OVER (ORDER BY timestamp) AS previous_price FROM trades LIMIT 10;`, principal=admin, cache=false, jit=true, time=2150458, msg=inconvertible value: `timestamp` [STRING -> DOUBLE], errno=0, pos=0]
2025-04-04T09:32:01.757014Z I IODispatcher disconnected [ip=127.0.0.1, fd=184683593773, src=queue]
2025-04-04T09:32:01.757260Z I IODispatcher connected [ip=127.0.0.1, fd=184683593792]
2025-04-04T09:32:01.758604Z I i.q.g.e.QueryProgress exe [id=3, sql=`SELECT count() FROM trades;`, principal=admin, cache=false, jit=false]
2025-04-04T09:32:01.758814Z I i.q.g.e.QueryProgress fin [id=3, sql=`SELECT count() FROM trades;`, principal=admin, cache=false, jit=true, time=208292]
2025-04-04T09:32:01.758852Z I i.q.c.h.p.JsonQueryProcessorState [184683593792] timings [compiler: 1165167, count: 0, execute: 1506209, q=`SELECT count() FROM trades;`]
```

Comment (puzpuzpuz) [reply core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java]: Done in 668d788093b32ccbeb2b9bc92b6326a189fa8ba4

**Review by ideoma — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|25|25|100.00%|
