### PR TITLE
fix(sql): fix assertion for static symbol table

### LINKED ISSUE #1704: Throws an error if my query returns 0 rows when using SAMPLE BY
### Describe the bug

QuestDB throws an error if my query returns 0 rows when using SAMPLE BY. It works fine and responds 0 row found without SAMPLE BY.

My query (I run it on QuestDB web console directly)
```sql
SELECT ts, pair, side, round(nsum(size)) as size
FROM liquidations
WHERE pair = 'ETC-USDT-PERP' and side = 'sell' and size > 500
SAMPLE BY 1m
ALIGN TO CALENDAR WITH OFFSET '00:00'
ORDER BY ts ASC
;
```

Working code:
```sql
SELECT ts, pair, side, round(nsum(size)) as size
FROM liquidations
WHERE pair = 'ETC-USDT-PERP' and side = 'sell' and size > 500
ORDER BY ts ASC
;
```
returns 0 rows without an error.

### To reproduce

Use SAMPLE BY with a query that returns no results.

### Expected Behavior

Return message ```0 rows in nn ms```

### Environment

```markdown
- **QuestDB version**: questdb-6.1.3-rt-linux-amd64
- **OS**: Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Browser**: Chrome 96.0.4664.110 (64 bit)
```

### Additional context

Log:
```console
2021-12-16T17:58:27.661521Z I i.q.c.h.p.JsonQueryProcessorState [37] exec [q='SELECT ts, pair, side, round(nsum(size)) as size
FROM liquidations
WHERE pair = 'ETC-USDT-PERP' and side = 'sell' and size > 500
SAMPLE BY 1m
ALIGN TO CALENDAR WITH OFFSET '00:00'
ORDER BY ts ASC
']
2021-12-16T17:58:27.661538Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-3, sql=SELECT ts, pair, side, round(nsum(size)) as size
FROM liquidations
WHERE pair = 'ETC-USDT-PERP' and side = 'sell' and size > 500
SAMPLE BY 1m
ALIGN TO CALENDAR WITH OFFSET '00:00'
ORDER BY ts ASC
]
2021-12-16T17:58:27.661543Z I i.q.c.h.p.JsonQueryProcessorState [37] execute-cached [skip: 0, stop: 1000]
2021-12-16T17:58:27.661714Z E i.q.c.h.p.JsonQueryProcessorState [37] Uh-oh. Error!
java.lang.AssertionError
        at io.questdb.griffin.engine.functions.columns.SymbolColumn.init(SymbolColumn.java:60)
        at io.questdb.cairo.sql.Function.init(Function.java:45)
        at io.questdb.griffin.engine.table.VirtualRecordCursorFactory.getCursor(VirtualRecordCursorFactory.java:74)
        at io.questdb.cutlass.http.processors.JsonQueryProcessorState.of(JsonQueryProcessorState.java:609)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:431)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeCachedSelect(JsonQueryProcessor.java:355)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:148)
        at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:211)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:568)
        at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:246)
        at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:89)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:162)
        at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:93)
        at io.questdb.mp.Worker.run(Worker.java:111)

2021-12-16T17:58:27.661803Z I i.q.c.h.HttpConnectionContext kicked out [fd=37]
2021-12-16T17:58:27.661806Z I http-server scheduling disconnect [fd=37, reason=5]
2021-12-16T17:58:27.661878Z I http-server disconnected [ip=172.22.192.1, fd=37, src=queue]
2021-12-16T17:58:27.661933Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-3, sql=SELECT ts, pair, side, round(nsum(size)) as size
FROM liquidations
WHERE pair = 'ETC-USDT-PERP' and side = 'sell' and size > 500
SAMPLE BY 1m
ALIGN TO CALENDAR WITH OFFSET '00:00'
ORDER BY ts ASC
]
```

### PR DESCRIPTION
**Pull request by eugenels**
Fixes https://github.com/questdb/questdb/issues/1786, Fixes #1704

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|1|100.00%|

File: core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java [hunk 1]
```diff
@@ -58,7 +58,8 @@ public CharSequence getSymbolB(Record rec) {
     @Override
     public void init(SymbolTableSource symbolTableSource, SqlExecutionContext executionContext) {
         this.symbolTable = symbolTableSource.getSymbolTable(columnIndex);
-        assert !symbolTableStatic || symbolTable != null;
+        //non-static symbol table must be non-null
+        assert symbolTableStatic || symbolTable != null;
```
Comment (ideoma) [inline core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java:62]: I think it's the other way around, when static symbol table is static it means non-null should exist. `getSymbolTable` is synonym to `getStaticSymbolTable`

src/main/java/io/questdb/griffin/engine/functions/eq/EqSymStrFunctionFactory.java

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/EmptyTableNoSizeRecordCursor.java|1|1|100.00%|
